### ISSUE TITLE
NullPointerException in ResourceRequestHandler

### ISSUE THREAD

**Issue by runningcode** [square/picasso#1004]
This crash happens often for our users but I can't seem to repro it. The crash seems to have only started happening after we started using Picasso to load contact images. I can't seem to figure out how this could happen.
```
java.lang.NullPointerException
       at com.squareup.picasso.ResourceRequestHandler.canHandleRequest(ResourceRequestHandler.java:39)
       at com.squareup.picasso.BitmapHunter.forRequest(BitmapHunter.java:416)
       at com.squareup.picasso.Dispatcher.performSubmit(Dispatcher.java:201)
       at com.squareup.picasso.Dispatcher.performSubmit(Dispatcher.java:175)
       at com.squareup.picasso.Dispatcher$DispatcherHandler.handleMessage(Dispatcher.java:482)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by f2prateek** [comment]
What does the code you are calling Picasso with look like?

**Comment by runningcode** [comment]
We use picasso to load images all over our app from the network, local resources and contact URIs, so I'm not sure which one is causing this NPE but the contact image loading code looks like something like this:
```
Uri baseUri = ContentUris.withAppendedId(ContactsContract.Contacts.CONTENT_URI, contactId);
Uri fullContactUri = Uri.withAppendedPath(baseUri, ContactsContract.Contacts.Photo.CONTENT_DIRECTORY);
if (fullContactUri != null) {
    picasso.load(fullContactUri).into(view);
}
```

our Picasso instance looks like this:
```
Picasso picasso = new Picasso.Builder(app)
				.downloader(new OkHttpDownloader(client))
				.listener(new Picasso.Listener() {
					@Override
					public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
						Utils.reportWarning(exception, "loading image " + uri);
					}
				})
				.build();
Picasso.setSingletonInstance(picasso);
```
Do you need any other details?
