### ISSUE TITLE
Picasso can't load some images from internet

### ISSUE THREAD

**Issue by mrleolink** [square/picasso#1024]
Picasso can't load these image on *Nexus 5 - 4.4.2* and *Genymotion 4.4.4*:
http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zed_1.jpg
OR
http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zed_2.jpg

Same error was given:
```
 java.io.IOException: Cannot reset
 at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
 at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
 at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
 at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 at java.lang.Thread.run(Thread.java:841)
 at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```

My code is very simple:

```java
public class A7 extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_7);
        ImageView image = (ImageView) findViewById(R.id.imageview);
        Picasso.Builder builder = new Picasso.Builder(this);
        builder.listener(new Picasso.Listener() {
            @Override
            public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                exception.printStackTrace();
            }
        });
        Picasso picasso = builder.build();
        picasso.load("http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zed_2.jpg")
                .fit()
                .centerCrop()
                .into(image);
    }
}
```

**Comment by mrleolink** [comment]
Never mind, it's duplicated with a lot of issues out there!
