### ISSUE TITLE
IOException: Cannot reset while loading local image

### ISSUE THREAD

**Issue by BaronZ** [square/picasso#1089]
Hi team,
I encountered java.io.IOException: Cannot reset while loading local image.
If I dont use resize, I got OutOfMemoryError
Picasson version is 2.5.2, below is how I use Picasso
`
Picasso.with(context).load(new File(path)).resize(100, 100).into(imageView);
`
StackTrace
```
 java.io.IOException: Cannot reset
            at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
            at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
            at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
            at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:848)
            at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```

**Comment by JakeWharton** [comment]
There are numerous issues tracking this already.

**Comment by BaronZ** [comment]
@JakeWharton works fine useing 2.4.0
