### ISSUE TITLE
OutOfMemoryError Nexus 7 version 5.1.1

### ISSUE THREAD

**Issue by busylee999** [square/picasso#1102]
Hi I faced this crash for my crash reporting tool, on same devices and same pictures. It seems that image is too large to be decoded by this devise, it depends on device yes, but why picasso does not detect possibles of device in rendering?

And is there any case to avoid this crashes?

java.lang.OutOfMemoryError: Failed to allocate a 360012 byte allocation with 238372 free bytes and 232KB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:988)
       at android.content.res.Resources.loadDrawableForCookie(Resources.java:2474)
       at android.content.res.Resources.loadDrawable(Resources.java:2381)
       at android.content.res.Resources.getDrawable(Resources.java:787)
       at android.content.res.Resources.getDrawable(Resources.java:752)
       at com.squareup.picasso.RequestCreator.getPlaceholderDrawable(RequestCreator.java:676)
       at com.squareup.picasso.RequestCreator.into(RequestCreator.java:664)
       at com.squareup.picasso.RequestCreator.into(RequestCreator.java:601)
       at com.busylee.ellada.ui.ApartmentView.bind(ApartmentView.java:88)
       at com.busylee.ellada.ui.ApartmentView.bind(ApartmentView.java:25)
       at com.busylee.ellada.adapter.BindableAdapter.onBindViewHolder(BindableAdapter.java:23)
       at com.busylee.ellada.adapter.BasicAdapter.getView(BasicAdapter.java:42)
       at android.widget.AbsListView.obtainView(AbsListView.java:2347)
       at android.widget.ListView.makeAndAddView(ListView.java:1864)
       at android.widget.ListView.fillDown(ListView.java:698)
       at android.widget.ListView.fillGap(ListView.java:662)
       at android.widget.AbsListView.trackMotionScroll(AbsListView.java:4991)
       at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4539)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:549)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by JakeWharton** [comment]
There's no way to avoid this unless you use less memory overall. Picasso isn't the cause of the OOM, it just happens to be around when it happens.

Use smaller images, use operators like `.fit()` and `resize()` to shrink the images when decoding, use pixel formats like `RGB_565` on photos to halve the byte allocation requirement, etc. There's no action for Picasso to take.
