### ISSUE TITLE
Image loading regression between 2.4.0 and 2.5.2

### ISSUE THREAD

**Issue by vishna** [square/picasso#1105]
The below will render the attached image correctly with picasso 2.4.0 but will fail with 2.5.2

```java
Picasso.with(context)
         .load("file:///android_asset/plane.jpg")
         .placeholder(new ColorDrawable(0))
         .resize(4096, 2730)
         .into(imageView);
```

![plane](https://cloud.githubusercontent.com/assets/121164/9170139/94ea64fe-3f60-11e5-8cb5-4a03b120e64b.jpg)

**Comment by JakeWharton** [comment]
Fail how? With what exception?

**Comment by lovetuzitong** [comment]
I have the same issue.  Load same high-resolution(4480x2688) image correctly with picasso 2.4.0 but will fail with 2.5.2. @JakeWharton 
```java
W/System.err﹕ java.io.IOException: Cannot reset
W/System.err﹕ at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
W/System.err﹕ at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
W/System.err﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
W/System.err﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
W/System.err﹕ at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```

**Comment by eygraber** [comment]
Dupe? https://github.com/square/picasso/issues/364

**Comment by JakeWharton** [comment]
Yep
