### ISSUE TITLE
4G network error

### ISSUE THREAD

**Issue by kvmaker** [square/picasso#1106]
when I use 4G network I got this.
picasso version:2.5.2
```
08-11 17:34:01.926  12996-13006/com.singlecountry.dscun E/StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
            at java.io.FileInputStream.<init>(FileInputStream.java:80)
            at java.util.Scanner.<init>(Scanner.java:158)
            at java.util.Scanner.<init>(Scanner.java:138)
            at android.net.NetworkInfo.getProcessName(NetworkInfo.java:522)
            at android.net.NetworkInfo.getConvertedSubtype(NetworkInfo.java:563)
            at android.net.NetworkInfo.getSubtype(NetworkInfo.java:207)
            at com.squareup.picasso.PicassoExecutorService.adjustThreadCount(PicassoExecutorService.java:54)
            at com.squareup.picasso.Dispatcher.performNetworkStateChange(Dispatcher.java:401)
            at com.squareup.picasso.Dispatcher$DispatcherHandler.handleMessage(Dispatcher.java:521)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by JakeWharton** [comment]
This is an Android bug, please file a bug on http://b.android.com. All we're doing is calling [`NetworkInfo.getSubtype()`][1].

 [1]: https://developer.android.com/reference/android/net/NetworkInfo.html#getSubtype()
