### ISSUE TITLE
invalidate() seems not to work in Picasso 2.5.2

### ISSUE THREAD

**Issue by oliverhausler** [square/picasso#1168]
I am using okhttp 2.5.0.

I am trying to load an image into a target:

        Picasso.with(boardView.getContext())
                .load(url).config(Constants.IMAGE_QUALITY_LOW).resize(width, height).centerCrop().noFade()
                .error(R.drawable.testpattern)
                .tag(boardView.getContext()).into(target);

Then if the bitmap fails to load, I invalidate and try to reload:

        @Override public void onBitmapFailed(Drawable errorDrawable) {
            transition(imagePreview.getBackground(), errorDrawable);
            if (lastUrl != null && lastUrl.startsWith("http")) {
                Picasso.with(boardView.getContext()).invalidate(lastUrl);
                // reload the image here
            }
        }

The url works when I post it into a browser.

https://storage.googleapis.com/closeup0002/C2ORBV0LRCGVZHr5ClKgTg.ANU3DbyV_EFMl0ICeti7aUQ.jpg

There are two possibilities here, as it seems:

1. Picasso fails on loading or scaling the image file, invalidates the cache and repeats.
2. Picasso does not invalidate the url and fails because the next cycle is picked from the cache over and over again.

I believe I am seeing 2.

**Comment by JakeWharton** [comment]
If an image cannot successfully be decoded then it will not be cached and
invalidate() will have no effect. It's essentially a no-op (except it
actually has to do a lot of string comparison actually).

**Comment by dyglcc** [comment]
I have the save issue,I found the target object is weakReference object .when getTarget() method in Action.java line number 76 return  null. that the reason why have no effect when invalidate view.

**Comment by oliverhausler** [comment]
@dyglcc I have my target fixed as instance variable, so this is not the case.

@JakeWharton How can I know if the image couldn't be properly decoded? Does Picasso tell me somehow why an image couldn't load. Problem is I don't get an error message in the callback.

**Comment by dyglcc** [comment]
@oliverhauser Maybe we have different case. But  i fixed it by changing WeekReference to SoftReference. I don't know if this is a suitable method.

**Comment by khaitq7** [comment]
I try use code
Argument(s) are different! Wanted:
cache.clearKeyUri(
    "file:///foo/bar/baz"
);
-> at com.squareup.picasso.PicassoTest.invalidateFile(PicassoTest.java:553)
Actual invocation has different arguments:
cache.clearKeyUri(
    "file://D%3A%5Cfoo%5Cbar%5Cbaz"
);
-> at com.squareup.picasso.Picasso.invalidate(Picasso.java:362)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.squareup.picasso.PicassoTest.invalidateFile(PicassoTest.java:553)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:234)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:175)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Exception in thread "Picasso-Dispatcher" java.lang.NullPointerException
	at org.robolectric.shadows.ShadowLooper.getMainLooper(ShadowLooper.java:59)
	at org.robolectric.shadows.ShadowLooper.doLoop(ShadowLooper.java:76)
	at org.robolectric.shadows.ShadowLooper.loop(ShadowLooper.java:64)
	at android.os.Looper.loop(Looper.java)
	at org.robolectric.shadows.ShadowHandlerThread.run(ShadowHandlerThread.java:34)
	at android.os.HandlerThread.run(HandlerThread.java)
Exception in thread "Picasso-Dispatcher" java.lang.NullPointerException
	at org.robolectric.shadows.ShadowLooper.getMainLooper(ShadowLooper.java:59)
	at org.robolectric.shadows.ShadowLooper.doLoop(ShadowLooper.java:76)
	at org.robolectric.shadows.ShadowLooper.loop(ShadowLooper.java:64)
	at android.os.Looper.loop(Looper.java)
	at org.robolectric.shadows.ShadowHandlerThread.run(ShadowHandlerThread.java:34)
	at android.os.HandlerThread.run(HandlerThread.java)
