### ISSUE TITLE
can not find class

### ISSUE THREAD

**Issue by carl1990** [square/picasso#1179]
I use picasso version 2.2+  and okhttp 2.4.0
 get the error 
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/okhttp/HttpResponseCache;
            at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:74)
            at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:51)
            at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:41)
            at com.squareup.picasso.Utils$OkHttpLoaderCreator.create(Utils.java:319)
            at com.squareup.picasso.Utils.createDefaultDownloader(Utils.java:171)
            at com.squareup.picasso.Picasso$Builder.build(Picasso.java:490)
            at com.squareup.picasso.Picasso.with(Picasso.java:390)

**Comment by JakeWharton** [comment]
That class does not exist in OkHttp anymore (since version 2.x), and Picasso doesn't reference it anymore either (since version 2.x). I don't think your dependencies line up properly and should be checked. You can use the `dependencies` task if you are using Gradle to get a nice list.
