### ISSUE TITLE
SecurityException: Unable to find app for caller android.app.ApplicationThreadProxy

### ISSUE THREAD

**Issue by digitalbuddha** [square/picasso#1197]
Few days ago we started seeing crashes in Hockey that looked like 
```
java.lang.RuntimeException: Unable to create application com.nytimes.android.NYTApplication: java.lang.SecurityException: Unable to find app for caller android.app.ApplicationThreadProxy@42b01348 (pid=14091) when getting content provider settings
```

The line throwing the error is:
```    
    Picasso picasso = new Picasso.Builder(this).build();
```

We are seeing it on a variety of device manufacturers but only for version 4.1.2 to 4.4 

full stacktrace
```
java.lang.RuntimeException: Unable to create application com.nytimes.android.NYTApplication: java.lang.SecurityException: Unable to find app for caller android.app.ApplicationThreadProxy@42b01348 (pid=14091) when getting content provider settings
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4775)
	at android.app.ActivityThread.access$1600(ActivityThread.java:170)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5635)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.SecurityException: Unable to find app for caller android.app.ApplicationThreadProxy@42b01348 (pid=14091) when getting content provider settings
	at android.os.Parcel.readException(Parcel.java:1465)
	at android.os.Parcel.readException(Parcel.java:1419)
	at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3299)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:4843)
	at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:2718)
	at android.content.ContentResolver.acquireProvider(ContentResolver.java:1421)
	at android.provider.Settings$NameValueCache.lazyGetProvider(Settings.java:1030)
	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:1111)
	at android.provider.Settings$Global.getStringForUser(Settings.java:11516)
	at android.provider.Settings$System.getStringForUser(Settings.java:1359)
	at android.provider.Settings$System.getIntForUser(Settings.java:1434)
	at android.provider.Settings$System.getInt(Settings.java:1426)
	at com.squareup.picasso.Utils.isAirplaneModeOn(SourceFile:291)
	at com.squareup.picasso.Dispatcher.<init>(SourceFile:115)
	at com.squareup.picasso.Picasso$Builder.build(SourceFile:827)
	at com.nytimes.android.NYTApplication.configurePicasso(SourceFile:189)
	at com.nytimes.android.NYTApplication.onCreate(SourceFile:99)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4772)
```

**Comment by JakeWharton** [comment]
Seems like an Android bug or perhaps the application is being started up for `adb backup` and not full UI. In either case, it's not Picasso's fault and there's not really anything we can do here. I'll leave it open for others to find I guess.

**Comment by digitalbuddha** [comment]
Hmm ok. Seems weird that it started last week with 300+ crashes so far. 

Seems like there needs to be a handled security exception here:

```
static boolean isAirplaneModeOn(Context context) {
    ContentResolver contentResolver = context.getContentResolver();
    try {
      return Settings.System.getInt(contentResolver, AIRPLANE_MODE_ON, 0) != 0;
    } catch (NullPointerException e) {
      // https://github.com/square/picasso/issues/761, some devices might crash here, assume that
      // airplane mode is off.
      return false;
    }
  }
```

**Comment by JakeWharton** [comment]
What phones? What API levels? Ideally this would be reproducible in some manner.

**Comment by digitalbuddha** [comment]
We have not been able to reproduce, QA has done at least 5 full regression tests on multiple devices and it never comes up but hockey has been reporting the crash more and more.  

stacktrace:
https://gist.github.com/digitalbuddha/0b3d25a176feb6bce637

<img width="1247" alt="screen shot 2015-12-07 at 10 48 31 pm" src="https://cloud.githubusercontent.com/assets/4528092/11647314/bb8da706-9d34-11e5-9838-cbb8d68b9f25.png">

<img width="1204" alt="screen shot 2015-12-07 at 10 50 24 pm" src="https://cloud.githubusercontent.com/assets/4528092/11647341/f578a9b6-9d34-11e5-8741-3af8225ee2a4.png">

<img width="983" alt="screen shot 2015-12-07 at 10 51 07 pm" src="https://cloud.githubusercontent.com/assets/4528092/11647357/0d44abf8-9d35-11e5-865a-e3877b836089.png">

Let me know if there's anything else that can help. Current Picasso version is 2.5.0

**Comment by JakeWharton** [comment]
Damn. Ok. Seems reasonable to try/catch then. We don't want to fail here.

**Comment by digitalbuddha** [comment]
I'll open a pr thanks

**Comment by fayou147** [comment]
@digitalbuddha hello, i have also encountered this problem , try-catch can solve this problem??
