### ISSUE TITLE
 java.lang.NoClassDefFoundError: com.squareup.picasso.OkHttpDownloader

### ISSUE THREAD

**Issue by anvesh523** [square/picasso#1249]
After updated my project in Android Studio 2.0 I am getting this error. 

I used the code like this: 

OkHttpClient okHttpClient = new OkHttpClient();
        okHttpClient.networkInterceptors().add(new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Response originalResponse = chain.proceed(chain.request());
                return originalResponse.newBuilder().header("Cache-Control", "max-age=" + (60 * 60 * 24 * 365)).build();
            }
        });
        FileCache fileCache;
        fileCache = new FileCache(this);
        okHttpClient.setCache(new Cache(fileCache.getFile(context), Integer.MAX_VALUE));
        OkHttpDownloader okHttpDownloader = new OkHttpDownloader(okHttpClient);

Complete Error: 

FATAL EXCEPTION: main
                                                                    java.lang.NoClassDefFoundError: com.squareup.picasso.OkHttpDownloader
                                                                        at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:212)
                                                                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4566)
                                                                        at android.app.ActivityThread.access$1300(ActivityThread.java:156)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                        at android.os.Looper.loop(Looper.java:153)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5299)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:511)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
Are you using multidex?

**Comment by anvesh523** [comment]
This is my gradle file. I am using mutidex. If I degraded the project to lower version it's working fine again. If I updated in Android Studio 2.0 ( gradle update ) i am getting error.

![instant run](https://cloud.githubusercontent.com/assets/10726276/12135245/38f70c46-b45f-11e5-97f0-ac69b4dc1155.png)
 

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.2'

    defaultConfig {
        applicationId "com.blpacademy.a2a"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"

        // Enabling multidex support.
        multiDexEnabled true

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    dexOptions {
        incremental true
        javaMaxHeapSize "4g"
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }
}


dependencies {
    provided fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:cardview-v7:23.1.1'
    compile 'com.android.support:recyclerview-v7:23.1.1'
    compile 'com.android.support:support-v4:23.1.1'
    compile 'com.melnykov:floatingactionbutton:1.1.0'
    compile 'com.android.support:design:23.1.1'
    compile 'org.apache.directory.studio:org.apache.commons.io:2.4'
    compile 'com.google.android.gms:play-services:8.4.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.7.0'
    compile 'com.squareup.okhttp:okhttp:2.7.0'
    compile 'com.squareup.okio:okio:1.6.0'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.koushikdutta.ion:ion:2.1.6'
    compile 'io.paperdb:paperdb:1.1'
    compile 'com.orhanobut:hawk:1.18'

}

**Comment by anvesh523** [comment]
Actually I am using only 2 dependencies .... 
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.squareup.okhttp:okhttp:2.7.0'

After I got the error, I searched in google and I added these 2 dependencies too
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.7.0'
    compile 'com.squareup.okio:okio:1.6.0'

Still not worked for me in 2.0

**Comment by JakeWharton** [comment]
Neither of those added two dependencies are needed. You should remove them.

That said, this is definitely not a problem with Picasso, but either Android Studio, the Android Gradle plugin, or multidex (or some combination of those). It's hard to know which is causing the problem or what to tell you to change. That class definitely exists inside Picasso's jar so something in your toolchain is causing the problem.

**Comment by AlexeiScherbakov** [comment]
I have similar problem without Picasso. This is a problem of Android Studio + com.android.tools.build 2.0
It is happened on devices lower than Android 5.
Solution - use com.android.tools.build:gradle:1.5.0

**Comment by JakeWharton** [comment]
Yes. As stated, this is a problem with the configuration of the build system, not of Picasso itself. Closing as a result.

**Comment by anvesh523** [comment]
Yes, I found the same. The problem with 2.0, If I changed to 1.5 it's working fine. Thank you.
