### ISSUE TITLE
Rotation 

### ISSUE THREAD

**Issue by Daard** [square/picasso#1297]
I have faced this bug in snapshot version.

 java.lang.OutOfMemoryError: Could not allocate JNI Env
                                                                    at java.lang.Thread.nativeCreate(Native Method)
                                                                    at java.lang.Thread.start(Thread.java:1063)
                                                                    at com.squareup.picasso.Picasso.<init>(Picasso.java:201)
                                                                    at com.squareup.picasso.Picasso$Builder.build(Picasso.java:869)

**Comment by Daard** [comment]
Several rotations were made before bug has been faced.

**Comment by Daard** [comment]
![unspecified](https://cloud.githubusercontent.com/assets/4972277/13043474/069c0616-d3d1-11e5-98d5-15f01ab85f2f.png)

**Comment by JakeWharton** [comment]
You are creating a new instance of Picasso every time you rotate. Don't do that. Create a single instance and re-use it for all your image loading.
