### ISSUE TITLE
java.lang.NullPointerException in com.squareup.picasso.BitmapHunter$4.run

### ISSUE THREAD

**Issue by remon** [square/picasso#1306]
```
java.lang.NullPointerException: Transformation r:[10.0, 10.0, 10.0, 10.0]b:0.0c:ColorStateList{mStateSpecs=[[]]mColors=[-16777216]mDefaultColor=-16777216}o:false returned null after 0 previous transformation(s).
Transformation list:
r:[10.0, 10.0, 10.0, 10.0]b:0.0c:ColorStateList{mStateSpecs=[[]]mColors=[-16777216]mDefaultColor=-16777216}o:false
	at com.squareup.picasso.BitmapHunter$4.run(BitmapHunter.java:452)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5323)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)
```

and here is my method to load the image 

~~~
 public void update_image_profiles(ImageView v, String url, ProgressBar mp){
        final ProgressBar mpp = mp;
        Transformation transformation = new RoundedTransformationBuilder()
                .cornerRadiusDp(5)
                .oval(false)
                .build();
            Picasso.with(getActivity()).load(url).
                  noFade().
                    placeholder(R.drawable.image_bg).transform(transformation).into(v, new Callback() {
                 @Override
                 public void onSuccess() {
                  mpp.setVisibility(View.GONE);
                 }
            @Override
            public void onError() {

            }
        });

    }
~~~

**Comment by JakeWharton** [comment]
The `RoundedTransformationBuilder` is returning `null` for its `Bitmap`. Ensure all code paths return non-null or if it isn't your project file an issue on it with the exception and example code.
