### ISSUE TITLE
Images not loading in Android N (Possibly Android N Exifinterface issue)

### ISSUE THREAD

**Issue by TheNuclearFalcon** [square/picasso#1315]
E/v: Failed to load bitmap aysnc
                                    java.io.IOException: Invalid marker: 89
                                        at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:946)
                                        at android.media.ExifInterface.loadAttributes(ExifInterface.java:651)
                                        at android.media.ExifInterface.<init>(ExifInterface.java:494)
                                        at com.squareup.picasso.FileRequestHandler.getFileExifRotation(FileRequestHandler.java:46)
                                        at com.squareup.picasso.FileRequestHandler.load(FileRequestHandler.java:42)
                                        at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
                                        at com.squareup.picasso.RequestCreator.get(RequestCreator.java:396)

**Comment by JakeWharton** [comment]
Android bug, not Picasso.
