### ISSUE TITLE
Android N: IllegalArgumentException

### ISSUE THREAD

**Issue by phileo** [square/picasso#1319]
I have  2 crash reports from out in the field, both on Android N (Nexus 6P) devices:

```
Fatal Exception: java.lang.IllegalArgumentException
       at java.util.concurrent.ThreadPoolExecutor.setCorePoolSize(ThreadPoolExecutor.java:1529)
       at com.squareup.picasso.PicassoExecutorService.setThreadCount(SourceFile:81)
       at com.squareup.picasso.PicassoExecutorService.adjustThreadCount(SourceFile:51)
       at com.squareup.picasso.Dispatcher.performNetworkStateChange(SourceFile:395)
       at com.squareup.picasso.Dispatcher$DispatcherHandler.handleMessage(SourceFile:515)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by JakeWharton** [comment]
We only call this method with the values 1-4 which are legal according to the Javadoc so I'm inclined to lean towards this being an Android bug.

**Comment by narayank** [comment]
I don't think this is an android bug. The issue is that the latest version of jsr-166 sources (which ship with OpenJdk8 and 9) have a check that the core pool size isn't greater than the max pool size.  You should perhaps update the max pool size before you update the core pool size. In other words, if you're *increasing* the thread count you should do

setMaxPoolSize(N);
setCorePoolSize(N);

instead of

setCorePoolSize(N);
setMaxPoolSize(N);

I have applied a platform workaround (https://android-review.googlesource.com/#/c/208931/) but it might be reverted in a future release.

**Comment by JakeWharton** [comment]
Got it. Will fix!
