### ISSUE TITLE
Does not load camera images on Marshmallow

### ISSUE THREAD

**Issue by jumsintheflow** [square/picasso#1361]
My app has "take photo" and "choose photo" features. 

Take Photo: Picasso does not load images taken by the camera.

Choose Photo: Picasso loads any images from gallery except those that were taken by phone's camera.

Using file manager, I copied a photo from camera directory to another folder wherein choosing and loading a photo works. All images on that folder works well on picasso except that specific photo that was captured by phone's camera. 

Im using picasso 2.5.2.2 from xamarin component.

**Comment by JakeWharton** [comment]
Please add an error listener to a `Picasso.Builder` instance and log the stacktrace of the error when the image fails to load.

**Comment by jumsintheflow** [comment]
Hi. I have run several test scenarios. Image loading is not consistent. There are photos from camera that loads into imageview successfully, usually smaller photos (in terms of pixel dimension). While some photos from the gallery won't load. 

I noticed that when i remove the .resize(300,300) option, all images loads successfully. My concern now is the memory usage of my app if i don't resize the images. Im using picasso on displaying images in gridview.

As for the stacktrace, Im using xamarin c#. Sample codes I get from posts and articles to log the stacktrace of the error doesn't work on c#.

**Comment by JakeWharton** [comment]
It's going to be impossible to help you then. Try 2.6.0-SNAPSHOT?

**Comment by jamesmundy** [comment]
Hi @jumsintheflow did you manage to get around this? In Android Marshmallow (using Xamarin) images have stopped loading for some of our users too: https://twitter.com/smartfilming/status/732668927596232704
We're using an older version of Picasso so the first thing we will try is upgrading the library. Will report back.

**Comment by jumsintheflow** [comment]
Hi. Not yet.. To be honest, im now using another image loader.

**Comment by antonc27** [comment]
Hello,

I have exactly same problem with Picasso: it fails to load images from gallery that were taken by camera.

Also, it works perfect on Android 4.4 and 5.0, but fails on 6.0

I'm using version 2.5.2 of Picasso, but problem still persist on 2.6.0-SNAPSHOT

The stack trace:

`E/PICASSO: file:///storage/emulated/0/DCIM/Camera/IMG_20160524_054633.jpg
 java.io.FileNotFoundException: /storage/emulated/0/DCIM/Camera/IMG_20160524_054633.jpg: open failed: EACCES (Permission denied)
     at libcore.io.IoBridge.open(IoBridge.java:452)
     at java.io.FileInputStream.<init>(FileInputStream.java:76)
     at java.io.FileInputStream.<init>(FileInputStream.java:103)
     at android.content.ContentResolver.openInputStream(ContentResolver.java:660)
     at com.squareup.picasso.ContentStreamRequestHandler.getInputStream(ContentStreamRequestHandler.java:44)
     at com.squareup.picasso.FileRequestHandler.load(FileRequestHandler.java:42)
     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
  Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
     at libcore.io.Posix.open(Native Method)
     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
     at libcore.io.IoBridge.open(IoBridge.java:438)
     at java.io.FileInputStream.<init>(FileInputStream.java:76) 
     at java.io.FileInputStream.<init>(FileInputStream.java:103) 
     at android.content.ContentResolver.openInputStream(ContentResolver.java:660) 
     at com.squareup.picasso.ContentStreamRequestHandler.getInputStream(ContentStreamRequestHandler.java:44) 
     at com.squareup.picasso.FileRequestHandler.load(FileRequestHandler.java:42) 
     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206) 
     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159) 
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
     at java.lang.Thread.run(Thread.java:818) 
     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)`

**Comment by JakeWharton** [comment]
You don't have permission to access that file.

**Comment by antonc27** [comment]
This is definitely the problem on Picasso side, because if I programatically copy image from gallery folder to temp folder and only after supply it to Picasso, it is working normal (@jumsintheflow already mentioned this)

In addition I already granted permissions in AndroidManifest.xml:
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />`

**Comment by JakeWharton** [comment]
I don't see how, as Picasso doesn't deal with permissions at all. It's
merely trying to load the path you gave it and the stack trace clearly
shows the problem happening inside the ContentResolver lookup.

**Comment by antonc27** [comment]
Thanks for your answers, Jake!
Btw I still cannot figure out exact problem here, as permissions already granted for app...

**Comment by obi-the-wombat** [comment]
Hello,

I have the same problem asjumsintheflow , Picasso doesn't load hight definition images (4288x2848). Tested in android 6.0 (emulator) and android 5.0.2 (galaxy tab) with Picasso 2.5.2 with Gradle.

I don't really known if the image is not loaded or if the ImageView becomes null. In fact, the ImageView doesn't appear on screen.
But if I don't use the .resize method, images appears well.

**Comment by yusukezzz** [comment]
@antonc27 If your `targetSdkVersion` is 23 (or higher) and not implemented runtime permission handling, please read the following articles.

https://developer.android.com/training/permissions/requesting.html
https://developer.android.com/guide/topics/security/permissions.html#normal-dangerous

**Comment by JakeWharton** [comment]
Not clear what action to take here.
