### ISSUE TITLE
StackOverFlow

### ISSUE THREAD

**Issue by parahall** [square/picasso#1363]
Guys,
We facing the following crash on prod:
Mostly 4.X.X

`Fatal Exception: java.lang.StackOverflowError
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1100)
       at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:844)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:493)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:195)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:208)
       at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:92)
       at android.widget.ImageView.onDraw(ImageView.java:1037)
       at android.view.View.draw(View.java:14544)
       at android.view.View.getDisplayList(View.java:13428)
       at android.view.View.getDisplayList(View.java:13470)
       at android.view.View.draw(View.java:14261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
       at android.view.View.getDisplayList(View.java:13423)
       at android.view.View.getDisplayList(View.java:13470)
       at android.view.View.draw(View.java:14261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
       at android.view.View.draw(View.java:14547)
       at android.view.View.getDisplayList(View.java:13428)
       at android.view.View.getDisplayList(View.java:13470)
       at android.view.View.draw(View.java:14261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
       at android.view.View.getDisplayList(View.java:13423)
       at android.view.View.getDisplayList(View.java:13470)
       at android.view.View.draw(View.java:14261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
       at android.view.View.getDisplayList(View.java:13423)
       at android.view.View.getDisplayList(View.java:13470)
       at android.view.View.draw(View.java:14261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
       at android.view.View.draw(View.java:14547)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.widget.ScrollView.draw(ScrollView.java:1608)
       at android.view.View.getDisplayList(View.java:13428)
       at android.view.View.getDisplayList(View.java:13470)
       at android.view.View.draw(View.java:14261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
       at android.view.View.draw(View.java:14547)
       at android.view.View.getDisplayList(View.java:13428)
       at android.view.View.getDisplayList(View.java:13470)
       at android.view.View.draw(View.java:14261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
       at android.view.View.draw(View.java:14547)
       at android.view.View.getDisplayList(View.java:13428)
       at android.view.View.getDisplayList(View.java:13470)
       at android.view.View.draw(View.java:14261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
       at android.view.View.getDisplayList(View.java:13423)
       at android.view.View.getDisplayList(View.java:13470)
       at android.view.View.draw(View.java:14261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
       at android.view.View.getDisplayList(View.java:13423)
       at android.view.View.getDisplayList(View.java:13470)
       at android.view.View.draw(View.java:14261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
       at android.view.View.getDisplayList(View.java:13423)
       at android.view.View.getDisplayList(View.java:13470)
       at android.view.View.draw(View.java:14261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1373)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
       at android.view.View.getDisplayList(View.java:13423)
       at android.view.View.getDisplayList(View.java:13470)
       at android.view.View.draw(View.java:14261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
       at android.view.View.getDisplayList(View.java:13423)
       at android.view.View.getDisplayList(View.java:13470)
       at android.view.View.draw(View.java:14261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
       at android.view.View.draw(View.java:14547)
       at com.android.internal.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:381)
       at android.view.View.getDisplayList(View.java:13428)
       at android.view.View.getDisplayList(View.java:13470)
       at android.view.View.draw(View.java:14261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
       at android.view.View.draw(View.java:14547)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2351)
       at android.view.View.getDisplayList(View.java:13428)
       at android.view.View.getDisplayList(View.java:13470)
       at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1583)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1453)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2487)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2316)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1946)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1044)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5840)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:768)
       at android.view.Choreographer.doCallbacks(Choreographer.java:581)
       at android.view.Choreographer.doFrame(Choreographer.java:551)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:754)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5333)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by parahall** [comment]
Any news? 
It's Crash #1 for all our users. It's have insane number of crashes :(

**Comment by JohnWowUs** [comment]
Why are you still using Picasso 2.5.1?

**Comment by parahall** [comment]
@JohnWowUs Is it fixed at 2.5.2?

**Comment by JakeWharton** [comment]
Can you repro this in the sample somehow? How do we reproduce this to figure out its cause?
