### ISSUE TITLE
BitmapHunter Exception - Unrecognized type of request

### ISSUE THREAD

**Issue by shekharsumn** [square/picasso#1364]
java.lang.IllegalStateException: Unrecognized type of request: Request{"https://s3-us-west-2.amazonaws.com/test-magictiger-uploads-thumbs/ccc33adf-0e01-4899-b4b1-868932913176.png”}
at com.squareup.picasso.BitmapHunter$2.load(BitmapHunter.java:66)
at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

I am unable to show using image using picasso....please find above the logs for this error.

**Comment by shekharsumn** [comment]
the url was inside the enclosing quotes ""....which was causing the exception

**Comment by littleshuang** [comment]
同求解答

**Comment by piffarettig** [comment]
In particular I had this error because the URL I was getting, as the error mentions, is not a valid URL that a handler can use. In particular, the URL string **had spaces** before the "http", like:

`" http://example.com/image.jpg".`

So I just had to call `trim()` on the url string, before loading it with Picasso, and worked great!
