### ISSUE TITLE
Throwing OutOfMemoryError  "Could not allocate JNI Env"

### ISSUE THREAD

**Issue by captain-miao** [square/picasso#1394]
```
compile 'com.github.captain-miao:recyclerviewutils:1.2.1-SNAPSHOT'

    @BindingAdapter({"compressImageUrl"})
    public static void loadImageCompress(ImageView imageView, String url) {
        //large -> b middle
        Picasso.Builder builder = new Picasso.Builder(imageView.getContext());
        builder.listener(new Picasso.Listener() {
            @Override
            public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                exception.printStackTrace();
                Log.e("Picasso Error", uri.toString());
            }
        });
        //recycle bitmap
        Drawable drawable = imageView.getDrawable();
        if (drawable instanceof BitmapDrawable) {
            imageView.setImageDrawable(null);
            Bitmap bitmap = ((BitmapDrawable) drawable).getBitmap();
            Log.d(TAG, "recycle bitmap, w:" + bitmap.getWidth() + ", h:" + bitmap.getHeight());
            bitmap.recycle();
        }
        builder.build()
                .load(url.replace("large", "bmiddle"))
                .memoryPolicy(MemoryPolicy.NO_CACHE, MemoryPolicy.NO_STORE)
                .placeholder(R.drawable.ic_image_load_place_holder)
                .config(Bitmap.Config.RGB_565)
                .into(imageView);
    }
```

**fast scroll RecycleView, load image more and more and more...**

```
 ** MEMINFO in pid 4695 [com.github.captain_miao.agera.tutorial] **
                   Pss  Private  Private  Swapped     Heap     Heap     Heap
                 Total    Dirty    Clean    Dirty     Size    Alloc     Free
                ------   ------   ------   ------   ------   ------   ------
  Native Heap    26019    25972        0        0    37376    33872     3503
  Dalvik Heap   172734   172632        0        0   196608   181382    15226
 Dalvik Other     5184     5184        0        0 
```
```
W/art: Throwing OutOfMemoryError  "Could not allocate JNI Env"
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.captain_miao.agera.tutorial, PID: 18267
    java.lang.OutOfMemoryError: Could not allocate JNI Env
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:1063)
        at com.squareup.picasso.Dispatcher.<init>(Dispatcher.java:102)
        at com.squareup.picasso.Picasso$Builder.build(Picasso.java:867)
        at com.github.captain_miao.agera.tutorial.helper.PicassoBinding.loadImageCompress(PicassoBinding.java:77)
        at com.github.captain_miao.agera.tutorial.databinding.RecyclerItemViewBinding.executeBindings(RecyclerItemViewBinding.java:114)
        at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:355)
        at com.github.captain_miao.agera.tutorial.recycleview.VehicleListAdapter.onBindItemViewHolder(VehicleListAdapter.java:45)

```
Try use pauseTag() from this blog [image-loading-with-picasso](https://nullpointer.wtf/android/image-loading-with-picasso/),it's  also not work.

Do you have other ideas? Thank you.

**Comment by captain-miao** [comment]
#561

**Comment by maduperera** [comment]
Yes that worked. Thanks @captain-miao.
