### ISSUE TITLE
Resource leak in Picasso detected using StrictMode logs

### ISSUE THREAD

**Issue by rahulrj** [square/picasso#1421]
```
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
 java.lang.Throwable: Explicit termination method 'close' not called
 at dalvik.system.CloseGuard.open(CloseGuard.java:184)
at java.io.FileInputStream.<init>(FileInputStream.java:78)
at okio.Okio.source(Okio.java:163)
 at com.squareup.okhttp.internal.io.FileSystem$1.source(FileSystem.java:44)
at com.squareup.okhttp.internal.DiskLruCache$Entry.snapshot(DiskLruCache.java:1001)
at com.squareup.okhttp.internal.DiskLruCache.get(DiskLruCache.java:429)
at com.squareup.okhttp.Cache.get(Cache.java:184)
 at com.squareup.okhttp.Cache$1.get(Cache.java:139)
at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:226)
at com.squareup.okhttp.Call.getResponse(Call.java:267)
 at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
 at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
at com.squareup.okhttp.Call.execute(Call.java:79)
at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:117)
at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
 at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```

**Comment by JakeWharton** [comment]
This was fixed in OkHttp 3. I strongly encourage you to update. You can use https://github.com/JakeWharton/picasso2-okhttp3-downloader/ to adapt it for Picasso until the next version is released with native OkHttp 3 support.
