### ISSUE TITLE
PicassoExecutorService.setThreadCount() IllegalArgumentException on API 24

### ISSUE THREAD

**Issue by austynmahoney** [square/picasso#1422]
Downloaded the DP4 emulator (API Level 24) and I get this crash when Picasso is first used.

v2.6.0-SNAPSHOT
```
FATAL EXCEPTION: Picasso-Dispatcher
    Process: {redacted-package}, PID: 6816
    java.lang.IllegalArgumentException
    at java.util.concurrent.ThreadPoolExecutor.setMaximumPoolSize(ThreadPoolExecutor.java:1659)
    at com.squareup.picasso.PicassoExecutorService.setThreadCount(PicassoExecutorService.java:83)
    at com.squareup.picasso.PicassoExecutorService.adjustThreadCount(PicassoExecutorService.java:66)
    at com.squareup.picasso.Dispatcher.performNetworkStateChange(Dispatcher.java:401)
    at com.squareup.picasso.Dispatcher$DispatcherHandler.handleMessage(Dispatcher.java:521)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by JakeWharton** [comment]
This was reported as broken and the behavior changed to support N... but now it's reversed and broken... WHHHYYYY

**Comment by JakeWharton** [comment]
Does this mean 2.5.2 just works?

**Comment by austynmahoney** [comment]
Yep

**Comment by eygraber** [comment]
Is [this commit](https://github.com/square/picasso/commit/5755afd36bf11977d81b773c7133a03139e0c57f) going to be reverted?

**Comment by JakeWharton** [comment]
No it's not going to be reverted

**Comment by xiaomingtuo** [comment]
is this problem had resolved? or which is the new version? i have got this exception with "2.5.3-snapshot" ,maybe this is helpful: 
[https://github.com/DikangGu/cassandra/commit/eea231de9200a55f14f87dc97ec8acbdaa3f8663]
