### ISSUE TITLE
Thread start plus application close

### ISSUE THREAD

**Issue by spidfire** [square/picasso#1424]
It's a edge case but maybe should be encapsulated by a try catch?
```
Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
       at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:989)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1131)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
       at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```

**Comment by JakeWharton** [comment]
Uhhh is this when the device is shutting down or something? I don't believe individual processes are shutdown gracefully ever otherwise.

**Comment by NightlyNexus** [comment]
I recall Prateek looked into a similar report.
https://github.com/segmentio/analytics-android/issues/490#issuecomment-270775091

i also wonder if there is more to the stack trace. the exception cause below perhaps?

**Comment by Grohden** [comment]
```
va.lang.InternalError: Thread starting during runtime shutdown
    at java.lang.Thread.nativeCreate(Thread.java)
    at java.lang.Thread.start(Thread.java:1063)
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1328)
    at com.squareup.picasso.PicassoExecutorService.submit(PicassoExecutorService.java:87)
    at com.squareup.picasso.Dispatcher.performRetry(Dispatcher.java:343)
    at com.squareup.picasso.Dispatcher$DispatcherHandler.handleMessage(Dispatcher.java:496)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.os.HandlerThread.run(HandlerThread.java:61)
```
same here, not sure what causes this
