### ISSUE TITLE
Unrecognized type of request on RequestCreator.get() in OFFLINE mode

### ISSUE THREAD

**Issue by skremon** [square/picasso#1426]
when the path or key for the image is not already cached.

Test code:
```
Picasso.with(context).load("avatar_uri").networkPolicy(NetworkPolicy.OFFLINE).get();
```

Result:
```
java.lang.IllegalStateException: Unrecognized type of request: Request{avatar_uri_from_platform_toobad}
06-22 11:46:46.784 29908  4612 E AndroidRuntime: 	at com.squareup.picasso.BitmapHunter$2.load(BitmapHunter.java:66)
06-22 11:46:46.784 29908  4612 E AndroidRuntime: 	at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
06-22 11:46:46.784 29908  4612 E AndroidRuntime: 	at com.squareup.picasso.RequestCreator.get(RequestCreator.java:396)
```

Note that this does not happen if an image is already cached with the path or key, then get() returns a Bitmap correctly in OFFLINE mode.
Also this does not happen with ReqeustCreator.fetch().

The purpose of calling get() in OFFLINE mode was to test if an image was cached by Picasso, it is common to find that the image was not cached, and a RuntimeException is not expected in those cases.

**Comment by JakeWharton** [comment]
I don't understand the problem. Can you provide a sample that demonstrates the issue?

**Comment by skremon** [comment]
Yeah, it happens if I pass in a key that is not a uri or resource. I had a case where I loaded an image and assigned a stable key that is a simple string (e.g. "abcdedfg"). Then I had a function to check if them image was cached in OFFLINE mode using get().
Here is a sample that produces the error:
```
final String testUriKey = "image_key";

        final Context context = this;
        Thread loaderThread = new Thread() {
            @Override
            public void run() {
                try {
                    Picasso.with(context).load(testUriKey).networkPolicy(NetworkPolicy.OFFLINE).get();
                } catch (IOException e) {
                    e.printStackTrace();
                }

            }
        };
        loaderThread.start();
```
