### ISSUE TITLE
crash when getting `connectivity` service on dual sim devices

### ISSUE THREAD

**Issue by scottmeng** [square/picasso#1478]
We have observed some crashes on `Dispatcher.NetworkBroadcastReceiver` when trying to get system `ConnectivityManager`. It seems to only happen on dual sim devices. Perhaps some simple exception handling will resolve the issue.

__Affected devices:__

samsung - SM-J700F
i-mobile - i-mobile i-STYLE 218
samsung - SM-G355M
JSR Tech - D10F 
samsung - SM-N9005
...

__Detailed stack trace:__
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in com.squareup.c.v@245f618d
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:941)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5930)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
Caused by: java.lang.NullPointerException: missing IConnectivityManager
	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:54)
	at android.net.ConnectivityManager.<init>(ConnectivityManager.java:1748)
	at android.app.ContextImpl$12.createService(ContextImpl.java:456)
	at android.app.ContextImpl$ServiceFetcher.getService(ContextImpl.java:341)
	at android.app.ContextImpl.getSystemService(ContextImpl.java:2079)
	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:569)
	at com.squareup.picasso.Utils.java.lang.Object getService(android.content.Context,java.lang.String)(SourceFile:304)
	at com.squareup.picasso.Dispatcher$NetworkBroadcastReceiver.void onReceive(android.content.Context,android.content.Intent)(SourceFile:579)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:931)
	... 8 more
java.lang.NullPointerException: missing IConnectivityManager
	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:54)
	at android.net.ConnectivityManager.<init>(ConnectivityManager.java:1748)
	at android.app.ContextImpl$12.createService(ContextImpl.java:456)
	at android.app.ContextImpl$ServiceFetcher.getService(ContextImpl.java:341)
	at android.app.ContextImpl.getSystemService(ContextImpl.java:2079)
	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:569)
	at com.squareup.picasso.Utils.java.lang.Object getService(android.content.Context,java.lang.String)(SourceFile:304)
	at com.squareup.picasso.Dispatcher$NetworkBroadcastReceiver.void onReceive(android.content.Context,android.content.Intent)(SourceFile:579)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:931)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5930)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

**Comment by JakeWharton** [comment]
Seems like a bug in Android. The stack trace isn't in Picasso code.

**Comment by gauravsak** [comment]
@JakeWharton Should this issue be closed then?
