### ISSUE TITLE
Getting Nullpointer when I try to call fit() on an image loaded from the sd card

### ISSUE THREAD

**Issue by KathiSick** [square/picasso#1479]
when I load my image like following it works fine
`picasso.load(uri).into(contentImageView);`
but when I add fit to resize the image to match the imageview (`picasso.load(uri).fit().into(contentImageView);`) I geht this exception:

`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.setHasAlpha(boolean)' on a null object reference`

another funny thing is, that when I call above method with an image from the web it works also fine.. there are only problems with local images and fit()

**Comment by JakeWharton** [comment]
Paste the full stscktrace

**Comment by KathiSick** [comment]
`08-31 14:57:45.236 20041-20041/at.mogree.thxfor W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.setHasAlpha(boolean)' on a null object reference
08-31 14:57:45.243 20041-20041/at.mogree.thxfor W/System.err:     at android.graphics.Bitmap.createBitmap(Bitmap.java:835)
08-31 14:57:45.243 20041-20041/at.mogree.thxfor W/System.err:     at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
08-31 14:57:45.243 20041-20041/at.mogree.thxfor W/System.err:     at android.graphics.Bitmap.createBitmap(Bitmap.java:739)
08-31 14:57:45.244 20041-20041/at.mogree.thxfor W/System.err:     at com.squareup.picasso.BitmapHunter.transformResult(BitmapHunter.java:558)
08-31 14:57:45.244 20041-20041/at.mogree.thxfor W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:232)
08-31 14:57:45.244 20041-20041/at.mogree.thxfor W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
08-31 14:57:45.244 20041-20041/at.mogree.thxfor W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
08-31 14:57:45.244 20041-20041/at.mogree.thxfor W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-31 14:57:45.244 20041-20041/at.mogree.thxfor W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-31 14:57:45.244 20041-20041/at.mogree.thxfor W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-31 14:57:45.244 20041-20041/at.mogree.thxfor W/System.err:     at java.lang.Thread.run(Thread.java:818)
08-31 14:57:45.244 20041-20041/at.mogree.thxfor W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)`

**Comment by JakeWharton** [comment]
Thank you. I'll take a look.

**Comment by KathiSick** [comment]
thank you! sorry I didn't know how to format the exception properly..

**Comment by KathiSick** [comment]
hey - did you already find something?
