### ISSUE TITLE
java.lang.Throwable: Explicit termination method 'close' not called 

### ISSUE THREAD

**Issue by snijsure** [square/picasso#1485]
I have following code in my Android app running in strict mode. I see following exception being thrown. I am closing the response item returned by the code below by invoking `response.close()`
fwiw I am using okio 1.10 and okhttp3 version 3.4.1

Am I using okhttp3 API wrong or issue really is in okio ?

`E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                     java.lang.Throwable: Explicit termination method 'close' not called
                                                                         at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                         at java.io.FileOutputStream.<init>(FileOutputStream.java:222)
                                                                         at okio.Okio.appendingSink(Okio.java:185)
                                                                         at okhttp3.internal.io.FileSystem$1.appendingSink(FileSystem.java:59)
                                                                         at okhttp3.internal.cache.DiskLruCache.newJournalWriter(DiskLruCache.java:310)
                                                                         at okhttp3.internal.cache.DiskLruCache.readJournal(DiskLruCache.java:302)
                                                                         at okhttp3.internal.cache.DiskLruCache.initialize(DiskLruCache.java:229)
                                                                         at okhttp3.internal.cache.DiskLruCache.get(DiskLruCache.java:431)
                                                                         at okhttp3.Cache.get(Cache.java:194)
                                                                         at okhttp3.Cache$1.get(Cache.java:144)
                                                                         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:70)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                                         at okhttp3.RealCall.execute(RealCall.java:60)
                                                                         at com.lonelyplanet.guides.data.cache.Downloader.getResponse(Downloader.java:83)`

Code that creates Response object is below.

`protected Response getResponse(OkHttpClient client,
                                              String downloadUrl)  {

    Request request = new Request.Builder().
            url(downloadUrl).get().build();

    Call httpRequest = client.newCall(request);

    try {

      return httpRequest.execute();

    }

    catch (Exception e) {

      Timber.e("Error downloading url %s",downloadUrl);

      return null;

    }
 
}`

**Comment by ankit209** [comment]
Were you able to fix this issue?

**Comment by JoyHong** [comment]
+1
