### ISSUE TITLE
Handler (com.squareup.picasso.Dispatcher$DispatcherHandler) {534b6bf} sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by rahulrj** [square/picasso#1489]
I frequently get these exceptions while downloading images. Its very intermittent and sometimes the image downloads successfully and most of the times the image download fails due to the above exception. Here is the complete stacktrace. 
It is not device specific and i have observed it in Android 7.0,Android 5.1,Android 6.0. I am using Picasso 2.5.2
The image URL is a simple URL like https://i.l.inmobicdn.net/ifctpads/IFC/CCN/assets/replay1470057094.png

```
Handler (com.squareup.picasso.Dispatcher$DispatcherHandler) {534b6bf} sending message to a Handler on a dead thread
java.lang.IllegalStateException: Handler (com.squareup.picasso.Dispatcher$DispatcherHandler) {534b6bf} sending message to a Handler on a dead thread
at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
at android.os.Handler.enqueueMessage(Handler.java:643)
at android.os.Handler.sendMessageAtTime(Handler.java:612)
at android.os.Handler.sendMessageDelayed(Handler.java:582)
at android.os.Handler.sendMessage(Handler.java:519)
at com.squareup.picasso.Dispatcher.dispatchFailed(Dispatcher.java:162)
at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:195)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:433)
```

**Comment by JakeWharton** [comment]
Please provide a sample or test that demonstrates the problem.

Picasso only shuts down the dispatcher when you call `.shutdown()`.
