### ISSUE TITLE
Unrecognized type of request for HTTP scheme

### ISSUE THREAD

**Issue by aryarohit07** [square/picasso#1493]
We are loading images synchronously to display notification once the image is loaded.

`bitmap = picasso.load(imageUrl).get();`

It was working fine but we got an exception on every device:

```
Fatal Exception: java.lang.IllegalStateException: Unrecognized type of request: Request{
http://www.fulbori.com/mp/resources/image/19/17/e.jpg}
       at com.squareup.picasso.BitmapHunter$2.load(BitmapHunter.java:66)
       at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
       at com.squareup.picasso.RequestCreator.get(RequestCreator.java:396)
       at com.jumbotail.app.utils.JtImageLoader.loadImageSync(JtImageLoader.java:397)
       at com.jumbotail.app.notifs.JumboGcmIntentService.readInboundIntent(JumboGcmIntentService.java:213)
       at com.jumbotail.app.notifs.JumboGcmIntentService.buildNotification(JumboGcmIntentService.java:273)
       at com.jumbotail.app.notifs.JumboGcmIntentService.onHandleIntent(JumboGcmIntentService.java:49)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:174)
       at android.os.HandlerThread.run(HandlerThread.java:60)
```

I understand that this exception is thrown when no request handlers can handle the request.

Now, as per the `Uri` scheme of the request (which is `http`) [`canHandleRequest(Request data)`](https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/NetworkRequestHandler.java#L43) method of [`NetworkRequestHandler`](https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/NetworkRequestHandler.java#L43) should have returned `true`.

But all the request handlers returned `false` including `NetworkRequestHandler`. Thus, [`ERRORING_HANDLER`](https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java#L431) was returned, resulting into the exception : `IllegalStateException("Unrecognized type of request: " + request)`.

Is there any other explanation to this exception?

Originally asked on [StackOverflow](http://stackoverflow.com/q/39456858/2720553).

**Comment by JakeWharton** [comment]
If you can provide a sample or failing test case that demonstrates this issue we'll fix it. Otherwise I don't see how this could happen.
