### ISSUE TITLE
Some images are errored if .resize() applied

### ISSUE THREAD

**Issue by frakc** [square/picasso#1514]
Hello, I am using picasso 2.5.2
If I load image with resize, then this image is always failed to load (most of images in same adapter loads well)
D: Main        created      [R196] Request{http://ellostatic-16d2.kxcdn.com/video_thumb/1857/video580e4513694c3.jpg resize(608,332) centerCrop}
D: Dispatcher  enqueued     [R196]+0ms 
D: Hunter      executing    [R196]+0ms 
D: Dispatcher  retrying     [R196]+507ms 
D: Hunter      executing    [R196]+508ms 
D: Dispatcher  retrying     [R196]+1015ms 
D: Hunter      executing    [R196]+1016ms 
D: Dispatcher  batched      [R196]+1528ms for error (will replay)
D: Dispatcher  delivered    [R196]+1730ms 
D: Main        errored      [R196]+1730ms 
D: Main        created      [R197] Request{http://ellostatic-16d2.kxcdn.com/user/1/574e2ec11906d.jpeg resize(176,100) centerCrop}
D: Main        completed    [R197] from MEMORY

But if i remove `.resize()` then image loads

**Comment by MizzleDK** [comment]
I'm seeing this as well.

**Comment by avrohith** [comment]
I have the same issue as well. Looks like nobody is looking at this ticket though.

**Comment by JakeWharton** [comment]
Add an exception listener and paste the stack trace

**Comment by avrohith** [comment]
Did the following to get the exception. 

Picasso.Builder builder = new Picasso.Builder(holder.itemView.getContext());
        builder.listener(new Picasso.Listener() {
            @Override
            public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                exception.printStackTrace();
            }
        });

        builder.build()
                .load("image url")
                .placeholder(R.drawable.placeholder)
                .resize(imageDimension, imageDimension)
                .transform(new CircularTransformation())
                .into(holder.imageView);

Please let me if this is not what you asked for. Thanks for looking into this.

04-14 15:05:18.950 1439-1439/com.amazon.browseintegration W/System.err: java.io.IOException: Cannot reset
04-14 15:05:18.950 1439-1439/com.amazon.browseintegration W/System.err:     at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
04-14 15:05:18.950 1439-1439/com.amazon.browseintegration W/System.err:     at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
04-14 15:05:18.951 1439-1439/com.amazon.browseintegration W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
04-14 15:05:18.951 1439-1439/com.amazon.browseintegration W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
04-14 15:05:18.951 1439-1439/com.amazon.browseintegration W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
04-14 15:05:18.951 1439-1439/com.amazon.browseintegration W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-14 15:05:18.951 1439-1439/com.amazon.browseintegration W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-14 15:05:18.951 1439-1439/com.amazon.browseintegration W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-14 15:05:18.951 1439-1439/com.amazon.browseintegration W/System.err:     at java.lang.Thread.run(Thread.java:818)
04-14 15:05:18.951 1439-1439/com.amazon.browseintegration W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

**Comment by avrohith** [comment]
Also, the imageDimension value here is 201dp which translates to 402Pixel on the device I am running and the image resolution is 797 X 1000. Just thought this would help debugging.

**Comment by JakeWharton** [comment]
Perfect. Thanks. We fixed this already on master. Can you try the
3.0.0-SNAPSHOT version?

**Comment by avrohith** [comment]
Oh cool, could you please tell me how to add the snapshot version in the gradle file?

**Comment by NightlyNexus** [comment]
```gradle
repositories {
  mavenCentral()
  maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}
dependencies {
  compile 'com.squareup.picasso:picasso:3.0.0-SNAPSHOT'
}
```

**Comment by avrohith** [comment]
@NightlyNexus Thanks a lot!!
@JakeWharton Yes, it works now!! Just out of curiosity, what was the issue?

**Comment by JakeWharton** [comment]
A weird behavior in Android interacting with bad code that I wrote!

**Comment by BeEagle** [comment]
@JakeWharton  How did this question occured？

**Comment by BeEagle** [comment]
@JakeWharton what was the cause?

**Comment by JakeWharton** [comment]
A weird behavior in Android interacting with bad code that I wrote!

**Comment by Droid3r** [comment]
I am facing the same issue. Same url with fit() and centreCrop() loads at one place and errors at another. Is there any workaround for this other than 3.0.0-SNAPSHOT

**Comment by siddrc** [comment]
I am facing this issue as well.. :(
The 3.0.0 snapshot workaround did not work for me

**Comment by siddrc** [comment]
I tried the fix in this link 
https://github.com/sarriaroman/photoviewer/issues/154#issuecomment-456187759
and all my problems were solved, build working fine.
Issue i think was unrelated and more specifically to do with the version of the plugin using Picasso.
Thanks guys
