### ISSUE TITLE
java.io.IOException: Cannot reset (Huge photo loading)

### ISSUE THREAD

**Issue by wGJUH** [square/picasso#1519]
picasso 2.5.2
Code:
`Picasso picasso = builder.build();
            picasso.load(new File(authorImagePath)).error(R.drawable.favorites).
                    placeholder(R.mipmap.ic_launcher).fit().centerCrop().into(imageView);
`

There is exception stacktrace 
`W/System.err: java.io.IOException: Cannot reset
W/System.err:     at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
W/System.err:     at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
`

**Comment by wGJUH** [comment]
Fixed by using snapshot-2.6.0
