### ISSUE TITLE
Resources$NotFoundException while loading placeholder drawable.

### ISSUE THREAD

**Issue by avrohith** [square/picasso#1524]
Hello,

I am seeing a Resources$NotFoundException while trying to load an image.

Here is the code for loading an image

```
Picasso.with(getContext())
                .load(currentAlbumArtUrl)
                .placeholder(R.drawable.placeholder_album_max)
                .error(R.drawable.placeholder_album_max)
                .into(albumCoverArt);
```

Below is the exception I am seeing

```
android.content.res.Resources$NotFoundException: File  from drawable resource ID #0x7f020125
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2600)
	at android.content.res.Resources.loadDrawable(Resources.java:2495)
	at android.content.res.Resources.getDrawable(Resources.java:794)
	at android.content.res.Resources.getDrawable(Resources.java:759)
	at com.squareup.picasso.RequestCreator.getPlaceholderDrawable(RequestCreator.java:676)
	at com.squareup.picasso.RequestCreator.into(RequestCreator.java:664)
	at com.squareup.picasso.RequestCreator.into(RequestCreator.java:601)
	at com.test.app.view.MyView.bind(MyView.java:153)
	at com.test.app.activity.MainActivity$4.run(MainActivity.java:355)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5466)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.io.FileNotFoundException: 
	at android.content.res.AssetManager.openNonAssetNative(Native Method)
	at android.content.res.AssetManager.openNonAsset(AssetManager.java:405)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2593)
	... 16 more
```

I don't see this happening on other devices or in my testing. After going through source code android's Resource class, I could trace the android was not able to fetch image path through AssetManager for some reason. Logs suggest the same as there is no value after "File  From". Any thoughts on this? Appreciate your help.

**Comment by JakeWharton** [comment]
All we do is call getDrawable with the ID you provide. The same would
happen if you called getDrawable yourself with the ID. I don't think
there's any action for us to take here.

**Comment by avrohith** [comment]
I thought the same as well. Not really why android could not get the drawable that declared as part of the resources. Just wanted to double check with you guys. Thanks for looking at this.
