### ISSUE TITLE
NoClassDefFoundError Failed resolution of Lorg/aspectj/runtime/reflect/Factory

### ISSUE THREAD

**Issue by hegazy** [square/picasso#1526]
The problem comes out of nowhere and kept happening with me until I replaced the downloader with OkHttpDownloader from `JakeWharton/picasso2-okhttp3-downloader`.

I'm using version `2.5.2`

```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/aspectj/runtime/reflect/Factory;
    at com.squareup.picasso.UrlConnectionDownloader.ajc$preClinit(UrlConnectionDownloader.java:1)
    at com.squareup.picasso.UrlConnectionDownloader.<clinit>(UrlConnectionDownloader.java)
    at com.squareup.picasso.Utils.createDefaultDownloader(Utils.java:253) 
    at com.squareup.picasso.Picasso$Builder.build(Picasso.java:832)    
    at com.squareup.picasso.Picasso.with(Picasso.java:662)
    at ***.util.BackgroundUtil.setBackgroundImage(BackgroundUtil.java:50)
    at ***.util.BackgroundUtil.setBackground(BackgroundUtil.java:34)
    at ***.ui.activity.account.**Activity.onCreate(**Activity.java:108)
    at ***.ui.activity.account.**Activity.onCreate(**Activity.java:45)
    at android.app.Activity.performCreate(Activity.java:6679)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)    
 Caused by: java.lang.ClassNotFoundException: Didn't find class "org.aspectj.runtime.reflect.Factory" on path: DexPathList[[zip file "/data/app/******-2/base.apk"],nativeLibraryDirectories=[/data/app/***-2/lib/x86, /system/lib, /vendor/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at com.squareup.picasso.UrlConnectionDownloader.ajc$preClinit(UrlConnectionDownloader.java:1) 
    at com.squareup.picasso.UrlConnectionDownloader.<clinit>(UrlConnectionDownloader.java) 
    at com.squareup.picasso.Utils.createDefaultDownloader(Utils.java:253) 
    at com.squareup.picasso.Picasso$Builder.build(Picasso.java:832)    
    at com.squareup.picasso.Picasso.with(Picasso.java:662) 
    at ***.util.BackgroundUtil.setBackgroundImage(BackgroundUtil.java:50) 
    at ***.util.BackgroundUtil.setBackground(BackgroundUtil.java:34) 
    at ***.ui.activity.account.**Activity.onCreate(**Activity.java:108) 
    at ***.ui.activity.account.**Activity.onCreate(**Activity.java:45) 
    at android.app.Activity.performCreate(Activity.java:6679) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
    at android.app.ActivityThread.-wrap12(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:6119) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)    
```

**Comment by JakeWharton** [comment]
This has something to do with your use of AspectJ and not strictly Picasso.

**Comment by hegazy** [comment]
It maybe a dependency issue, but I don't use AspectJ at all in the project! and I don't know why it always happens in this Downloader and I don't see it imported anywhere in the class.

**Comment by JakeWharton** [comment]
Something is using AspectJ. Are you using any tools in your build for
automatic logging or timing measurements?

**Comment by hegazy** [comment]
Yup, I'm using `Soasta`

**Comment by JakeWharton** [comment]
Somehow that is causing the problem then. I know nothing of that tool, though, so you'll have to inquire with its maintainers.
