### ISSUE TITLE
alway so log when invalid image, so it 's disagreeable

### ISSUE THREAD

**Issue by tritueviet** [square/picasso#1535]
ExifInterface: Invalid image.
                                                                            java.io.IOException: Invalid marker: 89
                                                                                at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1600)
                                                                                at android.media.ExifInterface.loadAttributes(ExifInterface.java:1339)
                                                                                at android.media.ExifInterface.<init>(ExifInterface.java:1057)
                                                                                at com.squareup.picasso.FileRequestHandler.getFileExifRotation(FileRequestHandler.java:46)
                                                                                at com.squareup.picasso.FileRequestHandler.load(FileRequestHandler.java:42)
                                                                                at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
                                                                                at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
                                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                at java.lang.Thread.run(Thread.java:818)
                                                                                at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

**Comment by JakeWharton** [comment]
This exception is thrown by Android when your JPEG is in an invalid format. If you can supply the JPEG we can take a look to see if it also fails decoding as a `Bitmap`.

**Comment by tritueviet** [comment]
Oh yes, but when i load many image and it alway is in valid example .gif it is show many log. i i thinks it should be disable! Thanks you very much!

**Comment by JakeWharton** [comment]
We don't really have control over it since it happens in Android's code, not Picasso.
