### ISSUE TITLE
picasso can't use in view

### ISSUE THREAD

**Issue by gomylife** [square/picasso#1536]
11-09 22:13:58.139 21942-21942/com.zeusis.launcher3 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.zeusis.launcher3, PID: 21942
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
                                                                          at com.squareup.picasso.UrlConnectionDownloader.<init>(UrlConnectionDownloader.java:50)
                                                                          at com.squareup.picasso.Utils.createDefaultDownloader(Utils.java:253)
                                                                          at com.squareup.picasso.Picasso$Builder.build(Picasso.java:832)
                                                                          at com.squareup.picasso.Picasso.with(Picasso.java:662)
                                                                          at com.zeusis.globalsearch.fragment.YellowPagesResultAppFragment$YellowPagesListViewAdapter.getView(YellowPagesResultAppFragment.java:91)
                                                                          at android.widget.AbsListView.obtainView(AbsListView.java:2417)
                                                                          at android.widget.ListView.measureHeightOfChildren(ListView.java:1326)
                                                                          at android.widget.ListView.onMeasure(ListView.java:1233)
                                                                          at com.zeusis.globalsearch.view.GlobalSearchListView.onMeasure(GlobalSearchListView.java:28)
                                                                          at android.view.View.measure(View.java:19987)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                          at android.view.View.measure(View.java:19987)
                                                                          at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                          at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                          at android.view.View.measure(View.java:19987)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at android.view.View.measure(View.java:19987)
                                                                          at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:7487)
                                                                          at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1416)
                                                                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                          at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
                                                                          at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2625)
                                                                          at android.view.View.measure(View.java:19987)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                          at android.view.View.measure(View.java:19987)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                          at android.view.View.measure(View.java:19987)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at android.view.View.measure(View.java:19987)
                                                                          at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2370)
                                                                          at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1378)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1627)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1266)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6417)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6077)
11-09 22:13:58.140 21942-21942/com.zeusis.launcher3 E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by JakeWharton** [comment]
The only way this happens is if you pass `null` to `Picasso.with` which we don't allow. If you can provide a test case or repro steps I'm happy to take a look, but I really can't see how this could happen.
