### ISSUE TITLE
Custom resize dimens not resize after pass integer fix value.

### ISSUE THREAD

**Issue by altaf933** [square/picasso#1549]
I did simply pass integer value in dimens format but unlike it's break the code .
     Picasso.with(this)
                    .load(url)
                    .placeholder(R.drawable.ic_user_place_holder)
                    .error(R.drawable.ic_user_place_holder)
                    .resizeDimen(80,30)
                    .transform(
                            new BitmapBorderTransformation(0, 5,
                                    Color.TRANSPARENT))
                    .into(getTargetStrongP2(relativeView)); 

Picasso version : 2.5.2
Look at below stack trace it may help you.

```
android.content.res.Resources$NotFoundException: Resource ID #0x50
 at android.content.res.Resources.getValue(Resources.java:997)
 at android.content.res.Resources.getDimensionPixelSize(Resources.java:581)
at com.squareup.picasso.RequestCreator.resizeDimen(RequestCreator.java:212)
 at com.sa.wws.activities.GameBoardActivity.setPlayer2HeaderScore(GameBoardActivity.java:4362)
 at com.sa.wws.activities.GameBoardActivity.preInitGameComponents(GameBoardActivity.java:2517)
 at com.sa.wws.activities.GameBoardActivity.initialCreationGameboard(GameBoardActivity.java:1185)
 at com.sa.wws.activities.GameBoardActivity.access$500(GameBoardActivity.java:168)
 at com.sa.wws.activities.GameBoardActivity$5.onPreDraw(GameBoardActivity.java:1111)
 at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:726)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2105)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1140)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4726)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:747)
 at android.view.Choreographer.doCallbacks(Choreographer.java:567)
 at android.view.Choreographer.doFrame(Choreographer.java:536)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:733)
 at android.os.Handler.handleCallback(Handler.java:615)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:153)
 at android.app.ActivityThread.main(ActivityThread.java:5000)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
 at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mwping** [comment]
I think the source code may help you

`  /** Resize the image to the specified dimension size. */
  public RequestCreator resizeDimen(int targetWidthResId, int targetHeightResId) {
    Resources resources = picasso.context.getResources();
    int targetWidth = resources.getDimensionPixelSize(targetWidthResId);
    int targetHeight = resources.getDimensionPixelSize(targetHeightResId);
    return resize(targetWidth, targetHeight);
  }`

try pass R.dimen.xxx to resizeDimen method

**Comment by altaf933** [comment]
Before i have to pass convert into `Int `format `getResources().getDimension(R.dimen.value) ` What I just tried add `Int `value in parameter . 
At some point for multiple resolution device that's working fine . 

At that time I was thought just simply at implementation `Int `should work.

**Comment by JakeWharton** [comment]
Use resize() if you have pixels. Otherwise resizeDimen takes R.dimen IDs
only.
