### ISSUE TITLE
ExifInterface is initialized for PNG files

### ISSUE THREAD

**Issue by sandaru1** [square/picasso#1573]
I'm trying to open a PNG file from Piccaso. It works properly but I'm seeing a warning.

>I/ExifInterface_JNI: Raw image not detected
01-11 15:04:48.657 2480-4845/com.medicaljoyworks.prognosis W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
		java.io.IOException: Invalid marker: 89
			at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1835)
      at android.media.ExifInterface.loadAttributes(ExifInterface.java:1475)
      at android.media.ExifInterface.<init>(ExifInterface.java:1112)
      at com.squareup.picasso.FileRequestHandler.getFileExifRotation(FileRequestHandler.java:46)
      at com.squareup.picasso.FileRequestHandler.load(FileRequestHandler.java:42)
      at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
      at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
      at java.lang.Thread.run(Thread.java:761)
      at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

According to the JavaDocs, the ExifInterface doesn't support PNGs (https://developer.android.com/reference/android/media/ExifInterface.html).

Is there an option I can pass to picasso indicating that the image is a PNG and it will not initialize ExifInterface?

**Comment by JohnWowUs** [comment]
You can always write your own custom request handler if you think it's worth it. See [https://futurestud.io/tutorials/picasso-custom-request-handlers](here) for how to go about it.

**Comment by mhelder** [comment]
Would just like to add that a similar issue occurs with other non-JPEG files, like WebP:

```
W/ExifInterface: Invalid image.
    java.io.IOException: Invalid marker: 52
    at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1600)
    at android.media.ExifInterface.loadAttributes(ExifInterface.java:1339)
    at android.media.ExifInterface.<init>(ExifInterface.java:1057)
    at com.squareup.picasso.FileRequestHandler.getFileExifRotation(FileRequestHandler.java:46)
    at com.squareup.picasso.FileRequestHandler.load(FileRequestHandler.java:42)
    at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
    at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
    at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```

Picasso 2.5.2
LG Nexus 5 @ API 23

Haven't had a chance to test on other API levels yet. For now, I've rolled my own version of `FileRequestHandler` that simply doesn't use `ExifInterface` at all, which works because in my particular case the WebP files are downloaded in a bundle before being served to the user *and* I know they don't require any client-side orientation adjustments (and I'm not piping any other image files through Picasso). 

If the exif orientation logic weren't all package-private, I would've given the ExifInterface Support Library a go. :)

**Comment by JakeWharton** [comment]
We use the support exif library now which does not crash on non-JPGs.
