### ISSUE TITLE
Image not loading when URL needs authentication

### ISSUE THREAD

**Issue by zenith22** [square/picasso#1579]
Trying to load an image from an URL that needs authentication, but picasso fails in error.
Am using com.squareup.picasso:picasso:2.5.2 and com.squareup.okhttp:okhttp:2.7.5'

Below is my code 

```
import com.squareup.okhttp.Interceptor;
import com.squareup.okhttp.OkHttpClient;
import com.squareup.okhttp.Request;
import com.squareup.okhttp.Response;
import com.squareup.picasso.Downloader;
import com.squareup.picasso.OkHttpDownloader;
import com.squareup.picasso.Picasso;

 public Picasso getPicasso() {
        Picasso.Builder builder = new Picasso.Builder(this);
        builder.loggingEnabled(true);
        OkHttpClient client = new OkHttpClient();
        client.setFollowRedirects(true);
        client.setFollowSslRedirects(true);
        client.networkInterceptors().add(new MyInterceptor());

        Downloader downloader = new OkHttpDownloader(client);

        return builder.downloader(downloader).build();
    }

public class MyInterceptor implements Interceptor {

        @Override
        public Response intercept(Chain chain) throws IOException {
            Request newRequest = chain.request().newBuilder()
                    .header("key", "value")
                    .header("Content-Type","image/*")
                    .method("GET",chain.request().body())
                    .build();

            return chain.proceed(newRequest);
        }
    }
```

Method call
`        getPicasso().load("myURL").into(imageView);
`

I tried downloading the image using the same key/value as headers in a Rest Client and the image gets downloaded.

What could I be possibly doing wrong? Please can someone point in right direction.

**Comment by JakeWharton** [comment]
Looks good to me. What's the error returned?

**Comment by zenith22** [comment]
Used below code to check the error

```
builder.listener(new Picasso.Listener() {
            @Override
            public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                exception.printStackTrace();
            }
        });
```

The exception is as follows
```

	java.net.ProtocolException: Too many follow-up requests: 21
    at com.squareup.okhttp.Call.getResponse(Call.java:335)
    at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
    at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
    at com.squareup.okhttp.Call.execute(Call.java:80)
    at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:117)
    at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
    at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
    at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
    at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```

The exception remains same even if I remove the interceptor, also tried ths solution mentioned here, but no luck.
http://stackoverflow.com/questions/29456534/handling-authentication-in-okhttp

**Comment by JakeWharton** [comment]
This indicates that the URL either requires 20+ redirects to get to the real image or what's more likely is that there's a redirect loop.

**Comment by zenith22** [comment]
But as mentioned earlier it works with a REST client and also when I hit the URL using chrome it first redirects to login page, post login it loads the image.

What could be a possible fix to this?

**Comment by JakeWharton** [comment]
I don't know, but it doesn't seem to be a problem with Picasso. Can you request the image using OkHttp directly and get a response?

**Comment by zenith22** [comment]
Tried using OkHttp directly and the exception is same.
java.net.ProtocolException: Too many follow-up requests: 21

**Comment by JakeWharton** [comment]
Well that confirms that it's not a Picasso issue. Are you positive you're configuring the request the same way? Can you consult your server engineers or the support of the API you're talking to about it?
