### ISSUE TITLE
Help needed. Image not downloading from a particular type of url.

### ISSUE THREAD

**Issue by free4murad** [square/picasso#1599]
I am downloading an image like this.
`Picasso.with(MyActivity.this)`
                `.load(Uri.parse(imageURL))`
                `.into(imageTarget);`
For url like these (https://storage.googleapis.com/eventyay.com/events/6/speakers/2167/photo/ZFd5OHBEam/1485777076.63.png) the above code is working fine.

But when the images are large in size I am using https://rsz.io/ to reduce the image size which gives me a new url (https://storage.googleapis.com.rsz.io/eventyay.com/events/6/speakers/2167/photo/ZFd5OHBEam/1485777076.63.png?width=200)

When I am using the second url the above code is not working.
Can some one please help.

**Comment by JakeWharton** [comment]
What version? What's logged when you turn on debug logs? What exceptions
are passed to the exception listener?

**Comment by free4murad** [comment]
Version - Picasso 2.5.2
Log - 
```
03-09 10:41:23.951 20806-20806/org.fossasia.openevent W/System.err: javax.net.ssl.SSLPeerUnverifiedException: Hostname storage.googleapis.com.rsz.io not verified:
03-09 10:41:23.951 20806-20806/org.fossasia.openevent W/System.err:     certificate: sha1/BDj6BYAnMNVGVHI1N2KiDmtUnvg=
03-09 10:41:23.951 20806-20806/org.fossasia.openevent W/System.err:     DN: 1.2.840.113549.1.9.1=#1611706f73746d61737465724072737a2e696f,CN=*.rsz.io,O=Rafael Baptista,L=Arlington,ST=Massachusetts,C=US
03-09 10:41:23.951 20806-20806/org.fossasia.openevent W/System.err:     subjectAltNames: [*.rsz.io, rsz.io, *.com.rsz.io, *.org.rsz.io, *.net.rsz.io, *.nl.rsz.io, *.jp.rsz.io, *.co.uk.rsz.io, *.fr.rsz.io, *.de.rsz.io, *.it.rsz.io, *.es.rsz.io, *.ru.rsz.io]
03-09 10:41:23.952 20806-20806/org.fossasia.openevent W/System.err:     at com.android.okhttp.Connection.connectTls(Connection.java:241)
03-09 10:41:23.952 20806-20806/org.fossasia.openevent W/System.err:     at com.android.okhttp.Connection.connectSocket(Connection.java:199)
03-09 10:41:23.952 20806-20806/org.fossasia.openevent W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:172)
03-09 10:41:23.952 20806-20806/org.fossasia.openevent W/System.err:     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
03-09 10:41:23.952 20806-20806/org.fossasia.openevent W/System.err:     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
03-09 10:41:23.953 20806-20806/org.fossasia.openevent W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
03-09 10:41:23.953 20806-20806/org.fossasia.openevent W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
03-09 10:41:23.953 20806-20806/org.fossasia.openevent W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
03-09 10:41:23.953 20806-20806/org.fossasia.openevent W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
03-09 10:41:23.953 20806-20806/org.fossasia.openevent W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
03-09 10:41:23.953 20806-20806/org.fossasia.openevent W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
03-09 10:41:23.953 20806-20806/org.fossasia.openevent W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
03-09 10:41:23.953 20806-20806/org.fossasia.openevent W/System.err:     at com.squareup.picasso.UrlConnectionDownloader.load(UrlConnectionDownloader.java:93)
03-09 10:41:23.953 20806-20806/org.fossasia.openevent W/System.err:     at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
03-09 10:41:23.953 20806-20806/org.fossasia.openevent W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
03-09 10:41:23.953 20806-20806/org.fossasia.openevent W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
03-09 10:41:23.953 20806-20806/org.fossasia.openevent W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
03-09 10:41:23.953 20806-20806/org.fossasia.openevent W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-09 10:41:23.953 20806-20806/org.fossasia.openevent W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-09 10:41:23.954 20806-20806/org.fossasia.openevent W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-09 10:41:23.954 20806-20806/org.fossasia.openevent W/System.err:     at java.lang.Thread.run(Thread.java:761)
03-09 10:41:23.954 20806-20806/org.fossasia.openevent W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```

**Comment by free4murad** [comment]
The issue is with the certification so if you change the protocol from `https` to `http` the image will load.
But I want to know if there is some inbuilt library support of such URLs.

**Comment by JakeWharton** [comment]
This exception comes from the HTTP client, not Picasso. You either need to
configure the default HTTP client in Java to support talking to your image
host or use a superior client like OkHttp which likely can talk to it
without any additional configuration. For OkHttp, though, you need to set
up the Downloader on Picasso.Builder for it to be used.

**Comment by free4murad** [comment]
@JakeWharton 
Thanks, I figured it out.

**Comment by NightlyNexus** [comment]
(Also, if you just add OkHttp, [it'll be set as the default](https://github.com/square/picasso/blob/6930ff127ed59bb8a51d4fcd9a836514922b8c00/picasso/src/main/java/com/squareup/picasso/Utils.java#L250) without setting the Downloader explicitly, though you probably should anyway.)
