### ISSUE TITLE
Canvas: trying to use a recycled bitmap android.graphics.Bitmap

### ISSUE THREAD

**Issue by Qamar4P** [square/picasso#1604]
There is an issue

```
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@f4db2e9
                                                                                         at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
                                                                                         at android.graphics.Canvas.drawBitmap(Canvas.java:1404)
                                                                                         at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:544)
                                                                                         at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:96)
                                                                                         at android.widget.ImageView.onDraw(ImageView.java:1246)
                                                                                         at android.view.View.draw(View.java:16184)
                                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                                         at android.view.View.draw(View.java:15954)
                                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                                         at android.view.View.draw(View.java:15954)
                                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                         at android.widget.AbsListView.dispatchDraw(AbsListView.java:2615)
                                                                                         at android.view.View.draw(View.java:16187)
                                                                                         at android.widget.AbsListView.draw(AbsListView.java:4166)
```
ListAdapter getView code
```
@Override
    public View getView(final int position, View convertView, ViewGroup parent) {
View rowView = convertView;

        if (rowView == null) {
            rowView = inflater.inflate(R.layout.list_item_coupons, null);
        }

        ImageView image = (ImageView) rowView.findViewById(R.id.image);
        String url = BuildConfig.imagesUrl + mList.get(position).getImage();
       
            Picasso.with(context)
                    .load(url)
                    .into(image);
return rowView;
       }
```

**Comment by AbhirojPanwar** [comment]
Can you please share the logs after using Picasso's setLoggingEnabled(true).

**Comment by Qamar4P** [comment]
```
W/Bitmap: Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
D/Picasso: Main        completed    [R116] from MEMORY
D/AndroidRuntime: Shutting down VM
D/Picasso: Hunter      decoded      [R108]+1978ms 
D/Picasso: Main        created      [R118] Request{https://abc.xyz/uploads/1471380484.0247.png}
W/GAv4: syncDispatchLocalHits timed out: java.util.concurrent.TimeoutException
        --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
```

**Comment by AbhirojPanwar** [comment]
@Qamar4P  Okay, so you are first checking whether the bitmap is recycled or not, right?

**Comment by Qamar4P** [comment]
Yes, you are right. Just to avoid crash. As you can see from code, this should show empty image but it's working for me. May be this happen for few draw calls.
By the way at the same time I try to fetch HD images in background service.

**Comment by AbhirojPanwar** [comment]
@Qamar4P  great! :)

**Comment by JakeWharton** [comment]
Picasso doesn't recycle Bitmaps so something else must be doing it. Without a test case that demonstrates the problem it's hard to know what's really going on. Do you think you can create one?

**Comment by Qamar4P** [comment]
May be!
I shared my logs (Which points picasso) and may be background service hits same url. (Pre-fetching image in background). mean while loading in views. Looks like
```
Void doBackground(Void params...){
...
Bitmap bm = Picasso.with(SyncData.this).load(imageUrl).get();
                                if (bm != null) {
                                   datasource.updateHighResStatus(entry.getKey());
                                    bm.recycle();
                                }
```
 May be it's return same image from cache that causes this crash.

I don't know if there is relation with this https://github.com/charbgr/BlurNavigationDrawer library. 
If there is no issue in picasso then close this issue.

**Comment by foxcode7** [comment]
you can try set memoryPolicy(MemoryPolicy.NO_CACHE, MemoryPolicy.NO_STORE)

**Comment by xuezhimin** [comment]
> ```
> W/Bitmap: Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
> D/Picasso: Main        completed    [R116] from MEMORY
> D/AndroidRuntime: Shutting down VM
> D/Picasso: Hunter      decoded      [R108]+1978ms 
> D/Picasso: Main        created      [R118] Request{https://abc.xyz/uploads/1471380484.0247.png}
> W/GAv4: syncDispatchLocalHits timed out: java.util.concurrent.TimeoutException
>         --------- beginning of crash
> E/AndroidRuntime: FATAL EXCEPTION: main
> ```
> 
> For now I solve issue with `CustomImageView`
> 
> ```
> @Override
>     protected void onDraw(Canvas canvas) {
>         if(getDrawable() instanceof BitmapDrawable){
>             if (((BitmapDrawable)getDrawable()).getBitmap().isRecycled()) {
>                 return;
>             }
>         }
> 
>         super.onDraw(canvas);
>     }
> ```
> 
> and to reduce requests. I change in adapter `getView`
> 
> ```
> if(holder.position != position) {
>             ListItem item = items.get(position);
>             holder.bind(item);
>             holder.position = position;
>         }
> ```

 Is need  custom Imageview?

**Comment by Qamar4P** [comment]
@xuezhimin It's simple just extend from ImageView and add the following method
```
@Override
    protected void onDraw(Canvas canvas) {
        if(getDrawable() instanceof BitmapDrawable){
            if (((BitmapDrawable)getDrawable()).getBitmap().isRecycled()) {
                return;
            }
        }

        super.onDraw(canvas);
    }
```
