### ISSUE TITLE
cannot load  images  taken  by camera on oneplus 3   7.1.1

### ISSUE THREAD

**Issue by pwunsch** [square/picasso#1629]
pictures taken by camera on onePlus3  device are not loaded  with picasso 2.5.2   version  2.4.0  seems to  work fine   pictures  are JPEG  because taken by camera  but log shows error 

W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
                                                                    java.io.IOException: Invalid marker: 89
                                                                        at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1854)
                                                                        at android.media.ExifInterface.loadAttributes(ExifInterface.java:1490)
                                                                        at android.media.ExifInterface.<init>(ExifInterface.java:1119)
                                                                        at com.squareup.picasso.FileRequestHandler.getFileExifRotation(FileRequestHandler.java:46)
                                                                        at com.squareup.picasso.FileRequestHandler.load(FileRequestHandler.java:42)
                                                                        at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
                                                                        at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                        at java.lang.Thread.run(Thread.java:761)
                                                                        at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

**Comment by pwunsch** [comment]
works  on 2.5.2  if I remove fit()

**Comment by S1lv10Fr4gn4n1** [comment]
I'm facing a similar problem on my oneplus 3t (7.1.1) with picasso 2.5.2. Removing `.resize` it works.

```
Bitmap bitmap = Picasso.with(context)
        .load(imageFile)
        .rotate(rotation)
        .resize(maxWidth, maxHeight)
        .centerInside()
        .transform(new GrayscaleTransformation())
        .get();
```

```
Caused by: java.io.IOException: Cannot reset
  at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
  at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
  at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
  at com.squareup.picasso.RequestCreator.get(RequestCreator.java:396)
```

**Comment by JakeWharton** [comment]
Thanks. This is fixed on master already. Want to try out the 3.0.0-SNAPSHOT version?

**Comment by alextorres50** [comment]
Same result with 3.0.0-SNAPSHOT version on Moto G5
