### ISSUE TITLE
FATAL EXCEPTION when call API rotate(70f,122f,220f)，but it's normal  as rotate(90f,122f,220f) etc

### ISSUE THREAD

**Issue by yuzhimin999** [square/picasso#1642]
FATAL EXCEPTION when call API .rotate(70f,122f,220f)，but it's normal  as .rotate(90f,122f,220f),.rotate(0f,122f,220f),or .resize(200,200).rotate(70f,122f,220f)

Version ； picasso-2.5.2
code

`Picasso singleton;`

`singleton = Picasso.with(mcontext);`

`singleton.setIndicatorsEnabled(true); `

`singleton.setLoggingEnabled(true);`

`singleton.load(list.get(position)).rotate(70f,122f,220f).into(viewHolder.imagelist);`

07-11 16:03:54.906 26274-26339/com.zm.userpicasso D/Picasso: Hunter      transformed  [R12]+1346ms 
07-11 16:03:54.907 26274-26336/com.zm.userpicasso D/Picasso: Dispatcher  batched      [R12]+1347ms for completion
07-11 16:03:55.111 26274-26274/com.zm.userpicasso D/Picasso: Main        completed    [R12]+1551ms from DISK
07-11 16:03:55.111 26274-26336/com.zm.userpicasso D/Picasso: Dispatcher  delivered    [R12]+1551ms 
07-11 16:03:55.119 26274-26274/com.zm.userpicasso D/AndroidRuntime: Shutting down VM
07-11 16:03:55.124 26274-26274/com.zm.userpicasso E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.zm.userpicasso, PID: 26274
                                                                    java.lang.RuntimeException: **Canvas: trying to draw too large(157599736bytes) bitmap.**
                                                                        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:260)
                                                                        at android.graphics.Canvas.drawBitmap(Canvas.java:1415)
                                                                        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:528)
                                                                        at **com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:110)**
                                                                        at android.widget.ImageView.onDraw(ImageView.java:1298)
                                                                        at android.view.View.draw(View.java:17292)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16274)
                                                                        at android.view.View.draw(View.java:17058)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3739)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16269)
                                                                        at android.view.View.draw(View.java:17058)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3739)
                                                                        at android.widget.ListView.drawChild(ListView.java:3508)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
                                                                        at android.widget.AbsListView.dispatchDraw(AbsListView.java:2718)
                                                                        at android.widget.ListView.dispatchDraw(ListView.java:3503)
                                                                        at android.view.View.draw(View.java:17295)
                                                                        at android.widget.AbsListView.draw(AbsListView.java:4509)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16274)
                                                                        at android.view.View.draw(View.java:17058)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3739)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16269)
                                                                        at android.view.View.draw(View.java:17058)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3739)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16269)
                                                                        at android.view.View.draw(View.java:17058)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3739)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16269)
                                                                        at android.view.View.draw(View.java:17058)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3739)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16269)
                                                                        at android.view.View.draw(View.java:17058)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3739)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16269)
                                                                        at android.view.View.draw(View.java:17058)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3739)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
                                                                        at android.view.View.draw(View.java:17295)
                                                                        at com.android.internal.policy.DecorView.draw(DecorView.java:779)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16274)
                                                                        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:674)
                                                                        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:680)
                                                                        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:788)
                                                                        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2964)
                                                                        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2755)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2328)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1328)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6599)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:890)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:692)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:876)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:173)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6519)
                                                                        at java.lang.reflect.Method.invoke(Native Method)

**Comment by JakeWharton** [comment]
There's nothing Picasso can do about this. This exception is from Android on a Bitmap that it thinks is too large.

**Comment by willemevenwel** [comment]
Is there any way that one can catch this exception?

**Comment by Hesham-Salama** [comment]
@willemevenwel For this case you can't.

**Comment by pankaj-sequoia** [comment]
I got same Exception it is from Picasso only when I used Glide it loads image fine the size of the image was 34.9 mb
