### ISSUE TITLE
GLES20DisplayList.java line 39 - android.view.GLES20DisplayList.<init>

### ISSUE THREAD

**Issue by razmaimon** [square/picasso#1648]
happens on Android 4.4.2, with picasso:2.3.3, we know it's an old version . but we need to know if this was fixed in newer versions.

Fatal Exception: java.lang.StackOverflowError
       at android.view.GLES20DisplayList.<init>(GLES20DisplayList.java:39)
       at android.view.HardwareRenderer$Gl20Renderer.createDisplayList(HardwareRenderer.java:2191)
       at android.view.View.getDisplayList(View.java:13604)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4477)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.draw(View.java:14791)
       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3869)
       at android.view.View.getDisplayList(View.java:13655)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.draw(View.java:14791)
       at android.support.v4.view.ViewPager.draw(ViewPager.java:2443)
       at android.view.View.getDisplayList(View.java:13655)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.draw(View.java:14791)
       at android.view.View.getDisplayList(View.java:13655)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.draw(View.java:14791)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13655)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.draw(View.java:14791)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.support.v4.widget.NestedScrollView.draw(NestedScrollView.java:1768)
       at android.view.View.getDisplayList(View.java:13655)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2978)
       at android.view.View.draw(View.java:14791)
       at android.view.View.getDisplayList(View.java:13655)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.draw(View.java:14791)
       at android.support.v4.view.ViewPager.draw(ViewPager.java:2443)
       at android.view.View.getDisplayList(View.java:13655)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.draw(View.java:14791)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13655)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.getDisplayList(View.java:13650)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.View.draw(View.java:14505)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3134)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2971)
       at android.view.View.draw(View.java:14791)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2329)
       at android.view.View.getDisplayList(View.java:13655)
       at android.view.View.getDisplayList(View.java:13697)
       at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2483)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2307)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1936)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1049)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5899)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:771)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:757)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5268)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by JakeWharton** [comment]
It's unclear why you think Picasso is at fault here, so I have no idea. Try the latest stable version or the latest SNAPSHOT version and provide example code or a minimal sample app that reproduces the behavior and we'll look.
