### ISSUE TITLE
 Target must not be null.

### ISSUE THREAD

**Issue by Mahdihp** [square/picasso#1649]
` Process: com.mahdi.ketabcell, PID: 14175
                                                                     java.lang.IllegalArgumentException: Target must not be null.
                                                                         at com.squareup.picasso.RequestCreator.into(RequestCreator.java:618)
                                                                         at com.squareup.picasso.RequestCreator.into(RequestCreator.java:601)`

My Code : 
` Picasso.with(AppLoader.appContext)
                .load(Utils.createAvatarLink(searchTransferData.getImageUrl()))
                .placeholder(R.drawable.ic_sand_clock)
                .error(R.drawable.ic_sand_clock)
                .into(img_BookImage);`

**Comment by JakeWharton** [comment]
`img_BookImage` is `null` and is not allowed to be.

**Comment by MontsserratCisne** [comment]
But why is working on different devices and others don't

**Comment by Ramaraju1992** [comment]
`Picasso.get().load(this.document.getDocumentURL()).into((ImageView) findViewById(R.id.iv_doc_preview));`

The above request also giving me the below error.

**W/System.err: java.lang.IllegalArgumentException: Target must not be null.**

**Comment by Mamoon123d** [comment]
java.lang.IllegalArgumentException: Target must not be null.
        at com.squareup.picasso.RequestCreator.into(RequestCreator.java:682)
        at com.squareup.picasso.RequestCreator.into(RequestCreator.java:665)
