### ISSUE TITLE
Fix existing lint warnings

### ISSUE THREAD

**Issue by jaredsburrows** [square/picasso#1662]
See https://travis-ci.org/square/picasso#L1597.

```
/home/travis/build/square/picasso/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java:36: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.ORIENTATION_FLIP_HORIZONTAL;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/square/picasso/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java:37: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.ORIENTATION_FLIP_VERTICAL;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/square/picasso/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java:38: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.ORIENTATION_ROTATE_180;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/square/picasso/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java:39: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.ORIENTATION_ROTATE_270;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/square/picasso/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java:40: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.ORIENTATION_ROTATE_90;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/square/picasso/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java:41: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.ORIENTATION_TRANSPOSE;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/square/picasso/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java:42: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.ORIENTATION_TRANSVERSE;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/square/picasso/picasso/src/main/java/com/squareup/picasso/FileRequestHandler.java:19: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import android.media.ExifInterface;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/square/picasso/picasso/src/main/java/com/squareup/picasso/FileRequestHandler.java:26: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.ORIENTATION_NORMAL;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/square/picasso/picasso/src/main/java/com/squareup/picasso/FileRequestHandler.java:27: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.TAG_ORIENTATION;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Explanation for issues of type "ExifInterface":
   The android.media.ExifInterface implementation has some known security bugs
   in older versions of Android. There is a new implementation available of
   this library in the support library, which is preferable.
/home/travis/build/square/picasso/picasso/src/main/java/com/squareup/picasso/Picasso.java:147: Warning: Do not place Android context classes in static fields (static reference to Picasso which has field context pointing to Context); this is a memory leak (and also breaks Instant Run) [StaticFieldLeak]
  static volatile Picasso singleton = null;
  ~~~~~~
/home/travis/build/square/picasso/picasso/src/main/java/com/squareup/picasso/PicassoProvider.java:32: Warning: Do not place Android context classes in static fields; this is a memory leak (and also breaks Instant Run) [StaticFieldLeak]
  static Context context;
  ~~~~~~
   Explanation for issues of type "StaticFieldLeak":
   A static field will leak contexts.
   Non-static inner classes have an implicit reference to their outer class.
   If that outer class is for example a Fragment or Activity, then this
   reference means that the long-running handler/loader/task will hold a
   reference to the activity which prevents it from getting garbage
   collected.
   Similarly, direct field references to activities and fragments from these
   longer running instances can cause leaks.
   ViewModel classes should never point to Views or non-application Contexts.
0 errors, 12 warnings
Wrote HTML report to file:///home/travis/build/square/picasso/picasso/build/reports/lint-results.html
Wrote XML report to file:///home/travis/build/square/picasso/picasso/build/reports/lint-results.xml
:picasso:javaPreCompileDebugUnitTest
:picasso:compileDebugUnitTestJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:picasso:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
:picasso:testDebugUnitTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':picasso:testDebugUnitTest'.
> Process 'Gradle Test Executor 1' finished with non-zero exit value 137
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 3m 27s
72 actionable tasks: 69 executed, 3 up-to-date
Exception in thread "Thread-73" java.lang.NoClassDefFoundError: com/android/builder/internal/aapt/v2/AaptV2Jni$TempDirCache$RecursiveDelete
	at com.android.builder.internal.aapt.v2.AaptV2Jni$TempDirCache.lambda$getCachedDirectory$0(AaptV2Jni.java:252)
	at com.android.builder.internal.aapt.v2.AaptV2Jni$TempDirCache$$Lambda$306/1045447850.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.android.builder.internal.aapt.v2.AaptV2Jni$TempDirCache$RecursiveDelete
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
The command "./gradlew clean check" exited with 1.
cache.2
store build cache
0.00s
24.58schanges detected, packing new archive
.
.
.
uploading archive
Done. Your build exited with 1.
```

**Comment by JakeWharton** [comment]
It's not lint related. The test task failed because it couldn't delete a directory.

**Comment by jaredsburrows** [comment]
@JakeWharton Yes, I read that incorrectly ha.

**Comment by jaredsburrows** [comment]
@JakeWharton Wait, I take that back, that is the wrong exception I posted. I tried to build this locally and it does not work:

```
$ gradlew clean check
Parallel execution with configuration on demand is an incubating feature.
Build cache is an incubating feature.

> Task :picasso:lint
Ran lint on variant debug: 14 issues found
Ran lint on variant release: 14 issues found
/<>/picasso/picasso/src/main/java/com/squareup/picasso/Dispatcher.java:331: Error: Missing permissions required by ConnectivityManager.getActiveNetworkInfo: android.permission.ACCESS_NETWORK_STATE [MissingPermission]
      networkInfo = connectivityManager.getActiveNetworkInfo();
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/<>/picasso/picasso/src/main/java/com/squareup/picasso/Dispatcher.java:567: Error: Missing permissions required by ConnectivityManager.getActiveNetworkInfo: android.permission.ACCESS_NETWORK_STATE [MissingPermission]
        dispatcher.dispatchNetworkStateChange(connectivityManager.getActiveNetworkInfo());
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "MissingPermission":
   This check scans through your code and libraries and looks at the APIs
   being used, and checks this against the set of permissions required to
   access those APIs. If the code using those APIs is called at runtime, then
   the program will crash.

   Furthermore, for permissions that are revocable (with targetSdkVersion 23),
   client code must also be prepared to handle the calls throwing an exception
   if the user rejects the request for permission at runtime.

/<>/picasso/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java:36: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.ORIENTATION_FLIP_HORIZONTAL;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/<>/picasso/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java:37: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.ORIENTATION_FLIP_VERTICAL;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/<>/picasso/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java:38: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.ORIENTATION_ROTATE_180;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/<>/picasso/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java:39: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.ORIENTATION_ROTATE_270;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/<>/picasso/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java:40: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.ORIENTATION_ROTATE_90;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/<>/picasso/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java:41: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.ORIENTATION_TRANSPOSE;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/<>/picasso/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java:42: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.ORIENTATION_TRANSVERSE;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/<>/picasso/picasso/src/main/java/com/squareup/picasso/FileRequestHandler.java:19: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import android.media.ExifInterface;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
/<>/picasso/picasso/src/main/java/com/squareup/picasso/FileRequestHandler.java:26: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.ORIENTATION_NORMAL;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/<>/picasso/picasso/src/main/java/com/squareup/picasso/FileRequestHandler.java:27: Warning: Avoid using android.media.ExifInterface; use android.support.media.ExifInterface from the support library instead [ExifInterface]
import static android.media.ExifInterface.TAG_ORIENTATION;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "ExifInterface":
   The android.media.ExifInterface implementation has some known security bugs
   in older versions of Android. There is a new implementation available of
   this library in the support library, which is preferable.

/<>/picasso/picasso/src/main/java/com/squareup/picasso/Picasso.java:147: Warning: Do not place Android context classes in static fields (static reference to Picasso which has field context pointing to Context); this is a memory leak (and also breaks Instant Run) [StaticFieldLeak]
  static volatile Picasso singleton = null;
  ~~~~~~
/<>/picasso/picasso/src/main/java/com/squareup/picasso/PicassoProvider.java:32: Warning: Do not place Android context classes in static fields; this is a memory leak (and also breaks Instant Run) [StaticFieldLeak]
  static Context context;
  ~~~~~~

   Explanation for issues of type "StaticFieldLeak":
   A static field will leak contexts.

   Non-static inner classes have an implicit reference to their outer class.
   If that outer class is for example a Fragment or Activity, then this
   reference means that the long-running handler/loader/task will hold a
   reference to the activity which prevents it from getting garbage
   collected.

   Similarly, direct field references to activities and fragments from these
   longer running instances can cause leaks.

   ViewModel classes should never point to Views or non-application Contexts.

2 errors, 12 warnings
Wrote HTML report to file:///<>/picasso/picasso/build/reports/lint-results.html
Wrote XML report to file:///<>/picasso/picasso/build/reports/lint-results.xml


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':picasso:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
57 actionable tasks: 4 executed, 51 from cache, 2 up-to-date
```

**Comment by JakeWharton** [comment]
Those can be suppressed. Feel free to send a PR.

**Comment by jaredsburrows** [comment]
@JakeWharton Should we look into solving the other lint issues as well?
