### ISSUE TITLE
Picasso fails to load one particular image.

### ISSUE THREAD

**Issue by samramez** [square/picasso#1684]
Our company uses Picasso for loading images in various places in our app and just recently we realized it fails to load one particular image with the following URL: http://site.skychnl.net/thumbs/3572465.box_art.jpg

The following code loads the image:
```java    
final String url = video.getBoxArtUrl();
if(!url.isEmpty()) {
      Picasso.with(holder.image.getContext())
             .load(url)
             .fit()
             .centerCrop()
             .into(holder.image);
}
```
based on my tests and logs, `url` variable is never empty. This code loads every other image exist in the app but that one particular image which I posted the link above. None of the other platforms (iOS, Web and etc) has this issue so I can only imagine it can be a problem with the Picasso.
I'll appreciate any feedback.

**Comment by JakeWharton** [comment]
If you add an error handler does it receive an exception for this image?

**Comment by samramez** [comment]
I just added an error handler and it receives the following error:
```
java.io.IOException: Cannot reset
   at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
   at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
   at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
   at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
   at java.lang.Thread.run(Thread.java:764)
   at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```

**Comment by JakeWharton** [comment]
This is #364 and it's already been fixed on `master`. If you want to try out the 3.0.0-SNAPSHOT version for the fix that'd be great. There's no currently no release date for it, but it's stable enough to use.

**Comment by samramez** [comment]
Thank you Jake for very quick response.
