### ISSUE TITLE
 java.lang.OutOfMemoryError when loading lots of images in RecylerView while scrolling

### ISSUE THREAD

**Issue by chwakil** [square/picasso#1685]
I am getting this app crash when loading lots of images in RecyclerView with Picasso. I do not know why memory is going to increase on scrolling on Android Studio Device monitor. The log cat is below:

Process: [APP-PACKAGE], PID: 9817
                                                                   java.lang.OutOfMemoryError: Failed to allocate a 1136368 byte allocation with 294524 free bytes and 287KB until OOM
                                                                       at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                       at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                                       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:651)
                                                                       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:486)
                                                                       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:993)
                                                                       at android.content.res.Resources.loadDrawableForCookie(Resources.java:2723)
                                                                       at android.content.res.Resources.loadDrawable(Resources.java:2614)
                                                                       at android.content.res.Resources.getDrawable(Resources.java:900)
                                                                       at android.content.Context.getDrawable(Context.java:408)
                                                                       at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:30)
                                                                       at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:372)
                                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202)
                                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
                                                                       at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
                                                                       at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:73)
                                                                       at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:81)
                                                                       at com.squareup.picasso.ImageViewAction.error(ImageViewAction.java:66)
                                                                       at com.squareup.picasso.Picasso.deliverAction(Picasso.java:581)
                                                                       at com.squareup.picasso.Picasso.complete(Picasso.java:528)
                                                                       at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:117)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                       at android.os.Looper.loop(Looper.java:194)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5637)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

Please help.

**Comment by JakeWharton** [comment]
This is not a Picasso problem. You asked it to load a URL with an 11MB error drawable fallback and it attempted to load that error drawable when the URL failed. Use a smaller error drawable to reduce its memory consumption.

**Comment by chwakil** [comment]
Okay, I will try. Thank you.
