### ISSUE TITLE
Can't resize image on Android N

### ISSUE THREAD

**Issue by Pankaj-Hss** [square/picasso#1694]
Hello Everyone,
I am trying to resize an image so that I don't get Out of memory issue. I am using below code:
```
Picasso.with(context)
.load(new File("/storage/emulated/0/DCIM/Camera/IMG_20171025_162343.jpg"))
.resize(100,100)
.placeholder(R.mipmap.ic_launcher)
.into(imgView);
```
When I run above code in Android N it not working but it working fine in Android M.
If comment the resize method or remove it. My image showing perfectly on Android N but I want to resize it for Memory purpose.
Below is the Stack Trace:
```
10-26 14:13:24.712 25508-25508 D/Picasso: Main        created      [R0] Request{file:///storage/emulated/0/DCIM/Camera/IMG_20171025_162343.jpg resize(100,100)}
10-26 14:13:24.725 25508-25508 I/Choreographer: Skipped 842 frames!  The application may be doing too much work on its main thread.
10-26 14:13:24.738 25508-25578 D/OpenGLRenderer: ProgramCache.generateProgram: 103084458052
10-26 14:13:24.791 25508-25850 D/Picasso: Hunter      executing    [R0]+61ms 
10-26 14:13:24.890 25508-25850 I/ExifInterface_JNI: Raw image not detected
10-26 14:13:24.920 25508-25850 W/ExifInterface: Skip the tag entry since tag number is not defined: 546
10-26 14:13:24.921 25508-25772 D/Picasso: Dispatcher  enqueued     [R0]+51ms 
10-26 14:13:24.935 25508-25850 W/ExifInterface: Skip the tag entry since tag number is not defined: 544
10-26 14:13:24.936 25508-25850 W/ExifInterface: Skip the tag entry since tag number is not defined: 547
10-26 14:13:24.937 25508-25850 W/ExifInterface: Skip the tag entry since tag number is not defined: 545
10-26 14:13:24.942 25508-25850 W/ExifInterface: Skip the tag entry since tag number is not defined: 548
10-26 14:13:24.945 25508-25850 W/ExifInterface: Skip the tag entry since tag number is not defined: 549
10-26 14:13:24.999 25508-25850 W/ExifInterface: Skip the tag entry since tag number is not defined: 2
10-26 14:13:25.575 25508-25772 D/Picasso: Dispatcher  batched      [R0]+866ms for error
10-26 14:13:25.781 25508-25772 D/Picasso: Dispatcher  delivered    [R0]+1073ms 
10-26 14:13:25.781 25508-25508 D/Picasso: Main        errored      [R0]+1073ms 
```

Kindly Please help me out.

**Comment by pradhulstha** [comment]
Hey there,
I think you should use .fit(fitxy) along with resize so it knows whether to crop and resize or just downsize the image.

**Comment by JakeWharton** [comment]
Please attach an error listener to the Picasso instance so that the real exception can be captured and post it.

**Comment by iagomontenegrob** [comment]
I was going through the same problem,
Adding the Listener structure the problem is gone:

---
Picasso.Builder builder = new Picasso.Builder(context);
            builder.listener(new Picasso.Listener()
            {
                @Override
                public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception)
                {
                    exception.printStackTrace();
                }

            });
            builder.build()
                    .load(new File("PATH"))
                    .resize(0, 100)
                    .into(imgView, new Callback() {
                        @Override
                        public void onSuccess() {

                            System.out.println("SUCCESS");
                        }

                        @Override
                        public void onError() {
                            System.out.println("ERROR");
                        }
                    });
---

**Comment by iagomontenegrob** [comment]
I was going through the same problem,
Adding the Listener structure the problem is gone:

`Picasso.Builder builder = new Picasso.Builder(context);
            builder.listener(new Picasso.Listener()
            {
                @Override
                public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception)
                {
                    exception.printStackTrace();
                }

            });
            builder.build()
                    .load(new File("PATH"))
                    .resize(0, 100)
                    .into(imgView, new Callback() {
                        @Override
                        public void onSuccess() {

                            System.out.println("SUCCESS");
                        }

                        @Override
                        public void onError() {

                        }
                    });`

**Comment by iagomontenegrob** [comment]
I was going through the same problem,
adding the Listener structure the problem is gone.

**Comment by iagomontenegrob** [comment]
With the Listener attachment:

06-22 16:07:28.380 4941-4941/br.com.gestorescolar W/System.err: java.io.IOException: Cannot reset
06-22 16:07:28.381 4941-4941/br.com.gestorescolar W/System.err:     at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
06-22 16:07:28.381 4941-4941/br.com.gestorescolar W/System.err:     at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
06-22 16:07:28.381 4941-4941/br.com.gestorescolar W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
06-22 16:07:28.381 4941-4941/br.com.gestorescolar W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
06-22 16:07:28.381 4941-4941/br.com.gestorescolar W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
06-22 16:07:28.381 4941-4941/br.com.gestorescolar W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-22 16:07:28.381 4941-4941/br.com.gestorescolar W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-22 16:07:28.381 4941-4941/br.com.gestorescolar W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-22 16:07:28.381 4941-4941/br.com.gestorescolar W/System.err:     at java.lang.Thread.run(Thread.java:761)
06-22 16:07:28.381 4941-4941/br.com.gestorescolar W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

**Comment by iagomontenegrob** [comment]
With the Listener attachment:

W/System.err: java.io.IOException: Cannot reset
06-22 16:15:48.392 W/System.err:     at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
06-22 16:15:48.392 W/System.err:     at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
06-22 16:15:48.393 W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
06-22 16:15:48.393 W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
06-22 16:15:48.393 W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
06-22 16:15:48.393 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-22 16:15:48.393 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-22 16:15:48.393 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-22 16:15:48.393 W/System.err:     at java.lang.Thread.run(Thread.java:761)
06-22 16:15:48.393 W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
