### ISSUE TITLE
Failed to load big images from server (using v2.5.2)

### ISSUE THREAD

**Issue by krithghosh** [square/picasso#1709]
I'm trying to load an image from server on android version lollipop. The image dimension is : 3456 × 4608 pixels and I'm trying to resize it into 240 px circular image view. Its throwing an error :
```
java.lang.RuntimeException: at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:180)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 63701004 byte allocation with 4194304 free bytes and 54MB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:142)
at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
```

Here is my snippet :
```
ViewGroup.LayoutParams layoutParams = view.getLayoutParams();
Picasso picasso = new Picasso.Builder(mContext).listener(
                        (picasso1, uri, exception) -> {
                            Log.e(TAG, "setImage: ", exception);
                        }).build();
picasso.load(imageUrl)
        .placeholder(placeHolder)
        .resize(layoutParams.width, layoutParams.height)
        .into(view);
```
Even on using the resize function, its throwing an error. From the stack trace, I can understand that the image size is too large to load it into the memory. Any solution or suggestion ?

**Comment by JakeWharton** [comment]
No real suggestions beyond the obvious ones. If you're using `resize` or `fit` and the desired image size is less than half of the original it will be scaled down during decoding which saves on memory. But beyond that, there's really no magic here other than using less memory and ensuring you don't have memory leaks (with tools like LeakCanary).
