### ISSUE TITLE
OutOfMemoryError when loading images into ViewPager

### ISSUE THREAD

**Issue by Bersh** [square/picasso#173]
I use `Picasso` to load images from app resources into `ViewPager`. Today I've faced the crash when I scroll `ViewPager` pages very fast. I recieved folowing error log: 

```
08-13 13:10:33.968: ERROR/dalvikvm-heap(7896): Out of memory on a 1405456-byte allocation.
08-13 13:10:34.818: ERROR/dalvikvm(7896): can't open /data/misc/hprof_oom_dump.hprof: Permission denied
08-13 13:10:34.928: ERROR/Bitmap(7896): [FXN.ASD] Unable to create bitmap file. OutOfMemoryError.
        java.lang.OutOfMemoryError
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:645)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:587)
        at com.squareup.picasso.Picasso.transformResult(Picasso.java:479)
        at com.squareup.picasso.Picasso.loadFromType(Picasso.java:401)
        at com.squareup.picasso.Picasso.resolveRequest(Picasso.java:240)
        at com.squareup.picasso.Picasso.run(Picasso.java:218)
        at com.squareup.picasso.Request.run(Request.java:100)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:137)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:856)
        at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:267)
08-13 13:10:34.998: ERROR/AndroidRuntime(7896): FATAL EXCEPTION: main
        java.lang.RuntimeException: An unexpected exception occurred
        at com.squareup.picasso.Request$1.run(Request.java:106)
        at android.os.Handler.handleCallback(Handler.java:615)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4802)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:813)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:580)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: java.lang.NullPointerException
        at android.graphics.Bitmap.createBitmap(Bitmap.java:602)
        at com.squareup.picasso.Picasso.transformResult(Picasso.java:479)
        at com.squareup.picasso.Picasso.loadFromType(Picasso.java:401)
        at com.squareup.picasso.Picasso.resolveRequest(Picasso.java:240)
        at com.squareup.picasso.Picasso.run(Picasso.java:218)
        at com.squareup.picasso.Request.run(Request.java:100)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:137)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:856)
        at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:267)
08-13 13:10:35.228: ERROR/dalvikvm-heap(7896): Out of memory on a 3686416-byte allocation.
08-13 13:10:35.718: ERROR/wpa_supplicant(3206): ctrl_iface cmd = SIGNAL_POLL
08-13 13:10:36.188: ERROR/dalvikvm(7896): can't open /data/misc/hprof_oom_dump.hprof: Permission denied
08-13 13:10:36.298: ERROR/dalvikvm-heap(7896): Out of memory on a 3686416-byte allocation.
08-13 13:10:37.348: ERROR/dalvikvm-heap(7896): Out of memory on a 3686416-byte allocation.
08-13 13:10:38.278: ERROR/dalvikvm-heap(7896): Out of memory on a 3686416-byte allocation.
```

Here is code from my `PagerAdapter` where I load images:

``` java
@Override
    public View instantiateItem(ViewGroup container, int position) {
        View pagerItem = layoutInflater.inflate(R.layout.pager_item_wallpaper, container, false);
        ImageView imgWallpaper = (ImageView) pagerItem.findViewById(R.id.wallpaper);
        Picasso.with(context).load(wallpapers.get(position)).fit().into(imgWallpaper);
        container.addView(pagerItem);
        return pagerItem;
    }
```

I use `Picasso` version 1.1.1. 
Is something wrong with my code?

**Comment by liuhuibin** [comment]
@Bersh how did you solve it?

**Comment by Bersh** [comment]
@liuhuibin sorry too much time passed since that. But as i remember i finished with server-resized images. I mean that i server provided me with images with smaller size.

**Comment by liuhuibin** [comment]
@Bersh Thank you all the same. :smile:

**Comment by neywen** [comment]
I have also seen this problem with Android 4.4.2 (no problem with Android 6).
I've managed to avoid the problem, using the resize method.
<=>
`myPicassoInstance.load(imageUrl).resize(smallerWidth, smallerHeight).into(imageView, null);
`

**Comment by TasneemBohra** [comment]
I am also facing this issue, though image size is not very big. Did you able to resolve this. I can not fix the width and height.

**Comment by Pukhrajwdg** [comment]
> I use `Picasso` to load images from app resources into `ViewPager`. Today I've faced the crash when I scroll `ViewPager` pages very fast. I recieved folowing error log:
> 
> ```
> 08-13 13:10:33.968: ERROR/dalvikvm-heap(7896): Out of memory on a 1405456-byte allocation.
> 08-13 13:10:34.818: ERROR/dalvikvm(7896): can't open /data/misc/hprof_oom_dump.hprof: Permission denied
> 08-13 13:10:34.928: ERROR/Bitmap(7896): [FXN.ASD] Unable to create bitmap file. OutOfMemoryError.
>         java.lang.OutOfMemoryError
>         at android.graphics.Bitmap.nativeCreate(Native Method)
>         at android.graphics.Bitmap.createBitmap(Bitmap.java:645)
>         at android.graphics.Bitmap.createBitmap(Bitmap.java:587)
>         at com.squareup.picasso.Picasso.transformResult(Picasso.java:479)
>         at com.squareup.picasso.Picasso.loadFromType(Picasso.java:401)
>         at com.squareup.picasso.Picasso.resolveRequest(Picasso.java:240)
>         at com.squareup.picasso.Picasso.run(Picasso.java:218)
>         at com.squareup.picasso.Request.run(Request.java:100)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
>         at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:137)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
>         at java.lang.Thread.run(Thread.java:856)
>         at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:267)
> 08-13 13:10:34.998: ERROR/AndroidRuntime(7896): FATAL EXCEPTION: main
>         java.lang.RuntimeException: An unexpected exception occurred
>         at com.squareup.picasso.Request$1.run(Request.java:106)
>         at android.os.Handler.handleCallback(Handler.java:615)
>         at android.os.Handler.dispatchMessage(Handler.java:92)
>         at android.os.Looper.loop(Looper.java:137)
>         at android.app.ActivityThread.main(ActivityThread.java:4802)
>         at java.lang.reflect.Method.invokeNative(Native Method)
>         at java.lang.reflect.Method.invoke(Method.java:511)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:813)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:580)
>         at dalvik.system.NativeStart.main(Native Method)
>         Caused by: java.lang.NullPointerException
>         at android.graphics.Bitmap.createBitmap(Bitmap.java:602)
>         at com.squareup.picasso.Picasso.transformResult(Picasso.java:479)
>         at com.squareup.picasso.Picasso.loadFromType(Picasso.java:401)
>         at com.squareup.picasso.Picasso.resolveRequest(Picasso.java:240)
>         at com.squareup.picasso.Picasso.run(Picasso.java:218)
>         at com.squareup.picasso.Request.run(Request.java:100)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
>         at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:137)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
>         at java.lang.Thread.run(Thread.java:856)
>         at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:267)
> 08-13 13:10:35.228: ERROR/dalvikvm-heap(7896): Out of memory on a 3686416-byte allocation.
> 08-13 13:10:35.718: ERROR/wpa_supplicant(3206): ctrl_iface cmd = SIGNAL_POLL
> 08-13 13:10:36.188: ERROR/dalvikvm(7896): can't open /data/misc/hprof_oom_dump.hprof: Permission denied
> 08-13 13:10:36.298: ERROR/dalvikvm-heap(7896): Out of memory on a 3686416-byte allocation.
> 08-13 13:10:37.348: ERROR/dalvikvm-heap(7896): Out of memory on a 3686416-byte allocation.
> 08-13 13:10:38.278: ERROR/dalvikvm-heap(7896): Out of memory on a 3686416-byte allocation.
> ```
> 
> Here is code from my `PagerAdapter` where I load images:
> 
> ```java
> @Override
>     public View instantiateItem(ViewGroup container, int position) {
>         View pagerItem = layoutInflater.inflate(R.layout.pager_item_wallpaper, container, false);
>         ImageView imgWallpaper = (ImageView) pagerItem.findViewById(R.id.wallpaper);
>         Picasso.with(context).load(wallpapers.get(position)).fit().into(imgWallpaper);
>         container.addView(pagerItem);
>         return pagerItem;
>     }
> ```
> 
> I use `Picasso` version 1.1.1.
> Is something wrong with my code?


java.lang.RuntimeException: excessive total memory usage, total usage 1605 MB
	at com.vivo.vspa.AppThreadCmd$2.run(AppThreadCmd.java:84)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:239)
	at android.app.ActivityThread.main(ActivityThread.java:8149)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)  help me out
