### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by yinjinyj** [square/picasso#1785]
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Out of memory
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:1078)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1328)
	at com.squareup.picasso.PicassoExecutorService.submit(PicassoExecutorService.java:88)
	at com.squareup.picasso.Dispatcher.performSubmit(Dispatcher.java:202)
	at com.squareup.picasso.Dispatcher.performSubmit(Dispatcher.java:175)
	at com.squareup.picasso.Dispatcher$DispatcherHandler.handleMessage(Dispatcher.java:482)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by JakeWharton** [comment]
You are probably creating a new instance of Picasso every time you use it. Create one instance and re-use it instead.

**Comment by yinjinyj** [comment]
thanks

**Comment by yinjinyj** [comment]
public static Picasso with(Context context) {
    if (singleton == null) {
      synchronized (Picasso.class) {
        if (singleton == null) {
          singleton = new Builder(context).build();
        }
      }
    }
    return singleton;
  }

this is not singleton？
I use it by Picasso.with(context)
