### ISSUE TITLE
Loading images from camera stops working after calling Picasso

### ISSUE THREAD

**Issue by agentraymond232** [square/picasso#1892]
Picasso version   "2.5.2" and "2.71828" (issue found with both)

Android Studio version "3.1.1"

I am using one of the two methods to create a new URI  to pass to Android Camera intent so that Android camera can write to it. I store the URI in `outputFileUri`

Method 1.

	final String imageFileName = "JPEG_"
				+ new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date()) + ".jpeg" ;

        Uri outputFileUri = Uri.fromFile(new File(getFilesDir(), imageFileName + ".jpeg"));
        File imagePath = new File(getFilesDir(), "images");

        if(!imagePath.isDirectory()){
            imagePath.mkdirs();

        }

        File newFile = new File(imagePath, imageFileName);

        if (newFile.exists()) {
            newFile.delete();
        }
        try {
            if(!newFile.createNewFile())
                Log.e(MyActivity.class.getSimpleName(),  "Error creating file");
         } catch (IOException e) {
            e.printStackTrace();
        }
        outputFileUri = FileProvider.getUriForFile(
                this.getApplicationContext(), "com.my.android.fileprovider", newFile);

or Method 2.

        ContentValues values = new ContentValues();
        values.put(MediaStore.Images.Media.TITLE, "New Picture");
        values.put(MediaStore.Images.Media.DESCRIPTION,"From your Camera");
        Uri outputFileUri = MyApplication.INSTANCE.getContentResolver().insert(
                MediaStore.Images.Media.EXTERNAL_CONTENT_URI, values);

Further, on getting the callback `onActivityResult`,  I use this method to extract the bitmap from the image written to the file gotten above and store it in `ImageView mFetchedSnap`:

                Bitmap snap = MediaStore.Images.Media.getBitmap(
                        getContentResolver(),
                        snapUri);
                if(null == snap )
                    snap = BitmapFactory.decodeStream(
                            getContentResolver().openInputStream(snapUri));
               
                if (null == snap) {
                    Log.e(MyActivity.class.getSimpleName(), "Problem with decoding");
                    return;
                }

               BitmapDrawable drawable = (BitmapDrawable) mFetchedSnap.getDrawable();
               if(null != drawable && null != drawable.getBitmap() && !drawable.getBitmap().isRecycled())
                    drawable.getBitmap().recycle();
               mFetchedSnap.setImageBitmap(result);
            
I am also loading an image fetched from the web **into the same** `ImageView mFetchedSnap` in a different use case through this code.

        final String url = "https://i.imgur.com/xyz.jpg";
        Picasso.with(this.getApplicationContext()).load(url)
                .into(mFetchedSnap, new Callback() {
                    @Override
                    public void onSuccess() {
						Snackbar.make(getRootLayout(), "Success", Snackbar.LENGTH_SHORT);	
					}

                    @Override
                    public void onError() {
                        Snackbar.make(getRootLayout(), "Failure", Snackbar.LENGTH_SHORT);
                    }
                });

The issue is, **once I use Picasso to load the image into the ImageView, I am no longer able to load the image captured by the camera into it.** 

If I use Method 1 of creating a `outputUri`  for the camera to store the image into (shown above), both `MediaStore.Images.Media.getBitmap( getContentResolver(), snapUri);`  and `BitmapFactory.decodeStream( getContentResolver().openInputStream(snapUri));` return a `null` Bitmap with the Debug Log `SkImageDecoder::Factory returned null` . 

However, if I use Method 2 of  creating the `outputUri`,  `MediaStore.Images.Media.getBitmap( getContentResolver(), snapUri);` throws the following stacktrace:

`04-23 02:01:25.846 17290-17456/com.my.android.app W/System.err: java.io.FileNotFoundException: No such file or directory
04-23 02:01:25.861 17290-17456/com.my.android.app W/System.err:     at
android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
04-23 02:01:25.862 17290-17456/com.my.android.app W/System.err:     at
android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1080)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:921)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:646)
        at android.provider.MediaStore$Images$Media.getBitmap(MediaStore.java:865)`

What is surprising is till the time I don't run the flow of Picasso loading an image from the web into the image view, the flow of capturing image from the camera and loading it into the image view works flawlessly with either of the above methods. However, once I use that Picasso call, the aforementioned problems arise.

Can you help me with this? Is Picasso somehow messing up the FileInputStream used to decode the Bitmap images from the given URI ?

Edit: After using Picasso to load an image from the web into Image View, I tried to use Picasso itself for loading the image stored at the Uri into the Image View. Specifically, I replaced `MediaStore.Images.Media.getBitmap( getContentResolver(), snapUri);` with

        Picasso.get().load(snapUri).into( mFetchedSnap, new Callback() {
                    @Override
                    public void onSuccess() {
                        Log.e(MyActivity.class.getSimpleName(), "Picasso image loaded ");

                    }

                    @Override
                    public void onError(Exception e) {
                        Log.e(MyActivity.class.getSimpleName(), "Picasso image failed " + e.getMessage());
                        e.printStackTrace();
                    }
                });

Even for this, I got the `FileNotFound` exception from `Picasso`, and the top part of the stacktrace is identical to the one that I got with `MediaStore.getBitmap` or `BitmapFactory.decode` methods:

`04-23 03:29:10.114 4175-4175/com.my.android.app W/System.err: java.io.FileNotFoundException: No such file or directory
04-23 03:29:10.125 4175-4175/com.my.android.app W/System.err:     at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1080)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:921)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:646)
        at com.squareup.picasso.ContentStreamRequestHandler.getInputStream(ContentStreamRequestHandler.java:47)
        at com.squareup.picasso.MediaStoreRequestHandler.load(MediaStoreRequestHandler.java:95)
04-23 03:29:10.126 4175-4175/com.my.android.app W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
        at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
        at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)`

**Comment by agentraymond232** [comment]
Closing as issue found somewhere else.
