### ISSUE TITLE
java.lang.AbstractMethodError: com.squareup.picasso.Callback.onError

### ISSUE THREAD

**Issue by damaisubimawanto** [square/picasso#1928]
Hi, we are getting constant crashes of java.lang.AbstractMethodError after updated it to version 2.71828 in our application.

Here is the crash report:
> Fatal Exception: java.lang.AbstractMethodError: abstract method "void com.squareup.picasso.Callback.onError(java.lang.Exception)"
    at com.squareup.picasso.FetchAction.error(FetchAction.java:40)
       at com.squareup.picasso.Picasso.deliverAction(Picasso.java:581)
       at com.squareup.picasso.Picasso.complete(Picasso.java:528)
       at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:122)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5811)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)

My code implementation:
```
Picasso.get().cancelRequest(imageView);
Picasso.get().load(url)
    .error(R.drawable.img_default_transparent)
    .placeholder(R.drawable.img_default_transparent)
    .into(imageView);
```

Actually, it never happened in my device (I'm currently using Asus Zenfone 2 and Samsung Galaxy Note 2) while I was testing my application, but I looked in Fabric Crashlytics, the crashes happened in other devices.
Any idea why this crash occurred?

**Picasso Version**:
2.71828

**Crashes in device**:
Samsung, Xiaomi, OPPO, Vivo, QUALCOMM, HUAWEI, Sony, and many others. 

**Android versions**:
Android 5, 6, 7, and 8.

**Comment by ZeeshanArid** [comment]
yes also crash on my samsung c9 pro device. why this crash occurred?

**Comment by mahesh-gupta-23** [comment]
Also crashes on my app in production with exact same error and same version, same devices and android version. Not able to understand why this is happening. The implementation is quite straight forward. `Picasso.get().load(url).into(imageView);`

**Comment by BhupeshSahu** [comment]
Hi, we too are getting the same issue on Moto E2

**Comment by ayz4sci** [comment]
Is there any solution to this problem?

**Comment by Radwa13** [comment]
Hi, there have you find any solution  ?

**Comment by ahmadazarnia** [comment]
Hi, we too are getting the same issue on Asus Tablet. there have you find any solution ?

**Comment by Vengat121** [comment]
hi, any solution?

**Comment by Ic-ks** [comment]
We observed this crash bug caused by the usage of firebase in app messaging which has a dependency to picasso 2.71828: 
![image](https://user-images.githubusercontent.com/29521057/78553137-145e8900-7809-11ea-8fe8-4b858b87b37c.png)
Is this bug confirmed and is there already a bugfix in development (the last release was 2 years ago)?

**Comment by supergenedy** [comment]
It's solved for me by clearing app cache and reinstall the app
