### ISSUE TITLE
3.0.0 and 2.71828 is loading image in Google Pixel Android 8.1.0

### ISSUE THREAD

**Issue by Qamar4P** [square/picasso#1930]
Try this [https://github.com/Qamar4P/PicassoTestApp.git](https://github.com/Qamar4P/PicassoTestApp.git)
Usage
v3.0.0
```
picasso = new Picasso.Builder(getApplicationContext())
                .loggingEnabled(true).listener((picasso1, uri, exception) -> {
                    Log.wtf("Picasso","Url: "+uri,exception);
                }).indicatorsEnabled(true)
                .build();

picasso.load("https://d19dnii6y7cwuc.cloudfront.net/uploads/media/3342/original/5b1a2bc8c3863.png")
                .into(imageView);
```
v2.71828
```
Picasso.get()
                        .load(photo)
                        .placeholder(R.drawable.ic_img_profile)
                        .into(expandedImageView);
```

```
06-15 05:48:47.258 25550-25550/com.github.qamar4p.testapp D/Picasso: Main        created      [R0] Request{https://d19dnii6y7cwuc.cloudfront.net/uploads/media/3342/original/5b1a2bc8c3863.png}
06-15 05:48:47.263 25550-25580/com.github.qamar4p.testapp D/Picasso: Hunter      executing    [R0]+5ms 
06-15 05:48:47.264 25550-25577/com.github.qamar4p.testapp D/Picasso: Dispatcher  enqueued     [R0]+4ms 
06-15 05:48:50.905 25550-25577/com.github.qamar4p.testapp D/Picasso: Dispatcher  retrying     [R0]+3646ms 
06-15 05:48:50.908 25550-25592/com.github.qamar4p.testapp D/Picasso: Hunter      executing    [R0]+3650ms 
06-15 05:48:51.975 25550-25577/com.github.qamar4p.testapp D/Picasso: Dispatcher  retrying     [R0]+4712ms 
06-15 05:48:51.990 25550-25594/com.github.qamar4p.testapp D/Picasso: Hunter      executing    [R0]+4725ms 
06-15 05:48:52.025 25550-25577/com.github.qamar4p.testapp D/Picasso: Dispatcher  batched      [R0]+4762ms for error
06-15 05:48:52.249 25550-25550/com.github.qamar4p.testapp D/Picasso: Main        errored      [R0]+4987ms HTTP 504
06-15 05:48:52.249 25550-25577/com.github.qamar4p.testapp D/Picasso: Dispatcher  delivered    [R0]+4986ms 
06-15 05:48:52.259 25550-25550/com.github.qamar4p.testapp E/Picasso: Url: https://d19dnii6y7cwuc.cloudfront.net/uploads/media/3342/original/5b1a2bc8c3863.png
    com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 504
        at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:51)
        at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
        at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)
```

**Comment by Qamar4P** [comment]
From Glide I can say it's some ssl exception but why it's loading in browser. Anyone has information about this?
```
GlideException: Fetch failed
          Cause (1 of 1): class javax.net.ssl.SSLHandshakeException: Chain validation failed
```

**Comment by Qamar4P** [comment]
I change my date to Automatic date & time and Automatic time zone now working fine. Thanks for reading

**Comment by Qamar4P** [comment]
I change my date to Automatic date & time and Automatic time zone now working fine. ref [https://github.com/square/okhttp/wiki/HTTPS](https://github.com/square/okhttp/wiki/HTTPS) Thanks for reading.

**Comment by Qamar4P** [comment]
I change my date to Automatic date & time and Automatic time zone now working fine. ref https://github.com/square/okhttp/wiki/HTTPS Thanks for reading.
