### ISSUE TITLE
Help! Fatal Exception: android.database.sqlite.SQLiteException: table httpauth already exists (code 1)

### ISSUE THREAD

**Issue by nikitoSha** [square/picasso#1935]
Hello! Please, help us to resolve this problem.

	Fatal Exception: android.database.sqlite.SQLiteException: table httpauth already exists (code 1)
		   at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
		   at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:740)
		   at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
		   at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
		   at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1676)
		   at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
		   at org.chromium.android_webview.HttpAuthDatabase$1.run(HttpAuthDatabase.java:19)

Full stack here:  [http://crashes.to/s/6ebbc353ec1](url)

Number 2:

	Fatal Exception: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
		   at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
		   at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:732)
		   at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
		   at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
		   at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1676)
		   at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
		   at org.chromium.android_webview.HttpAuthDatabase$1.run(HttpAuthDatabase.java:1132)

Full stack here:  [http://crashes.to/s/ef537a2f8e2](url)

Number 3:

	Fatal Exception: android.database.sqlite.SQLiteException: table httpauth already exists (code 1)
		   at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
		   at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
		   at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
		   at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
		   at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1679)
		   at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1608)
		   at alL.run(PG:19)

Full stack here: [http://crashes.to/s/a2e9e0824d5](url)

We use gradle v. 4.4 and gradle plugin v. 3.1.3. Build tools 27.0.3, compileSdkVersion 27, minSdkVersion 16.

**Comment by JakeWharton** [comment]
This isn't related to Picasso
