### ISSUE TITLE
App crashes with java.net.UnknownHostException

### ISSUE THREAD

**Issue by trr-amsiq** [square/picasso#1942]
Picasso 2.71828

The following code is within a ```AppWidgetProvider```
```
    Picasso.get()
                 .load(account.profilePictureThumbUrl)
                 .error(R.drawable.as_shared_default_picture_offline_round)
                 .placeholder(R.drawable.as_shared_placeholder_empty)
                 .transform(CropCircleTransformation())
                 .noFade()
                 .get()
```

Should this crash the app or just fail the load call?

> Fatal Exception: java.net.UnknownHostException: Unable to resolve host "www.somesite.com": No address associated with hostname
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
       at java.net.InetAddress.getAllByName(InetAddress.java:787)
       at okhttp3.Dns$1.lookup(Dns.java:40)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
       at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
       at okhttp3.RealCall.execute(RealCall.java:77)
       at com.squareup.picasso.OkHttp3Downloader.load(OkHttp3Downloader.java:91)
       at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:46)
       at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
       at com.squareup.picasso.RequestCreator.get(RequestCreator.java:429)
       at com.example.widget.WidgetProfileItem$setupRoundThumbWithAccount$2.run(WidgetProfileItem.kt:63)
       at java.lang.Thread.run(Thread.java:764)

**Comment by JakeWharton** [comment]
`UnknownHostException` is a subtype of `IOException` which `get()` is declared to throw. This is a normal exception that can occur as a result of transport problems and you should handle it in the catch block.
