### ISSUE TITLE
Providing Vector Drawables as placeholder and/or error resource crashes with Resources$NotFoundException 

### ISSUE THREAD

**Issue by scholt** [square/picasso#1943]
```
   Picasso.get()
          .load("my image url")
          .placeholder(R.drawable.some_vector_fallback_drawable)
          .error(R.drawable.some_vector_error_drawable)
          .into(myImageView);
```

example stacktrace for different 4.4.2 devices:
```
Fatal Exception: android.content.res.Resources$NotFoundException: File res/drawable/no_image.xml from drawable resource ID #0x7f0801c0. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
       at android.content.res.Resources.loadDrawable(Resources.java:2152)
       at android.content.res.Resources.getDrawable(Resources.java:710)
       at com.squareup.picasso.RequestCreator.getPlaceholderDrawable(RequestCreator.java:743)
       at com.squareup.picasso.RequestCreator.into(RequestCreator.java:728)
       at com.squareup.picasso.RequestCreator.into(RequestCreator.java:665)
       at de.aposync.team.promotions.advertising.tv.ProductItem.bind(ProductItem.kt:46)
       at de.aposync.team.widget.adapter.RecyclerItemAdapter.onBindViewHolder(RecyclerItemAdapter.kt:78)
       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:22647)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:13752)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
       at android.view.View.layout(View.java:15142)
       at android.view.ViewGroup.layout(ViewGroup.java:4862)
       at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
       at android.view.View.layout(View.java:15142)
       at android.view.ViewGroup.layout(ViewGroup.java:4862)
       at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:13191)
       at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:895)
       at android.view.View.layout(View.java:15142)
       at android.view.ViewGroup.layout(ViewGroup.java:4862)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
       at android.view.View.layout(View.java:15142)
       at android.view.ViewGroup.layout(ViewGroup.java:4862)
       at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
       at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.findFirstDependency(AppBarLayout.java:1361)
       at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:894)
       at android.view.View.layout(View.java:15142)
       at android.view.ViewGroup.layout(ViewGroup.java:4862)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
       at android.view.View.layout(View.java:15142)
       at android.view.ViewGroup.layout(ViewGroup.java:4862)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
       at android.view.View.layout(View.java:15142)
       at android.view.ViewGroup.layout(ViewGroup.java:4862)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
       at android.view.View.layout(View.java:15142)
       at android.view.ViewGroup.layout(ViewGroup.java:4862)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
       at android.view.View.layout(View.java:15142)
       at android.view.ViewGroup.layout(ViewGroup.java:4862)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
       at android.view.View.layout(View.java:15142)
       at android.view.ViewGroup.layout(ViewGroup.java:4862)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2317)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2023)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1189)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6223)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
       at android.view.Choreographer.doCallbacks(Choreographer.java:591)
       at android.view.Choreographer.doFrame(Choreographer.java:560)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5345)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by NightlyNexus** [comment]
Vector drawable support wasn't added until Android 5.

In the future, maybe you'll be able to make a request handler that uses the vector drawable compat library.
For now, you can set the image manually with the help of the Callback (`into(view, callback)`).

**Comment by scholt** [comment]
Hm yeah, I know I can handle this manually. But is there a specific reason why this is not handled by Picasso or at least a warning/lint error?

**Comment by NightlyNexus** [comment]
because Picasso doesn't include the vector compat support library.
Picasso 3 will require at least 21+. I'm not familiar with the vector compat library anymore, but if there are features in it that still apply to 21+ sdk versions, Picasso maybe should use it.
