### ISSUE TITLE
StrictModeDiskReadViolation: policy : Picasso Lib : picasso:2.5.2  

### ISSUE THREAD

**Issue by successanil** [square/picasso#1944]
Getting this strictmode violation. I suspect this may be the cause of slowness , between fragments transitions in view pager.  Am i right ? 

32236-32236/io.datcompany.datapp.debug D/Error: ERR: stack=android.os.StrictMode$StrictModeDiskReadViolation: policy=4259847 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1263)
        at libcore.io.BlockGuardOs.statvfs(BlockGuardOs.java:297)
        at android.system.Os.statvfs(Os.java:500)
        at android.os.StatFs.doStat(StatFs.java:44)
        at android.os.StatFs.<init>(StatFs.java:39)
        at com.squareup.picasso.Utils.calculateDiskCacheSize(Utils.java:269)
        at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:55)
        at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:45)
        at com.squareup.picasso.Utils$OkHttpLoaderCreator.create(Utils.java:424)
        at com.squareup.picasso.Utils.createDefaultDownloader(Utils.java:250)
        at com.squareup.picasso.Picasso$Builder.build(Picasso.java:832)
        at com.squareup.picasso.Picasso.with(Picasso.java:662)

**Comment by JakeWharton** [comment]
No. This only happens once to initialize the cache. It does not affect the ongoing performance of the app. If you're worried about it, you can create a Downloader that initializes lazily.

**Comment by successanil** [comment]
Thanks for confirming.
