### ISSUE TITLE
Downloading images with same name but different URL links.

### ISSUE THREAD

**Issue by dragneel30** [square/picasso#1957]
I tried it and it doesnt seem to work. when i download it using

```
//cache the images
ImageView iv = new ImageView(context);
for ( int a = 0; a < 10; a++ )
{
String url = "http://localhost:1234/" + Integer.toString(a) + "image";
Picasso.get().load(url).into(iv);
}

//load images from cache
List<ImageView> images = new ArrayList();
for ( int a = 0; a < 10; a++ )
{
images.add(new ImageView(context));
String url ="http://localhost:1234/" + Integer.toString(a) + "image";
Picasso.get().load(url).networkPolicy(NetworkPolicy.OFFLINE).into(images.get(a));
}
```
and then when i display the images, only the last image has an image on it.
when i look at the android monitor it says 
```

W/System.err: com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 504
W/System.err:     at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:51)
W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)


```
the error happens on the first 9 loading of images, the last image i load is loading successfully.

**Comment by InI4** [comment]
The initial load loop loads all images into the same ImageView. To me it looks like a (reasonable) performance optimization within Picasso to cancel previous requests loading images into exactly the same place.

**Comment by dragneel30** [comment]
lnl4 Hi, yea right. what i did was to move the imageview inside the loop so every caching will have its own imageview. 

for ( int a = 0; a < 10; a++ )
{
ImageView iv = new ImageView(context);
String url = "http://localhost:1234/" + Integer.toString(a) + "image";
Picasso.get().load(url).into(iv);
}
