### ISSUE TITLE
Illegal state missing an BitmapHunter exception

### ISSUE THREAD

**Issue by NightlyNexus** [square/picasso#2021]
On master, in my app, I'm getting a lot of this crash. I think it's from network failures.
Unfortunately, it's nontrivial to track down because of all the Android Handler stuff.
```
java.lang.NullPointerException: e == null
  at com.squareup.picasso3.Utils.checkNotNull(Utils.java:102)
  at com.squareup.picasso3.Picasso.deliverAction(Picasso.java:627)
  at com.squareup.picasso3.Picasso.complete(Picasso.java:576)
  at com.squareup.picasso3.Picasso$1.handleMessage(Picasso.java:110)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:136)
```

**Comment by JakeWharton** [comment]
Can we trace back the codepath to any source of null for the exception? Seems like we need to move a null check farther "up".
