### ISSUE TITLE
Picasso can't load pic in Android P without any information.

### ISSUE THREAD

**Issue by liangpengfei** [square/picasso#2022]
picasso version is 2.71828 , no useful information just show nothing!

**Comment by JakeWharton** [comment]
Picasso developers can't diagnose problems in the library without any information.

**Comment by JakeWharton** [comment]
Retry indicates there was a failure to load the image over the network and a 504 means the image was not available in the cache.

**Comment by tejraj123** [comment]
try using android:usesCleartextTraffic="true" in Application tag of menifest 

https://stackoverflow.com/q/53139689/8731069
This works for me 😊

**Comment by spacemase** [comment]
I have the same issue, cleartext traffic is already enabled however.  My logs:

```2018-11-23 19:23:41.579 11959-12155/com.xyz.debug D/skia: --- SkAndroidCodec::NewFromStream returned null
2018-11-23 19:23:41.602 1647-1894/system_process E/memtrack: Couldn't load memtrack module
2018-11-23 19:23:41.602 1647-1894/system_process W/android.os.Debug: failed to get memory consumption info: -1
2018-11-23 19:23:41.606 11959-11971/com.xyz.debug I/zygote: Background concurrent copying GC freed 57528(5MB) AllocSpace objects, 60(1200KB) LOS objects, 36% free, 10MB/16MB, paused 5.207ms total 41.188ms
2018-11-23 19:23:41.888 1647-1894/system_process E/memtrack: Couldn't load memtrack module
2018-11-23 19:23:41.889 1647-1894/system_process W/android.os.Debug: failed to get memory consumption info: -1
2018-11-23 19:23:42.047 11959-12090/com.xyz.debug D/Picasso: Dispatcher  batched      [R109]+1680ms for error (will replay)
2018-11-23 19:23:42.053 11959-12090/com.xyz.debug D/Picasso: Dispatcher  batched      [R108]+1686ms for error (will replay)
2018-11-23 19:23:42.076 11959-12090/com.xyz.debug D/Picasso: Dispatcher  batched      [R110]+1707ms for error (will replay)
2018-11-23 19:23:42.082 11959-12090/com.xyz.debug D/Picasso: Dispatcher  batched      [R107]+1715ms for error (will replay)
2018-11-23 19:23:42.180 1647-1894/system_process E/memtrack: Couldn't load memtrack module
2018-11-23 19:23:42.180 1647-1894/system_process W/android.os.Debug: failed to get memory consumption info: -1
2018-11-23 19:23:42.249 11959-11959/com.xyz.debug D/Picasso: Main        errored      [R109]+1882ms 
2018-11-23 19:23:42.249 11959-12090/com.xyz.debug D/Picasso: Dispatcher  delivered    [R109]+1882ms, [R108]+1882ms, [R110]+1881ms, [R107]+1882ms 
2018-11-23 19:23:42.249 11959-11959/com.xyz.debug W/System.err: java.io.IOException: Failed to decode stream.
2018-11-23 19:23:42.249 11959-11959/com.xyz.debug W/System.err:     at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:145)
2018-11-23 19:23:42.250 11959-11959/com.xyz.debug W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
2018-11-23 19:23:42.250 11959-11959/com.xyz.debug W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
2018-11-23 19:23:42.250 11959-11959/com.xyz.debug W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
2018-11-23 19:23:42.250 11959-11959/com.xyz.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-11-23 19:23:42.250 11959-11959/com.xyz.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2018-11-23 19:23:42.250 11959-11959/com.xyz.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2018-11-23 19:23:42.250 11959-11959/com.xyz.debug W/System.err:     at java.lang.Thread.run(Thread.java:764)
2018-11-23 19:23:42.250 11959-11959/com.xyz.debug W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
2018-11-23 19:23:42.250 11959-11959/com.xyz.debug D/Picasso: Main        errored      [R108]+1883ms 
2018-11-23 19:23:42.250 11959-11959/com.xyz.debug W/System.err: java.io.IOException: Failed to decode stream.
2018-11-23 19:23:42.250 11959-11959/com.xyz.debug W/System.err:     at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:145)
2018-11-23 19:23:42.250 11959-11959/com.xyz.debug W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
2018-11-23 19:23:42.251 11959-11959/com.xyz.debug W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
2018-11-23 19:23:42.251 11959-11959/com.xyz.debug W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
2018-11-23 19:23:42.251 11959-11959/com.xyz.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-11-23 19:23:42.251 11959-11959/com.xyz.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2018-11-23 19:23:42.251 11959-11959/com.xyz.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2018-11-23 19:23:42.251 11959-11959/com.xyz.debug W/System.err:     at java.lang.Thread.run(Thread.java:764)
2018-11-23 19:23:42.251 11959-11959/com.xyz.debug W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
2018-11-23 19:23:42.251 11959-11959/com.xyz.debug D/Picasso: Main        errored      [R110]+1883ms 
2018-11-23 19:23:42.251 11959-11959/com.xyz.debug W/System.err: java.io.IOException: Failed to decode stream.
2018-11-23 19:23:42.251 11959-11959/com.xyz.debug W/System.err:     at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:145)
2018-11-23 19:23:42.251 11959-11959/com.xyz.debug W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
2018-11-23 19:23:42.251 11959-11959/com.xyz.debug W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
2018-11-23 19:23:42.251 11959-11959/com.xyz.debug W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
2018-11-23 19:23:42.252 11959-11959/com.xyz.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-11-23 19:23:42.252 11959-11959/com.xyz.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2018-11-23 19:23:42.252 11959-11959/com.xyz.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2018-11-23 19:23:42.252 11959-11959/com.xyz.debug W/System.err:     at java.lang.Thread.run(Thread.java:764)
2018-11-23 19:23:42.252 11959-11959/com.xyz.debug W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
2018-11-23 19:23:42.252 11959-11959/com.xyz.debug D/Picasso: Main        errored      [R107]+1885ms 
2018-11-23 19:23:42.253 11959-11959/com.xyz.debug W/System.err: java.io.IOException: Failed to decode stream.
2018-11-23 19:23:42.253 11959-11959/com.xyz.debug W/System.err:     at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:145)
2018-11-23 19:23:42.253 11959-11959/com.xyz.debug W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
2018-11-23 19:23:42.253 11959-11959/com.xyz.debug W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
2018-11-23 19:23:42.253 11959-11959/com.xyz.debug W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
2018-11-23 19:23:42.254 11959-11959/com.xyz.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-11-23 19:23:42.254 11959-11959/com.xyz.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2018-11-23 19:23:42.254 11959-11959/com.xyz.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2018-11-23 19:23:42.254 11959-11959/com.xyz.debug W/System.err:     at java.lang.Thread.run(Thread.java:764)
2018-11-23 19:23:42.254 11959-11959/com.xyz.debug W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
2018-11-23 19:23:42.468 1647-1894/system_process E/memtrack: Couldn't load memtrack module
2018-11-23 19:23:42.468 1647-1894/system_process W/android.os.Debug: failed to get memory consumption info: -1```

**Comment by LazarRistic** [comment]
Same here. Worked for month and today in the middle of the day for no reason stop working.
Using: Samsung Galaxy S7 edge, Android Pie.
Code is in Kotlin and u can see it below 

> 
    Picasso.get()
        .load("http://www.ples.co.rs/klubovi/logo/K00002.jpg")
        .error(R.drawable.ic_photo)
        .into(biding.clubLogo, object : Callback {
            override fun onSuccess() {
                biding.clubLogo.visibility = View.VISIBLE
            }
        
            override fun onError(e: Exception) {
                 // ignored
                throw e.fillInStackTrace()
            }
        })

Error:

> Caused by: com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 504
        at com.overswayit.plesnisavezsrbije.views.ClubsAdapter$ClubsViewHolder$bind$1.onError(ClubsAdapter.kt:59)
        at com.squareup.picasso.ImageViewAction.error(ImageViewAction.java:72)
        at com.squareup.picasso.Picasso.deliverAction(Picasso.java:581)
        at com.squareup.picasso.Picasso.complete(Picasso.java:528)
        at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:122)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by keehoo** [comment]
Same here :(
