### ISSUE TITLE
Image loading failed with version 2.71828

### ISSUE THREAD

**Issue by mukesh8293** [square/picasso#2070]
I was using version  2.5.2 in my all application then everything was working fine.
I just updated to 2.71828 then it's not loading same URL's.

URL = https://pixabay.com/get/ec30b00a2df01c22d2524518b74d479ee373e7d019ac104490f1c97ea2ecbdba_640.jpg

I tried to load this URL with 2.5.2, it's loading but failed with 2.71828.

**Comment by NightlyNexus** [comment]
what's the stack trace? attach an error listener or check in the callback.

**Comment by mukesh8293** [comment]
W/System.err: com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 504
at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:51)
at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)

ERROR MESSAGE   **HTTP 504**

It's **not** running in **android Pie**.
Same URL loading fine  **with 2.5.5**

**Comment by camhart** [comment]
This was happening to me when I was using https://github.com/JakeWharton/picasso2-okhttp3-downloader.  Once I removed that, everything worked.

**Comment by GORR174** [comment]
The same error. I'm not using downloader. Here is my code:
```kotlin
Picasso.get().load(url)
                .placeholder(R.drawable.loading)
                .error(R.drawable.error)
                .into(imageView, object : Callback {
                    //error & success listeners
                })
```
On my phone with android 8.0.0 it works fine, but on my other phone with android 4.4.2 it works only with picasso 2.5.2.

**Comment by brianchu** [comment]
Same here except I do it on purpose to have a corrupted jpg and use Charles to serve it locally. I do expect error but I don't expect HTTP 504.

**Comment by peterfortuin** [comment]
Apparently the Picasso OkHttp3 downloader is now included into Picasso. So you need to remove your dependency to JakeWharton/picasso2-okhttp3-downloader.
