### ISSUE TITLE
Error loading bitmap java.lang.NullPointerException: bitmap == null at com.squareup.picasso.aa.a(Utils.java:114)

### ISSUE THREAD

**Issue by Flyktsodan** [square/picasso#2079]
Been getting lots of crash-reports with this stacktrace:

`Fatal Exception: java.lang.NullPointerException: bitmap == null
       at com.squareup.picasso.Utils.checkNotNull(Utils.java:114)
       at com.squareup.picasso.RequestHandler$Result.(RequestHandler.java:60)
       at com.squareup.picasso.ResourceRequestHandler.load(ResourceRequestHandler.java:45)
       at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
       at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
       at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)`

We haven't been able to reproduce it ourselves and we use Picasso in a lots of different ways but maybe someone could point me in the direction when this would happen. My guess is that one of our many Transformation is doing something fishy.

**Comment by JakeWharton** [comment]
Do you have the de-obfuscated trace?

**Comment by Flyktsodan** [comment]
updated my question.

**Comment by NightlyNexus** [comment]
from a quick look, it looks like it could be from BitmapFactory.decodeResource returning null here: https://github.com/square/picasso/blob/2.71828/picasso/src/main/java/com/squareup/picasso/ResourceRequestHandler.java#L54
maybe a missing resource?

**Comment by Flyktsodan** [comment]
@NightlyNexus you are correct, we had some legacy code for loading bitmaps into a target and using placeholders - I'll close this issue since it's not a Picasso problem.
