### ISSUE TITLE
NullpointerException on loading the picture

### ISSUE THREAD

**Issue by Hoss3inf** [square/picasso#2110]
here is the code which is supposed to fetch the picture:
```
Picasso.with(this)
                .load(presignedUrl.toString().trim())
                .into(fullimgview);
```
and as I try to fetch the pictures on a recyclerView, it throws exception as I open the 5th or 6th picture:

```
java.lang.NullPointerException: Attempt to read from field 'float android.graphics.PointF.x' on a null object reference
        at com.ortiz.touchview.TouchImageView.setZoom(TouchImageView.java:416)
        at com.ortiz.touchview.TouchImageView.setScaleType(TouchImageView.java:203)
        at android.app.ActivityTransitionCoordinator.setSharedElementState(ActivityTransitionCoordinator.java:448)
        at android.app.ActivityTransitionCoordinator.setSharedElementState(ActivityTransitionCoordinator.java:583)
        at android.app.EnterTransitionCoordinator.startSharedElementTransition(EnterTransitionCoordinator.java:405)
        at android.app.EnterTransitionCoordinator.-wrap4(EnterTransitionCoordinator.java)
        at android.app.EnterTransitionCoordinator$5$1$1.run(EnterTransitionCoordinator.java:475)
        at android.app.ActivityTransitionCoordinator.startTransition(ActivityTransitionCoordinator.java:836)
        at android.app.EnterTransitionCoordinator$5$1.onPreDraw(EnterTransitionCoordinator.java:472)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1013)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2513)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1522)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7098)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
        at android.view.Choreographer.doCallbacks(Choreographer.java:702)
        at android.view.Choreographer.doFrame(Choreographer.java:638)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```
The problem is that none of the errors in this log is related to my app, and i dont know how to trace the problem.

**Comment by jrodbx** [comment]
There's no mention of Picasso in the stack trace, so I'm not sure there's any action to take here.  If you have a sample/repro project, please file another issue.
