### ISSUE TITLE
 Using update picasso version 2.71828 app sudden crashed

### ISSUE THREAD

**Issue by Nababkhan007** [square/picasso#2150]
When I using update picasso version 2.71828, then my project show an unexpected error. My project minimum api level is 16. Please give me a solution to solved the issue. Thanks!

Error log: 

java.lang.ExceptionInInitializerError
        at e.b0.a(:263)
        at e.b0.<init>(:229)
        at e.b0$b.a(:1015)
        at com.squareup.picasso.s.<init>(:71)
        at com.squareup.picasso.s.<init>(:50)
        at com.squareup.picasso.s.<init>(:40)
        at com.squareup.picasso.t$b.a(:848)
        at com.squareup.picasso.t.b(:683)
        at g.a.c.g0.a(:566)
        at g.a.c.g0.a(:69)
        at g.a.c.g0$d.a(:299)
        at g.a.c.g0$d.a(:276)
        at d.a.a.v.l.c(:82)
        at d.a.a.v.l.a(:29)
        at d.a.a.f$b.run(:102)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:5330)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:830)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:646)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19

**Comment by JakeWharton** [comment]
You're using OkHttp 3.13 or newer which requires Android 21 or newer. If you need to support older versions of Android you must use OkHttp 3.12.
