### ISSUE TITLE
ResponseException: 410 Gone

### ISSUE THREAD

**Issue by Ali-Rezaei** [square/picasso#2155]
I am trying to show an image from a url ( which is working fine in browser ) in my ImageView using Picasso '2.5.2' version :
```
val builder = Picasso.Builder(imageView.context)
builder.listener { _, _, exception -> exception.printStackTrace() }
builder.build().load("https://via.placeholder.com/600/568c72").into(imageView)
```

I receive following exception :
 ```
com.squareup.picasso.Downloader$ResponseException: 410 Gone
2020-02-23 19:14:08.112 2764-2764/com.sample.android.storytel W/System.err:     at com.squareup.picasso.UrlConnectionDownloader.load(UrlConnectionDownloader.java:96)
2020-02-23 19:14:08.112 2764-2764/com.sample.android.storytel W/System.err:     at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
2020-02-23 19:14:08.112 2764-2764/com.sample.android.storytel W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
2020-02-23 19:14:08.112 2764-2764/com.sample.android.storytel W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
2020-02-23 19:14:08.113 2764-2764/com.sample.android.storytel W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2020-02-23 19:14:08.113 2764-2764/com.sample.android.storytel W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-02-23 19:14:08.113 2764-2764/com.sample.android.storytel W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-02-23 19:14:08.113 2764-2764/com.sample.android.storytel W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-02-23 19:14:08.113 2764-2764/com.sample.android.storytel W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-02-23 19:14:08.113 2764-2764/com.sample.android.storytel W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```

**Comment by JakeWharton** [comment]
This is a normal HTTP exception indicating the URL no longer exists. Picasso will retain the placeholder or if you supply an error drawable that will be used.

**Comment by Ali-Rezaei** [comment]
Thank you @JakeWharton , but when I use url (https://via.placeholder.com/600/568c72) in a browser like Google chrome, it loads the image. Why?

**Comment by JakeWharton** [comment]
I have no idea, but a 410 means the server successfully received the request and decided to return an error message. So either your request is malformed or it's for a different resource which actually does not exist.
