### ISSUE TITLE
Google Play Console Android compatibility (non-SDK api)

### ISSUE THREAD

**Issue by AlexSheva-mason** [square/picasso#2170]
Upon sending my app for a review, pre-launch report came up with multiple compatibility warnings referencing Picasso.
One of the stack traces:
```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Class.java)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at okhttp3.internal.platform.OptionalMethod.getPublicMethod(OptionalMethod.java:1)
	at okhttp3.internal.platform.OptionalMethod.getMethod(OptionalMethod.java:1)
	at okhttp3.internal.platform.OptionalMethod.invoke(OptionalMethod.java:4)
	at okhttp3.internal.platform.OptionalMethod.invokeWithoutCheckedException(OptionalMethod.java:0)
	at okhttp3.internal.platform.AndroidPlatform.getSelectedProtocol(AndroidPlatform.java:2)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:29)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:29)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:11)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:47)
	at okhttp3.internal.connection.StreamAllocation.e(StreamAllocation.java:0)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:10)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:2)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:111)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:111)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:2)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:27)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:27)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:2)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:7)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:2)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:6)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:12)
	at okhttp3.RealCall.execute(RealCall.java:28)
	at com.squareup.picasso.OkHttp3Downloader.load(OkHttp3Downloader.java:28)
	at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:28)
	at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:2)
	at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:2)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
	at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:5)
```

It was also present in other "unsupported API" warnings:

```
Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V
Lcom/android/org/conscrypt/ConscryptFileDescriptorSocket;->setHostname(Ljava/lang/String;)V
Lcom/android/org/conscrypt/ConscryptFileDescriptorSocket;->setUseSessionTickets(Z)V
Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V
Ldalvik/system/CloseGuard;->warnIfOpen()V
```

I am using v. 2.71828

**Comment by JakeWharton** [comment]
Please use the latest OkHttp 3.x or 4.x which does not use these methods on newer API levels.

 * 4.x: https://square.github.io/okhttp/changelog/
 * 3.x: https://square.github.io/okhttp/changelog_3x/

**Comment by AlexSheva-mason** [comment]
> You will have to specify the okhttp dependency manually to get the newer version. The next release of Picasso, if there ever is one, will use this newer version by default, but there's no timeline on that and we don't release new versions simply to track upgrades of our dependencies (on any square project).

Thank you, will do just that.
Is Picasso no longer being developed or updated? Didn't know that I'm sorry

**Comment by JakeWharton** [comment]
It's just stable.

While there's efforts we would like to pursue they are not a high priority.
