### ISSUE TITLE
Picasso not loading certain images while glide loads it fine

### ISSUE THREAD

**Issue by xrafi** [square/picasso#2221]
Picasso is not loading certain images while glide loads it fine

eg.
https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6407/6407695_sd.jpg
https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6407/6407695_sd.jpg

error

com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 403
        at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:51)
        at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
        at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
        at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)

**Comment by JakeWharton** [comment]
Ah HTTP 403 means the server successfully processed the request and has chosen not to fulfill it for some reason. This could be because of rate limiting or some other reason (perhaps indicated in headers). But that response code means that the HTTP request Picasso is issuing is correct and the server is choosing not to honor it (and thus Picasso never sees an image in the response data). There is nothing we are able to do about this–it's between your app and the server and not specific to the Picasso library.
