### ISSUE TITLE
Strict Mode Violations When Scrolling

### ISSUE THREAD

**Issue by DavidTPate** [square/picasso#296]
Hitting the following stack trace when scrolling with StrictMode on:

```
E/StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
java.lang.Throwable: Explicit termination method 'end' not called
    at dalvik.system.CloseGuard.open(CloseGuard.java:184)
    at java.util.zip.Inflater.<init>(Inflater.java:82)
    at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:96)
    at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:81)
    at libcore.net.http.HttpEngine.initContentStream(HttpEngine.java:541)
    at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:844)
    at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:283)
    at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:495)
    at com.squareup.picasso.UrlConnectionDownloader.load(UrlConnectionDownloader.java:64)
    at com.squareup.picasso.NetworkBitmapHunter.decode(NetworkBitmapHunter.java:46)
    at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:111)
    at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:82)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
    at java.lang.Thread.run(Thread.java:856)
    at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:218)
```

Here's the settings that I'm using for StrictMode:

``` java
StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
                                   .detectDiskReads()
                                   .detectDiskWrites()
                                   .detectAll()
                                   .penaltyLog()
                                   .build());
StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                               .detectLeakedSqlLiteObjects()
                               .detectLeakedClosableObjects()
                               .penaltyLog()
                               .build());
```

Took at look at similar issues (#245 and #206) but didn't see any resemblance to the issue that I'm hitting, especially since both of those issues look to be fixed and included in current versions.

**Comment by mrmaffen** [comment]
This issue is still happening for me. I'm using okhttp 2.5.0 (the stacktrace doesn't show any involvement of picasso though)
```
E/StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'end' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:180)
            at java.util.zip.Inflater.<init>(Inflater.java:82)
            at okio.GzipSource.<init>(GzipSource.java:62)
            at com.squareup.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
            at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:821)
            at com.squareup.okhttp.Call.getResponse(Call.java:268)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
            at com.squareup.okhttp.Call.execute(Call.java:79)
            at org.tomahawk.libtomahawk.infosystem.hatchet.Store.get(Store.java:834)
            at org.tomahawk.libtomahawk.infosystem.hatchet.Store.storeRecords(Store.java:383)
            at org.tomahawk.libtomahawk.infosystem.hatchet.Store.storeRecords(Store.java:212)
            at org.tomahawk.libtomahawk.infosystem.hatchet.HatchetInfoPlugin.getParseConvert(HatchetInfoPlugin.java:157)
            at org.tomahawk.libtomahawk.infosystem.hatchet.HatchetInfoPlugin.access$000(HatchetInfoPlugin.java:58)
            at org.tomahawk.libtomahawk.infosystem.hatchet.HatchetInfoPlugin$1.run(HatchetInfoPlugin.java:124)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by JakeWharton** [comment]
We've removed HttpURLConnection support on `master` and the OkHttp leak is fixed in the 3.x versions.
