### ISSUE TITLE
Handler still used after canceling

### ISSUE THREAD

**Issue by arvola** [square/picasso#445]
I noticed that at times there are exceptions in the logs when navigating activities, even though the image downloads are being canceled prior.

I'm not very familiar with the inner workings of Picasso, but it would seem that `BitmapHunter.hunt()` does not check if it has been canceled while it's running, and so ends up trying to contact a dead handler at the end:

```
Handler (com.squareup.picasso.Stats$StatsHandler) {41b13d40} sending message to a Handler on a dead thread
    java.lang.RuntimeException: Handler (com.squareup.picasso.Stats$StatsHandler) {41b13d40} sending message to a Handler on a dead thread
            at android.os.MessageQueue.enqueueMessage(MessageQueue.java:196)
            at android.os.Handler.sendMessageAtTime(Handler.java:473)
            at android.os.Handler.sendMessageDelayed(Handler.java:446)
            at android.os.Handler.sendMessage(Handler.java:383)
            at com.squareup.picasso.Stats.processBitmap(Stats.java:104)
            at com.squareup.picasso.Stats.dispatchBitmapTransformed(Stats.java:59)
            at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:136)
            at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:83)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
```

Since the exception is caught, it doesn't currently affect the app in any significant way, but I'd wager it'd still be better to avoid the exception in the first place.

Thoughts? I can make the necessary changes.

**Comment by cypressf** [comment]
I'm also seeing this happen in my app. I'm customizing and setting the singleton instance in my app in Application.onCreate(), then using the singleton in several activities, using Picasso.with(context). When I run tests and rapidly cycle between activities that use Picasso, I am seeing quite a few of these warnings all at once:

```
06-16 13:16:09.030 5186-7414/com.onshape.app.debug W/MessageQueue: Handler (com.squareup.picasso.Stats$StatsHandler) {36fe3f9b} sending message to a Handler on a dead thread
                                                                   java.lang.IllegalStateException: Handler (com.squareup.picasso.Stats$StatsHandler) {36fe3f9b} sending message to a Handler on a dead thread
                                                                       at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
                                                                       at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                       at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                       at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                       at android.os.Handler.sendMessage(Handler.java:507)
                                                                       at com.squareup.picasso.Stats.processBitmap(Stats.java:119)
                                                                       at com.squareup.picasso.Stats.dispatchBitmapDecoded(Stats.java:60)
                                                                       at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:228)
                                                                       at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                       at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
06-16 13:16:09.042 5186-7414/com.onshape.app.debug W/MessageQueue: Handler (com.squareup.picasso.Dispatcher$DispatcherHandler) {2e847f38} sending message to a Handler on a dead thread
                                                                   java.lang.IllegalStateException: Handler (com.squareup.picasso.Dispatcher$DispatcherHandler) {2e847f38} sending message to a Handler on a dead thread
                                                                       at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
                                                                       at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                       at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                       at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                       at android.os.Handler.sendMessage(Handler.java:507)
                                                                       at com.squareup.picasso.Dispatcher.dispatchComplete(Dispatcher.java:154)
                                                                       at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:164)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                       at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
06-16 13:16:09.045 5186-7413/com.onshape.app.debug W/MessageQueue: Handler (com.squareup.picasso.Stats$StatsHandler) {36fe3f9b} sending message to a Handler on a dead thread
                                                                   java.lang.IllegalStateException: Handler (com.squareup.picasso.Stats$StatsHandler) {36fe3f9b} sending message to a Handler on a dead thread
                                                                       at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
                                                                       at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                       at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                       at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                       at android.os.Handler.sendMessage(Handler.java:507)
                                                                       at com.squareup.picasso.Stats.processBitmap(Stats.java:119)
                                                                       at com.squareup.picasso.Stats.dispatchBitmapDecoded(Stats.java:60)
                                                                       at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:228)
                                                                       at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                       at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
06-16 13:16:09.045 5186-7413/com.onshape.app.debug W/MessageQueue: Handler (com.squareup.picasso.Dispatcher$DispatcherHandler) {2e847f38} sending message to a Handler on a dead thread
                                                                   java.lang.IllegalStateException: Handler (com.squareup.picasso.Dispatcher$DispatcherHandler) {2e847f38} sending message to a Handler on a dead thread
                                                                       at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
                                                                       at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                       at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                       at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                       at android.os.Handler.sendMessage(Handler.java:507)
                                                                       at com.squareup.picasso.Dispatcher.dispatchComplete(Dispatcher.java:154)
                                                                       at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:164)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                       at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
06-16 13:16:09.069 5186-7415/com.onshape.app.debug W/MessageQueue: Handler (com.squareup.picasso.Stats$StatsHandler) {36fe3f9b} sending message to a Handler on a dead thread
                                                                   java.lang.IllegalStateException: Handler (com.squareup.picasso.Stats$StatsHandler) {36fe3f9b} sending message to a Handler on a dead thread
                                                                       at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
                                                                       at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                       at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                       at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                       at android.os.Handler.sendMessage(Handler.java:507)
                                                                       at com.squareup.picasso.Stats.processBitmap(Stats.java:119)
                                                                       at com.squareup.picasso.Stats.dispatchBitmapDecoded(Stats.java:60)
                                                                       at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:228)
                                                                       at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                       at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
06-16 13:16:09.070 5186-7415/com.onshape.app.debug W/MessageQueue: Handler (com.squareup.picasso.Dispatcher$DispatcherHandler) {2e847f38} sending message to a Handler on a dead thread
                                                                   java.lang.IllegalStateException: Handler (com.squareup.picasso.Dispatcher$DispatcherHandler) {2e847f38} sending message to a Handler on a dead thread
                                                                       at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
                                                                       at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                       at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                       at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                       at android.os.Handler.sendMessage(Handler.java:507)
                                                                       at com.squareup.picasso.Dispatcher.dispatchComplete(Dispatcher.java:154)
                                                                       at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:164)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                       at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```
