### ISSUE TITLE
fit(), resize(): java.io.IOException: Cannot reset

### ISSUE THREAD

**Issue by Hazer** [square/picasso#465]
Hi Square team!

We are having issues loading images in a ListView for a chat in our app.
When we try to **resize** the bitmap, from the links below, gives us **java.io.IOException: Cannot reset**
If I do not resize, no problem loading the bitmap.

The apps got tested in a Moto G XT1028 Android 4.4.2 and a LG e435f Android 4.1.2.
Latest Picasso and Picasso 2.1.1
Same behaviour same pics.

```
http://www.bnmsp.de/home/e.huber/epica/Simone_Simons.jpg
```
and took from issue #364 also **don't work**
```
http://store.indemand.com/shared/ovs/prodimages/movies/t/troublewiththecurve_ID0360906/troublewiththecurveBM_ID0360906.jpg
```

This one from issue #250 **works** perfect, if it helps.
```
http://clashot.com/avatars/1782/1782318/z_1782318.jpg
```

Calling in my adapter
```java
Picasso.with(convertView.getContext())
                   .load(message.getSenderPic())
                    .resizeDimen(R.dimen.chat_sender_pic, R.dimen.chat_sender_pic)
//                   .fit()
                    .centerCrop()
                    .transform(new CircleTransform())
                    .into(holder.chatSenderPic);
```

Result
```java
    java.io.IOException: Cannot reset
            at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:94)
            at com.squareup.picasso.NetworkBitmapHunter.decodeStream(NetworkBitmapHunter.java:91)
            at com.squareup.picasso.NetworkBitmapHunter.decode(NetworkBitmapHunter.java:60)
            at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:111)
            at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:82)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
            at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:218)
```

Thanks

**Comment by dnkoutso** [comment]
This is our highest priority for 2.5.1

**Comment by JakeWharton** [comment]
Dupe #364.
