### ISSUE TITLE
WeakReferences cannot be cast to com.squareup.picasso.Request$RequestWeakReference

### ISSUE THREAD

**Issue by mbronzovic** [square/picasso#471]
Hi there, I´m experiencing this issue when using the Picasso Library for loading images from a url.
I´m loading the images using a Target, which is a field member in my class to avoid the GC. Also I´m calling cancelRequest when leaving the Activity/Fragment to prevent any errors or leaks.
When testing the app I cant reproduce it, this log is been sent by Crashlytics Service.

*\* LOG **

```
java.lang.RuntimeException: java.lang.ClassCastException: java.lang.ref.WeakReference cannot be cast to com.squareup.picasso.Request$RequestWeakReference
       at com.squareup.picasso.Picasso$CleanupThread$1.run(Picasso.java:478)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4960)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.ClassCastException: java.lang.ref.WeakReference cannot be cast to com.squareup.picasso.Request$RequestWeakReference
       at com.squareup.picasso.Picasso$CleanupThread.run(Picasso.java:473)
```

*\* END LOG **

ok.http v1.0.3
Picasso v1.1.2

My Code:

``` java
    /**

    * Async loading of the image from Server

    * @param url of the image to load

    */

    public void fillImageViewComponentFromUrl(String url) {

        mLoadingSpinner.setVisibility(View.VISIBLE);

        mImageView.setVisibility(View.GONE);

        mUrlImage = url;

        Picasso.with(mFragment.getActivity())

            .load( url)



            .into(myTarget);    

    }

    private Target myTarget = new Target() {

        @Override

        public void onSuccess(final Bitmap bm) {

        mFragment.getActivity().runOnUiThread(new Runnable() {

            @Override

            public void run() {

                mLoadingSpinner.setVisibility(View.GONE);

                mImageView.setVisibility(View.VISIBLE);

                int dpValue = 250; // margin in dps

                float d = getContext().getResources().getDisplayMetrics().density;

                int margin = (int)(dpValue * d); // margin in pixels                

                mImageView.setImageBitmap(UtilImage.getResizedBitmap(bm, margin));

                }

        });

    }

        @Override

        public void onError() {

            System.out.println("CAMERA PHOTO VIEW COMPONENT - FAILED TO FILL IMAGEVIEW FROM URL: " + mUrlImage);

            mLoadingSpinner.setVisibility(View.GONE);

            mImageView.setVisibility(View.VISIBLE);

        }

    };
```

**Comment by Alok255** [comment]
### ### ### #1950 #1256
