### ISSUE TITLE
Getting 504 Gateway Timeout from ResponseException

### ISSUE THREAD

**Issue by riclage** [square/picasso#501]
I'm having an issue on some devices on the same network when downloading photos from Flickr. Following your suggestion on a [previous issue](https://github.com/square/picasso/issues/500), here is how I'm calling Picasso:

``` java
OkHttpClient client = new OkHttpClient();
client.setProtocols(Arrays.asList(Protocol.HTTP_11));
Picasso picasso = new Picasso.Builder(c)
        .downloader(new OkHttpDownloader(client))
        .listener(new Listener() {
                    @Override
                    public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                      exception.printStackTrace();
                    }
                  })
        .build();
```

And here is the full stack trace of the exception I'm getting:

``` java
com.squareup.picasso.Downloader$ResponseException: 504 Gateway Timeout
    at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:108)
    at com.squareup.picasso.NetworkBitmapHunter.decode(NetworkBitmapHunter.java:46)
    at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:123)
    at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:83)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
    at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:306)
```

I tried playing with `client.setConnectTimeout` and `client.setReadTimeout` but they don't seem to influence the downloader at all. The crash always occur before any timeout I set. Any ideas?

Thanks.

**Comment by jaisonz** [comment]
Please check the answer added to [#683](https://github.com/square/picasso/issues/683). Hope this helps

**Comment by ahmet12** [comment]
https://stackoverflow.com/a/50834600
