### ISSUE TITLE
IOException: Failed to decode stream

### ISSUE THREAD

**Issue by niqo01** [square/picasso#543]
I am having a `Failed to decode stream` using picasso on a specific image. Please find below the error detail:

Picasso: 2.3.2
Android SDK: 4.4.2
Device: SM-G900F
Image:
![picasso_decode_error](https://cloud.githubusercontent.com/assets/1121251/3222470/b753d574-f016-11e3-8329-939adc105299.jpg)

```
PicassoException: Error while loading image with Picasso
       at com.couchsurfing.mobile.data.DataModule$1.onImageLoadFailed(DataModule.java:158)
       at com.squareup.picasso.Picasso.complete(Picasso.java:374)
       at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:97)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5579)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.io.IOException: Failed to decode stream.
       at com.squareup.picasso.NetworkBitmapHunter.decodeStream(NetworkBitmapHunter.java:121)
       at com.squareup.picasso.NetworkBitmapHunter.decode(NetworkBitmapHunter.java:72)
       at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:144)
       at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:101)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
       at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:394)
```

**Comment by dimsuz** [comment]
Happened to me with Picasso 2.5.2, got this output (note warnings from skia):

```
D  --- decoder->decode returned false
D  --- decoder->decode returned false
E  java.io.IOException: Failed to decode stream.
E      at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:145)
E      at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
E      at com.squareup.picasso.RequestCreator.get(RequestCreator.java:396)
E      at ru.appkode.pga.util.RxUtils$2.call(RxUtils.java:82)
E      at ru.appkode.pga.util.RxUtils$2.call(RxUtils.java:75)
E      at ru.appkode.pga.util.RxUtils$1.call(RxUtils.java:43)
E      at ru.appkode.pga.util.RxUtils$1.call(RxUtils.java:35)
E      at rx.Observable.unsafeSubscribe(Observable.java:7531)
E      at rx.internal.operators.OperatorZip$Zip.start(OperatorZip.java:213)
E      at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:155)
E      at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:120)
E      at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:43)
E      at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:32)
E      at rx.Observable$1.call(Observable.java:144)
E      at rx.Observable$1.call(Observable.java:136)
E      at rx.Observable.unsafeSubscribe(Observable.java:7531)
E      at rx.internal.operators.OperatorMerge$MergeSubscriber.handleNewSource(OperatorMerge.java:215)
E      at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:185)
E      at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:120)
E      at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
E      at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onNext(OperatorOnErrorResumeNextViaFunction.java:89)
E      at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
E      at retrofit.RxSupport$2.run(RxSupport.java:56)
E      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
E      at java.util.concurrent.FutureTask.run(FutureTask.java:234)
E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
E      at retrofit.Platform$Android$2$1.run(Platform.java:142)
E      at java.lang.Thread.run(Thread.java:838)
```

**Comment by HellAvalor** [comment]
What could it be?

Not loading
![Not loading](http://jadmin.jeunesseglobaldev.com/imgdb/videos/SECRET-OF-JEUNESSE.jpg)
Loading normal
![Loading normal](https://jadmin.jeunesseglobal.com/imgdb/videos/SERUM_SAMPLING.jpg)

Both load normal with lazyLoader and other images from htt/https loading normal

Error Trace
 java.io.IOException: Failed to decode stream.
at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:145)
at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:841)
at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

Picasso: 2.5.2
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.squareup.okhttp:okhttp:2.2.0'

compileSdkVersion 22
targetSdkVersion 20

Builder config
picasso = new Picasso.Builder(application).listener(new Picasso.Listener() {
                    @Override
                    public void onImageLoadFailed(Picasso picasso, Uri uri, Exception exception) {
                        exception.printStackTrace();
                    }
                }).build();
