### ISSUE TITLE
[Android L] NoSuchMethodError: No static method source(Ljava/io/File;)Lokio/Source; in class Lokio/Okio;

### ISSUE THREAD

**Issue by StErMi** [square/picasso#567]
This is my actual setup:
- picasso-2.3.2.jar
- okio-1.0.0.jar
- okhttp-2.0.0.jar
- httpclientandroidlib-1.2.0.jar

I'm testing it on a Nexus 5 with the new Android L and I get this error (it was not present on Android 4.4.4). How can I solve it?

``` java
06-27 16:39:48.793  13884-13884/com.surveylab.SurveyLab E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.surveylab.SurveyLab, PID: 13884
    java.lang.NoSuchMethodError: No static method source(Ljava/io/File;)Lokio/Source; in class Lokio/Okio; or its super classes (declaration of 'okio.Okio' appears in /system/framework/okhttp.jar)
            at com.squareup.okhttp.internal.DiskLruCache.readJournal(DiskLruCache.java:243)
            at com.squareup.okhttp.internal.DiskLruCache.open(DiskLruCache.java:224)
            at com.squareup.okhttp.Cache.<init>(Cache.java:146)
            at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:74)
            at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:51)
            at com.surveylab.SurveyLab.util.image.PicassoUtil.initPicasso(PicassoUtil.java:43)
            at com.surveylab.SurveyLab.global.Global.onCreate(Global.java:81)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1008)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4397)
            at android.app.ActivityThread.access$1500(ActivityThread.java:143)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5070)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:631)
```

**Comment by hao-tian** [comment]
I'm testing it on a Nexus 5 with the new Android L and I get this error (it was not present on Android 4.4.4). How can I solve it?

09-23 14:57:22.807 20992-21132/com.zhunxiner E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
Process: com.zhunxiner, PID: 20992
 java.lang.NoSuchMethodError: No static method source(Ljava/net/Socket;)Lokio/Source; in class Lokio/Okio; or its super classes (declaration of 'okio.Okio' appears in /system/framework/okhttp.jar)
                                                                   at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:191)
                                                                   at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
                                                                   at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
                                                                   at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
                                                                   at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
                                                                   at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
                                                                   at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                   at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                   at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                   at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                                   at okhttp3.RealCall.access$100(RealCall.java:33)
                                                                   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
                                                                   at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                   at java.lang.Thread.run(Thread.java:818)
