### ISSUE TITLE
Can't load images into widget's listview

### ISSUE THREAD

**Issue by ab-helly** [square/picasso#587]
I can't load images into every item of widget's ListView, it just breaks widget layout.
I use RemoteViewsFactory to handle listview population

getViewAt code: 

```
public RemoteViews getViewAt(final int position) {
    final RemoteViews remoteView = new RemoteViews(context.getPackageName(), R.layout.lockscreen_widget_list_item);
    ListItem listItem = listItemList.get(position);
    remoteView.setTextViewText(R.id.widget_listitem_headline, listItem.headline);
    remoteView.setTextViewText(R.id.widget_listitem_author, listItem.author);
    final String imageUrl = listItem.image;
    handler.post(new Runnable() {
        @Override
        public void run() {
            if (!Utils.isEmpty(imageUrl)) {
                picasso.load(imageUrl)
                        .placeholder(R.drawable.empty_photo)
                        .into(remoteView, R.id.widget_listitem_picture, new int[]{appWidgetId});
            }
        }
    });
    return remoteView;
}
```

Result without images loading:
![screenshot-01](https://cloud.githubusercontent.com/assets/320930/3602570/99078a02-0d0d-11e4-9f52-e9ea2ae0dbb6.png)

And after they are loaded:
![screenshot-02](https://cloud.githubusercontent.com/assets/320930/3602571/990edb54-0d0d-11e4-9d77-1387522ec996.png)

PS: the same happens (but only sometimes) if I inflate and add to RemoteViews the same item layout in for-loop

**Comment by dnkoutso** [comment]
Looking at this now for 2.5.

**Comment by SylvainRousson** [comment]
Still having crash using the dedicated method with v2.5.0 : 
Picasso.with(mContext).load(imgUrl).into(rv, R.id.item_picture, new int[] { mAppWidgetId });

Stack :
03-13 11:20:11.063: E/AndroidRuntime(16185): java.lang.IllegalStateException: Method call should happen from the main thread.
03-13 11:20:11.063: E/AndroidRuntime(16185): 	at com.squareup.picasso.Utils.checkMain(Utils.java:133)
03-13 11:20:11.063: E/AndroidRuntime(16185): 	at com.squareup.picasso.Picasso.cancelExistingRequest(Picasso.java:570)
03-13 11:20:11.063: E/AndroidRuntime(16185): 	at com.squareup.picasso.Picasso.enqueueAndSubmit(Picasso.java:472)
03-13 11:20:11.063: E/AndroidRuntime(16185): 	at com.squareup.picasso.RequestCreator.performRemoteViewInto(RequestCreator.java:711)
03-13 11:20:11.063: E/AndroidRuntime(16185): 	at com.squareup.picasso.RequestCreator.into(RequestCreator.java:580)
03-13 11:20:11.063: E/AndroidRuntime(16185): 	at com.myapp.appwidget.BigStoryRemoteViewsService$BigStoryRemoteViewsFactory.getViewAt(BigStoryRemoteViewsService.java:107)

The only way I found to achieve my aim is this : 
final Bitmap b = Picasso.with(mContext).load(imgUrl).get();
rv.setImageViewBitmap(R.id.item_picture, b);

Could you tell me if it is the best wordaround, and also if yo will fix it ?

**Comment by manuel-sejourne** [comment]
Any issue ?

**Comment by pristalovpavel** [comment]
Maybe now the time has come?)

**Comment by 089apps** [comment]
Same issue here, please save my life!

**Comment by aligurelli** [comment]
i have same issue too. can you please fix it?

**Comment by BackPackerDz** [comment]
Same issue !

**Comment by RabieMohimane** [comment]
i have the same issue v2.5.2

**Comment by RabieMohimane** [comment]
hi , it works , you just ensure that the files name doesn't contain any special charactere like é,à and spaces url must be encoded.(forgive my weak english)

**Comment by zub1984** [comment]
java.lang.IllegalStateException: Method call should happen from the main thread. 

does this issue is fixed? i am using Picasso library to load image from URL, and making the call of my Utils method from  public RemoteViews getViewAt(int position) { ... some code logic }

using RemoteViewFactory implements RemoteViewsService.RemoteViewsFactory.

will appreciate the feedback, meanwhile testing with Glide found no issue.

**Comment by eltray** [comment]
@zub1984 

You should use this work around solution:
```
        Handler uiHandler = new Handler(Looper.getMainLooper());
        uiHandler.post(() -> {
            Picasso.with(context)
                    .load(imageUrl)
                    .into(remoteViews, viewId, new int[]{widgetId});

        });
```

**Comment by 3zcs** [comment]
check out this answer solve this issue 
http://stackoverflow.com/a/42437729/6684402
