### ISSUE TITLE
java.lang.OutOfMemory Exception when using PicassoDrawable's placeholder

### ISSUE THREAD

**Issue by dornad** [square/picasso#623]
Hello people at Square!

First of all, great work with Picasso, Its a great library!

I'm seeing an OutOfMemoryError on a PicassoDrawable instance, used in a ListAdapter.  It seems that the error occurs when setting the placeholder resource.

The exception is (usually) thrown when I start scrolling quickly thru the list.  The crash occurs on a SGH-I545 (Samsung Galaxy S4), running Android 4.4.2.  At the moment I don't have another device with me where I can try to reproduce the crash on.

My build.gradle has the picasso dependency set to compile `com.squareup.picasso:picasso:2.3.2`

Here's the stacktrace:

```
08-20 10:47:54.157  13212-13212/org.dornad.testapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.dornad.testapp, PID: 13212
    java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:677)
            at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:507)
            at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:872)
            at android.content.res.Resources.loadDrawable(Resources.java:3024)
            at android.content.res.Resources.getDrawable(Resources.java:1586)
            at android.widget.ImageView.resolveUri(ImageView.java:648)
            at android.widget.ImageView.setImageResource(ImageView.java:377)
            at com.squareup.picasso.PicassoDrawable.setPlaceholder(PicassoDrawable.java:62)
            at com.squareup.picasso.RequestCreator.into(RequestCreator.java:520)
            at com.squareup.picasso.RequestCreator.into(RequestCreator.java:462)
            at org.dornad.testapp.ui.adapters.HitsAdapter.getView(HitsAdapter.java:47)
            at android.widget.AbsListView.obtainView(AbsListView.java:2689)
            at android.widget.ListView.makeAndAddView(ListView.java:1801)
            at android.widget.ListView.fillDown(ListView.java:697)
            at android.widget.ListView.fillGap(ListView.java:661)
            at android.widget.AbsListView.trackMotionScroll(AbsListView.java:6660)
            at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:5665)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
            at android.view.Choreographer.doCallbacks(Choreographer.java:603)
            at android.view.Choreographer.doFrame(Choreographer.java:572)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)
```

I'll start posting here the relevant code from my Android App:

First the ArrayAdapter subclass:

```java
package org.dornad.testapp.ui.adapters;

import android.content.Context;
import android.support.v4.app.ListFragment;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import butterknife.ButterKnife;
import butterknife.InjectView;
import org.dornad.testapp.R;
import org.dornad.testapp.models.User;
import org.dornad.testapp.ui.utils.Utils;
import com.squareup.picasso.Picasso;

import java.util.List;

/**
 * Created by dornad (daniel@danielrodriguez.name) on 2/6/14.
 */
public class HitsAdapter extends ArrayAdapter<User> {

    public HitsAdapter(ListFragment fragment, Context context, int resource, List<User> objects) {
        super(fragment, context, resource, objects);
    }

    @Override
    public View getView(final int position, View convertView, ViewGroup parent) {
        HitsHolder holder;

        if (convertView != null) {
            holder = (HitsHolder) convertView.getTag();
        } else {
            convertView = getLayoutInflater().inflate(layoutResourceId, parent, false);
            holder = new HitsHolder(convertView);
            convertView.setTag(holder);
        }

        User user = getItem(position);

        holder.countView.setText(String.valueOf(position+1));
        holder.usernameView.setText(user.getUsername());
        holder.ageView.setText( String.valueOf(user.getAge()));
        holder.locationView.setText( user.getLocation() );

        // OutOfMemory Exception seems to happen here (see stacktrace)
        Picasso.with(context).load(user.getCoverPicURL()).placeholder( Utils.randomCat() ).fit().into(holder.profileView);
        Picasso.with(context).load(user.getPictureURL()).placeholder( R.drawable.user_default ).fit().into(holder.userPic);

        return convertView;
    }

    static class HitsHolder {
        @InjectView(R.id.count) TextView countView;
        @InjectView(R.id.hits_item_content_iv) ImageView profileView;
        TextView usernameView;
        TextView ageView;
        TextView locationView;
        ImageView userPic;

        public HitsHolder(View convertView) {
            ButterKnife.inject(this, convertView);
            View userPanel = convertView.findViewById(R.id.user_panel);
            usernameView = ButterKnife.findById(userPanel, R.id.username);
            ageView = ButterKnife.findById(userPanel, R.id.age);
            locationView = ButterKnife.findById(userPanel, R.id.user_place);
            userPic = ButterKnife.findById(userPanel, R.id.userpanel_user_pic);
        }
    }
}
```
And the  XML Layout for the Adapter:

```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:descendantFocusability="blocksDescendants"
        android:padding="10dp">

  <LinearLayout
          android:orientation="vertical"
          android:layout_width="match_parent"
          android:layout_height="wrap_content">

    <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/hits_userpanel">

      <TextView
              android:id="@+id/count"
              style="@style/HitsCount"
              android:focusable="true"
              android:clickable="false"
              android:layout_alignTop="@+id/user_panel"
              android:layout_alignBottom="@+id/user_panel"
              android:text="@string/test_number"/>

      <include
              android:id="@+id/user_panel"
              layout="@layout/user_info_panel"
              android:layout_width="match_parent"
              android:layout_height="wrap_content"
              android:layout_toRightOf="@+id/count"/>
    </RelativeLayout>

    <RelativeLayout
            android:layout_height="wrap_content"
            android:layout_width="match_parent">

      <ImageView
          android:focusable="false"
          android:clickable="false"
              android:id="@+id/hits_item_content_iv"
              android:layout_width="match_parent"
              android:layout_height="wrap_content"
              android:src="@drawable/ic_purplecat"
              android:scaleType="fitXY"
              android:adjustViewBounds="true"
              android:layout_alignParentTop="true"
              android:layout_alignParentLeft="true"
              android:contentDescription="@null"/>

      <ImageView
              android:id="@+id/hits_item_start_singing"
          android:focusable="true"
          android:clickable="false"
              android:layout_width="wrap_content"
              android:layout_height="wrap_content"
              android:background="@null"
              android:src="@drawable/hits_btn_play"
              android:layout_centerVertical="true"
              android:layout_centerHorizontal="true"
              android:contentDescription="@string/play"/>
    </RelativeLayout>
  </LinearLayout>
</FrameLayout>
```

Here's the implementation for Utils.randomCat :

```java
public static int randomCat() {
        int[] cats = new int[]{R.drawable.ic_greencat,
                               R.drawable.ic_orangecat,
                               R.drawable.ic_purplecat,
                               R.drawable.ic_redcat};
        int rand = new Random().nextInt(3);
        return cats[rand];
    }
```

Any ideas?  Thank you for your help!

**Comment by confile** [comment]
How do you know the placeholder color?
