### ISSUE TITLE
Getting out of memory error when display image with Picasso 2.3.4

### ISSUE THREAD

**Issue by cycorax12** [square/picasso#751]
When i am trying to display image from url with Picasso getting following exception:

```java
java.lang.OutOfMemoryError: pthread_create (stack size 16384 bytes) failed: Try again
       at java.lang.VMThread.create(VMThread.java)
       at java.lang.Thread.start(Thread.java:1029)
       at com.squareup.picasso.Dispatcher.(Dispatcher.java:93)
       at com.squareup.picasso.Picasso$Builder.build(Picasso.java:619)
       at com.squareup.picasso.Picasso.with(Picasso.java:482)
       at com.wallie.utils.ImageManagerUtils.displayImageWithPicassoSpinner1(ImageManagerUtils.java:95)
       at com.wallie.fragments.FullScreenFragment.initialiseComponents(FullScreenFragment.java:209)
       at com.wallie.fragments.FullScreenFragment.onViewCreated(FullScreenFragment.java:145)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:952)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1115)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1097)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1895)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:566)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1177)
       at android.app.Activity.performStart(Activity.java:5461)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2453)
       at android.app.ActivityThread.access$900(ActivityThread.java:173)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5579)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by dnkoutso** [comment]
See this for diff. https://github.com/square/picasso/releases I am closing this for now.
