### ISSUE TITLE
com.squareup.picasso.Downloader$ResponseException: 504 Unsatisfiable Request (only-if-cached)

### ISSUE THREAD

**Issue by roms** [square/picasso#788]
Already saw a similar issue, #656, but this is different as the url contains no character encoding problems. Rather I think it has something to do with the image itself.

I get 

com.squareup.picasso.Downloader$ResponseException: 504 Unsatisfiable Request (only-if-cached)
            at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:108)
            at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:49)
            at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:153)
            at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:111)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
            at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:408)

for both of the following urls,
https://breezeworks-production.s3.amazonaws.com/notes/73084c1c10db7ae7bedd5e4a9a7a1e97/8050b8e6d52cb4f33edea2f5a3b383f2/31f38e24bc52b4195edc8ba033b7b22f.png 
and
 https://breezeworks-production.s3.amazonaws.com/notes/73084c1c10db7ae7bedd5e4a9a7a1e97/f208e4478f43dbad260ac590eeda1a52/c86d862f60372958b2f69e77259898bc.png

While these are two different urls, they both point to the same picture taken with a Moto X (2013) and uploaded to Amazon S3. As far as I can tell, there are no character encoding issues in the url, so I don't think the url is the problem.

**Comment by omer-entertainer** [comment]
I have noticed that this issue randomly also occurs using latest picasso library (com.squareup.picasso:picasso:2.71828) if testing device date is not correct or selected the future date.

Strange but i have reproduced this and wasted ample of time.

com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 504
        at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:51)
        at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
        at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)

**Comment by developer--** [comment]
same problem, I had a internet connection but 
```
com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 504
    at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:51)
    at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
    at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
    at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)
```

**Comment by gorkemkara** [comment]
same have problem
`E/PICASSO: com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 504`
