### ISSUE TITLE
Resource Leak detected by StrictMode

### ISSUE THREAD

**Issue by simpleton** [square/picasso#824]
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

``` java
    java.lang.Throwable: Explicit termination method 'close' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
            at java.io.FileInputStream.<init>(FileInputStream.java:80)
            at com.squareup.okhttp.internal.DiskLruCache.get(DiskLruCache.java:417)
            at com.squareup.okhttp.Cache.get(Cache.java:158)
            at com.squareup.okhttp.Cache$1.get(Cache.java:117)
            at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:221)
            at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:420)
            at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:371)
            at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:466)
            at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:105)
            at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:49)
            at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:153)
            at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:111)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
            at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:408)
```

**Comment by simpleton** [comment]
@JakeWharton Thanks for u replay.
Here is the version I am using:
```
compile 'com.squareup.okhttp:okhttp:2.0.0'
compile 'com.squareup.okhttp:okhttp-urlconnection:2.0.0'
compile 'com.squareup.picasso:picasso:2.4.0'
```
I load image in RecycleView's onBindViewHolder:
```
        @Override
        public void onBindViewHolder(ProductHolder holder, int position) {

            final Product product = list.get(position);

            Picasso.with(getActivity())
                    .load(product.data.getThumbnail())
                    .fit()
                    .into(holder.imageView);
```
BTW, the Picasso works fine when internet connecting well. But if the connection is slow, it always display this error info.
You can recur this error when you turn on the airplan mode.

**Comment by JakeWharton** [comment]
Can you try version 2.2.0 of OkHttp?

**Comment by simpleton** [comment]
okay.

**Comment by simpleton** [comment]
same issue with different log:
```
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
            at java.io.FileInputStream.<init>(FileInputStream.java:80)
            at okio.Okio.source(Okio.java:160)
            at com.squareup.okhttp.internal.DiskLruCache$Entry.snapshot(DiskLruCache.java:1038)
            at com.squareup.okhttp.internal.DiskLruCache.get(DiskLruCache.java:418)
            at com.squareup.okhttp.Cache.get(Cache.java:155)
            at com.squareup.okhttp.Cache$1.get(Cache.java:114)
            at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:216)
            at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:425)
            at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:376)
            at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:471)
            at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:105)
            at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:49)
            at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:153)
            at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:111)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
            at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:408)
```

**Comment by JakeWharton** [comment]
Thanks. I'll have a look soon.

**Comment by dnkoutso** [comment]
Can you provide some more steps to repro this? Perhaps a sample app? I cant replicate it locally...

**Comment by simpleton** [comment]
@dnkoutso have sent you through gmail.

**Comment by dnkoutso** [comment]
Thank you @simpleton will take care of this.

**Comment by dnkoutso** [comment]
@simpleton 
```
E/StrictMode(26277): java.lang.Throwable: Explicit termination method 'release' not called
E/StrictMode(26277): 	at dalvik.system.CloseGuard.open(CloseGuard.java:184)
E/StrictMode(26277): 	at android.view.Surface.<init>(Surface.java:290)
E/StrictMode(26277): 	at android.view.SurfaceView.<init>(SurfaceView.java:96)
E/StrictMode(26277): 	at android.opengl.GLSurfaceView.<init>(GLSurfaceView.java:213)
E/StrictMode(26277): 	at com.baidu.platform.comapi.map.f.<init>(Unknown Source)```

This does not appear to be related to Picasso?

**Comment by dnkoutso** [comment]
Nevermind I think its a different issue. Looking further into this.

**Comment by dnkoutso** [comment]
Cant seem to reproduce on HTC One Mini:

These were your instructions:
Replicated way:
1. open the debug version app.
2. see the product list and then turn on the aeroplane mode
3. scroll the list
4. the app shut down by strict mode.

**Comment by ened** [comment]
Here is another case, maybe needs to be reported to okhttp?

```
04-14 07:52:58.210    3485-3494/de.audi.rse3 E/StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
            at java.io.FileInputStream.<init>(FileInputStream.java:80)
            at com.android.okhttp.internal.DiskLruCache.get(DiskLruCache.java:418)
            at com.android.okhttp.HttpResponseCache.get(HttpResponseCache.java:207)
            at com.android.okhttp.HttpResponseCache$1.get(HttpResponseCache.java:149)
            at com.android.okhttp.internal.http.HttpEngine.initResponseSource(HttpEngine.java:224)
            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:185)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
            at com.squareup.picasso.UrlConnectionDownloader.load(UrlConnectionDownloader.java:64)
            at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:49)
            at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:153)
            at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:111)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
            at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:408)
```

**Comment by TreyWalker** [comment]
Here is another case. `Picasso 2.5.2`
```
05-24 16:51:17.830  16477-16488/com.imaygou.android E/StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
            at java.io.FileInputStream.<init>(FileInputStream.java:80)
            at com.android.okhttp.internal.DiskLruCache.get(DiskLruCache.java:418)
            at com.android.okhttp.HttpResponseCache.get(HttpResponseCache.java:207)
            at com.android.okhttp.HttpResponseCache$1.get(HttpResponseCache.java:149)
            at com.android.okhttp.internal.http.HttpEngine.initResponseSource(HttpEngine.java:224)
            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:185)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
            at com.squareup.picasso.UrlConnectionDownloader.load(UrlConnectionDownloader.java:93)
            at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
            at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
            at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
            at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```

**Comment by Manabu-GT** [comment]
@TreyCai I have the same error with Picasso 2.5.2.
In my case, it occurs when I do something like below inside my ListView adapter's getView() call; then I enter the activity screen which contains the listview with the airplane mode on.

```java
   // inside getView() call
   Picasso.with(context)
                .load(accountLink.getAppDetail().getIconUrl().getLarge())
                .fit()
                .into(holder.appIcon);
```

**Comment by ixsans** [comment]
Hi all, I also have the same error when loading image using Picasso. This is my picasso and okhttp.
` 'com.squareup.okhttp:okhttp:2.4.0'
compile 'com.squareup.okhttp:okhttp-urlconnection:2.2.0'
compile 'com.squareup.picasso:picasso:2.4.0' `

And this is my code:

`Picasso.with(context)
                .load(imageUrl)
                .placeholder(R.drawable.default_Image)
                .error(R.drawable.default_image)
                .fit()
                .centerCrop()
                .into(imageView); 1

This error happen olny when I activated Strict mode on my application.

` StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
                    .detectDiskReads()
                    .detectDiskWrites()
                    .detectNetwork()   // or .detectAll() for all detectable problems
                    .penaltyLog()
                    .build());
            StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                    .detectLeakedSqlLiteObjects()
                    .detectLeakedClosableObjects()
                    .penaltyLog()
                    .penaltyDeath()
                    .build()); `

**Comment by Amosiper** [comment]
is this bug fixed?

**Comment by DavidEdwards** [comment]
This issue still exists.

It happens for me in a long-ish RecyclerView list of images. When scrolling *very* quickly down the list (and sometimes requiring me to quickly scroll back up again) it will crash. This is 100% reproducible for me. 

```
StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
 java.lang.Throwable: Explicit termination method 'close' not called
	 at dalvik.system.CloseGuard.open(CloseGuard.java:180)
	 at java.io.FileInputStream.<init>(FileInputStream.java:78)
	 at com.android.okhttp.okio.Okio.source(Okio.java:159)
	 at com.android.okhttp.internal.io.FileSystem$1.source(FileSystem.java:44)
	 at com.android.okhttp.internal.DiskLruCache$Entry.snapshot(DiskLruCache.java:1002)
	 at com.android.okhttp.internal.DiskLruCache.get(DiskLruCache.java:430)
	 at com.android.okhttp.Cache.get(Cache.java:180)
	 at com.android.okhttp.Cache$1.get(Cache.java:139)
	 at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:229)
	 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
	 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
	 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
	 at com.squareup.picasso.UrlConnectionDownloader.load(SourceFile:93)
	 at com.squareup.picasso.NetworkRequestHandler.load(SourceFile:47)
	 at com.squareup.picasso.BitmapHunter.hunt(SourceFile:206)
	 at com.squareup.picasso.BitmapHunter.run(SourceFile:159)
	 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
	 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	 at java.lang.Thread.run(Thread.java:818)
	 at com.squareup.picasso.Utils$PicassoThread.run(SourceFile:411)
trictmode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks. java.lang.Throwable: Explicit termination method 'close' not called at dalvik.system.CloseGuard.open(CloseGuard.java:180) at java.io.FileInputStream.<init>(FileInputStream.java:78) at com.android.okhttp.okio.Okio.source(Okio.java:159) at com.android.okhttp.internal.io.FileSystem$1.source(FileSystem.java:44) at com.android.okhttp.internal.DiskLruCache$Entry.snapshot(DiskLruCache.java:1002) at com.android.okhttp.internal.DiskLruCache.get(DiskLruCache.java:430) at com.android.okhttp.Cache.get(Cache.java:180) at com.android.okhttp.Cache$1.get(Cache.java:139) at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:229) at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437) at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388) at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501) at com.squareup.picasso.UrlConnectionDownloader.load(SourceFile:93) at com.squareup.picasso.NetworkRequestHandler.load(SourceFile:47) at com.squareup.picasso.BitmapHunter.hunt(SourceFile:206) at com.squareup.picasso.BitmapHunter.run(SourceFile:159) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) at java.util.concurrent.FutureTask.run(FutureTask.java:237) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) at java.lang.Thread.run(Thread.java:818) at com.squareup.picasso.Utils$PicassoThread.run(SourceFile:411)
```

**Comment by JakeWharton** [comment]
This was a bug in OkHttp that has been fixed in 3.x.

**Comment by AbhilashJain** [comment]
Is this fixed?
I am using 
compile 'com.squareup.picasso:picasso:2.5.2'
compile 'com.squareup.okhttp3:okhttp:3.2.0'

This happens when internet is slow and when listview is scrolled quickly.
