### ISSUE TITLE
Picasso crashes with 85% memory free?

### ISSUE THREAD

**Issue by oliverhausler** [square/picasso#832]
I wanted to bring this stacktrace to your attention. I had "Forcing collection of SoftReferences for 1379416-byte allocation" about 10-20 times consecutively, with the same byte count every time. To me it looks like Picasso tried loading an image with a specific size in a loop and could not fit it into memory. Finally the app crashed.

At the crash, I had 85% of app memory available, 1,000 times the amount Picasso tried to allocate!?

Short before, I ran a memory profiling test and forced the app to be extremely busy so not many GCs were performed and memory was up to the limit of 64MB. Is it possible that Picasso tried to allocate memory while the app was close to the limit, and consecutive attempts to allocate the same resource for whatever reason failed as well, even though memory became available in the meantime?
```
01-04 21:02:49.434  29485-29485/cc.closeup D/dalvikvm﹕ GC_EXPLICIT freed 2K, 85% free 10274K/65536K, paused 4ms+6ms, total 41ms
01-04 21:02:49.454  29485-29485/cc.closeup D/dalvikvm﹕ GC_FOR_ALLOC freed <1K, 85% free 10273K/65536K, paused 28ms, total 28ms
01-04 21:02:49.454  29485-29485/cc.closeup I/dalvikvm-heap﹕ Forcing collection of SoftReferences for 1379416-byte allocation
01-04 21:02:49.494  29485-29485/cc.closeup D/dalvikvm﹕ GC_BEFORE_OOM freed 0K, 85% free 10273K/65536K, paused 35ms, total 35ms
01-04 21:02:49.494  29485-29485/cc.closeup E/dalvikvm-heap﹕ Out of memory on a 1379416-byte allocation.
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ "main" prio=5 tid=1 RUNNABLE
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ | group="main" sCount=0 dsCount=0 obj=0x40da79a0 self=0x61ef9010
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ | sysTid=29485 nice=0 sched=0/0 cgrp=apps handle=1075143644
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ | state=R schedstat=( 113054191134 15151846125 103214 ) utm=10695 stm=610 core=0
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:505)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:355)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:785)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at android.content.res.Resources.loadDrawable(Resources.java:2030)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at android.content.res.Resources.loadDrawable(Resources.java:1929)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at android.content.res.Resources.getDrawable(Resources.java:661)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at android.widget.ImageView.resolveUri(ImageView.java:616)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at android.widget.ImageView.setImageResource(ImageView.java:349)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at com.squareup.picasso.ImageViewAction.error(ImageViewAction.java:60)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at com.squareup.picasso.Picasso.deliverAction(Picasso.java:516)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at com.squareup.picasso.Picasso.complete(Picasso.java:463)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:115)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at android.os.Handler.dispatchMessage(Handler.java:99)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at android.os.Looper.loop(Looper.java:137)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at android.app.ActivityThread.main(ActivityThread.java:5041)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at java.lang.reflect.Method.invokeNative(Native Method)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at java.lang.reflect.Method.invoke(Method.java:511)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ at dalvik.system.NativeStart.main(Native Method)
01-04 21:02:49.494  29485-29485/cc.closeup I/dalvikvm﹕ [ 01-04 21:02:49.494 29485:29485 D/skia     ]
    --- decoder->decode returned false
01-04 21:02:49.534  29485-29485/cc.closeup D/dalvikvm﹕ GC_EXPLICIT freed <1K, 85% free 10273K/65536K, paused 4ms+6ms, total 40ms
01-04 21:02:49.564  29485-29485/cc.closeup D/dalvikvm﹕ GC_FOR_ALLOC freed <1K, 85% free 10273K/65536K, paused 28ms, total 28ms
01-04 21:02:49.564  29485-29485/cc.closeup I/dalvikvm-heap﹕ Forcing collection of SoftReferences for 1379416-byte allocation
01-04 21:02:49.594  29485-29485/cc.closeup D/dalvikvm﹕ GC_BEFORE_OOM freed 0K, 85% free 10273K/65536K, paused 34ms, total 34ms
01-04 21:02:49.594  29485-29485/cc.closeup E/dalvikvm-heap﹕ Out of memory on a 1379416-byte allocation.
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ "main" prio=5 tid=1 RUNNABLE
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ | group="main" sCount=0 dsCount=0 obj=0x40da79a0 self=0x61ef9010
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ | sysTid=29485 nice=0 sched=0/0 cgrp=apps handle=1075143644
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ | state=R schedstat=( 113147591259 15153465000 103243 ) utm=10704 stm=610 core=0
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:505)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:355)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:785)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at android.content.res.Resources.loadDrawable(Resources.java:2030)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at android.content.res.Resources.loadDrawable(Resources.java:1929)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at android.content.res.Resources.getDrawable(Resources.java:661)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at android.widget.ImageView.resolveUri(ImageView.java:616)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at android.widget.ImageView.setImageResource(ImageView.java:349)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at com.squareup.picasso.ImageViewAction.error(ImageViewAction.java:60)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at com.squareup.picasso.Picasso.deliverAction(Picasso.java:516)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at com.squareup.picasso.Picasso.complete(Picasso.java:463)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:115)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at android.os.Handler.dispatchMessage(Handler.java:99)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at android.os.Looper.loop(Looper.java:137)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at android.app.ActivityThread.main(ActivityThread.java:5041)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at java.lang.reflect.Method.invokeNative(Native Method)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at java.lang.reflect.Method.invoke(Method.java:511)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ at dalvik.system.NativeStart.main(Native Method)
01-04 21:02:49.594  29485-29485/cc.closeup I/dalvikvm﹕ [ 01-04 21:02:49.594 29485:29485 D/skia     ]
    --- decoder->decode returned false
01-04 21:02:49.634  29485-29485/cc.closeup D/dalvikvm﹕ GC_EXPLICIT freed <1K, 85% free 10273K/65536K, paused 3ms+6ms, total 39ms
01-04 21:02:49.634  29485-29485/cc.closeup D/AndroidRuntime﹕ Shutting down VM
01-04 21:02:49.634  29485-29485/cc.closeup W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x40da6930)
01-04 21:02:49.644  29485-29485/cc.closeup E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:505)
            at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:355)
            at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:785)
            at android.content.res.Resources.loadDrawable(Resources.java:2030)
            at android.content.res.Resources.loadDrawable(Resources.java:1929)
            at android.content.res.Resources.getDrawable(Resources.java:661)
            at android.widget.ImageView.resolveUri(ImageView.java:616)
            at android.widget.ImageView.setImageResource(ImageView.java:349)
            at com.squareup.picasso.ImageViewAction.error(ImageViewAction.java:60)
            at com.squareup.picasso.Picasso.deliverAction(Picasso.java:516)
            at com.squareup.picasso.Picasso.complete(Picasso.java:463)
            at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:115)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by oliverhausler** [comment]
![memory](https://cloud.githubusercontent.com/assets/8090341/5609548/f5ac8128-9457-11e4-82e8-15bd5aa516c8.PNG)

**Comment by JakeWharton** [comment]
This is unrelated to Picasso. If you look closer at the stack trace you'll see the Picasso is simply calling `setImageResource` with the error ID that you passed in. The OOM triggers while the framework is trying to load that image.

Since the OOM happens when it native code perhaps there's no available memory off-heap (rather than on-heap which you pointed out is mostly free).

I don't think there's any action to take here.

**Comment by oliverhausler** [comment]
Yes, I saw that. I just wanted to bring this to your attention because I noticed that Picasso seemed to work around that issue by retrying several times.

**Comment by JakeWharton** [comment]
The retry is on I/O problems loading the original image URL. Setting the error image only occurs once that has been abandoned.

**Comment by oliverhausler** [comment]
Thanks Jake, this helps. Have a good night!

**Comment by JakeWharton** [comment]
There's a similar report at https://github.com/square/picasso/issues/623 except this happens when setting the placeholder drawable.

**Comment by oliverhausler** [comment]
#623 "when I start scrolling quickly thru the list" looks similar to what I did: While I had an image gallery with about 50 images open, I turned my device back and forth quickly in order to interrupt image loading on purpose and defeat GC. This is how I can trigger the OOM, and it happens every time I do that.

**Comment by oliverhausler** [comment]
BTW: Interestingly it does not happen immediately when I reach the 64MB limit, but the device gets into a situation where it happens 10-20 seconds later.

**Comment by dnkoutso** [comment]
Use `tag()` to slowly load requests only when scrolling has stopped. Sample app has a sample about this.

Do you have URLs fo the bitmaps you load? Are you using `fit()`? You might be loading too much concurrently and thats why this occurs.

**Comment by oliverhausler** [comment]
@dnkoutso can be closed. I figured out with Jeff that the problem is in Android and we can't do much about it.

**Comment by dnkoutso** [comment]
Thanks man!
