### ISSUE TITLE
ClassCastException when setting custom Executor

### ISSUE THREAD

**Issue by stabib** [square/picasso#839]
I'm building a singleton Picasso instance in my application class as such:

```java
Picasso.Builder builder = new Picasso.Builder(this)
                                         .executor(new ThreadPoolExecutor(
                                                        Constants.NUM_PICASSO_THREADS,
                                                        Constants.NUM_PICASSO_THREADS,
                                                        0, TimeUnit.MILLISECONDS,
                                                        new PriorityBlockingQueue<Runnable>(),
                                                        Executors.defaultThreadFactory()));
Picasso.setSingletonInstance(builder.build());
```

Soon after I use the instance, I get this crash:
```java
01-07 17:19:16.075: E/AndroidRuntime(23719): FATAL EXCEPTION: Picasso-Dispatcher
01-07 17:19:16.075: E/AndroidRuntime(23719): java.lang.ClassCastException: java.util.concurrent.FutureTask cannot be cast to java.lang.Comparable
01-07 17:19:16.075: E/AndroidRuntime(23719): 	at java.util.concurrent.PriorityBlockingQueue.siftUpComparable(PriorityBlockingQueue.java:317)
01-07 17:19:16.075: E/AndroidRuntime(23719): 	at java.util.concurrent.PriorityBlockingQueue.offer(PriorityBlockingQueue.java:445)
01-07 17:19:16.075: E/AndroidRuntime(23719): 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1295)
01-07 17:19:16.075: E/AndroidRuntime(23719): 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:81)
01-07 17:19:16.075: E/AndroidRuntime(23719): 	at com.squareup.picasso.Dispatcher.performSubmit(Dispatcher.java:200)
01-07 17:19:16.075: E/AndroidRuntime(23719): 	at com.squareup.picasso.Dispatcher.performSubmit(Dispatcher.java:173)
01-07 17:19:16.075: E/AndroidRuntime(23719): 	at com.squareup.picasso.Dispatcher$DispatcherHandler.handleMessage(Dispatcher.java:476)
01-07 17:19:16.075: E/AndroidRuntime(23719): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-07 17:19:16.075: E/AndroidRuntime(23719): 	at android.os.Looper.loop(Looper.java:137)
01-07 17:19:16.075: E/AndroidRuntime(23719): 	at android.os.HandlerThread.run(HandlerThread.java:60)
```

When I use a ```ScheduledThreadPoolExecutor ```, the library does NOT crash.

I'm using Picasso 2.4.0.

**Comment by JakeWharton** [comment]
Per `PriorityBlockingQueue`'s docs:

> A priority queue relying on natural ordering also does not permit insertion of non-comparable objects (doing so results in ClassCastException).

Either pass in a custom `Comparable` or use a normal `LinkedBlockingQueue`.
