### ISSUE TITLE
Picasso 2.4 and OkHttp 2.2:  Picasso detected an unsupported OkHttp on the classpath

### ISSUE THREAD

**Issue by nizlumina** [square/picasso#850]
Reproducible in a new project API14+ using the latest stable release of AS and build tools.
Method used:

`Picasso.with(getApplicationContext()).load(Uri.parse(url)).fit().into(imageView);`

Dependencies:
        compile 'com.squareup.picasso:picasso:2.4.0'
        compile 'com.squareup.okhttp:okhttp:2.2.0'

The image is just a generic image from the web.

Error logs:

    01-15 14:06:39.000    1190-1190/nizlumina.com.myapplication E/AndroidRuntime﹕ FATAL EXCEPTION: main
        java.lang.RuntimeException: Picasso detected an unsupported OkHttp on the classpath.
        To use OkHttp with this version of Picasso, you'll need:
        1. com.squareup.okhttp:okhttp:1.6.0 (or newer)
        2. com.squareup.okhttp:okhttp-urlconnection:1.6.0 (or newer)
        Note that OkHttp 2.0.0+ is supported!
                at com.squareup.picasso.Utils.createDefaultDownloader(Utils.java:251)
                at com.squareup.picasso.Picasso$Builder.build(Picasso.java:754)
                at com.squareup.picasso.Picasso.with(Picasso.java:597)
                at nizlumina.com.myapplication.MainActivity$1.onClick(MainActivity.java:30)
                at android.view.View.performClick(View.java:4084)
                at android.view.View$PerformClick.run(View.java:16966)
                at android.os.Handler.handleCallback(Handler.java:615)
                at android.os.Handler.dispatchMessage(Handler.java:92)
                at android.os.Looper.loop(Looper.java:137)
                at android.app.ActivityThread.main(ActivityThread.java:4745)
                at java.lang.reflect.Method.invokeNative(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:511)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                at dalvik.system.NativeStart.main(Native Method)

Upon a closer look into
`com.squareup.picasso.Utils.createDefaultDownloader`

I'm seeing that OkUrlFactory is not available yet in the current 2.2 version of OkHTTP.

Do I need to follow the dependencies as mentioned in the log or in case of duplicate issues (I'd searched), mind referring to the version of OkHttp/Picasso that address this earlier?

Thanks.

**Comment by JakeWharton** [comment]
Per the exception, you need a dependency on `okhttp-urlconnection` as well as `okhttp`.

**Comment by nizlumina** [comment]
Was a bit wondering earlier since I've saw the same class in OkHttp repo hence the question. I'll follow your recommendation then. Thanks for the swift reply.

**Comment by JakeWharton** [comment]
This requirement is disappearing in Picasso 2.5 which will see a release in a week or two.

**Comment by AungPyae** [comment]
Error:Execution failed for task ':tVBuddy:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/squareup/okhttp/Address.class

Failed the build with above exception. 
Both okhttp & okhttp-urlconnection has been added in dependency to use Picasso 2.4.0.

Enabled the multiDex because of method counts exceeding the limit.
multiDexEnabled true.

Seen this bug report in Android Issue Tracker.
https://code.google.com/p/android/issues/detail?id=81804
But, no solution.

Any workaround ?

Thanks.

**Comment by mansukhgagal** [comment]
Must use both okhttp and okhttp-urlconnection, until OkHttp 2.0 final is out.

see answer here.. http://stackoverflow.com/a/32091981/4395114
