### ISSUE TITLE
StrictMode policy violation.

### ISSUE THREAD

**Issue by Wolftein** [square/picasso#861]
I'm getting warns when activating StrictMode.
```
01-28 13:49:56.190: D/StrictMode(12035): StrictMode policy violation; ~duration=48 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
01-28 13:49:56.190: D/StrictMode(12035): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1135)
01-28 13:49:56.190: D/StrictMode(12035): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:106)
01-28 13:49:56.190: D/StrictMode(12035): 	at libcore.io.IoBridge.open(IoBridge.java:393)
01-28 13:49:56.190: D/StrictMode(12035): 	at java.io.FileInputStream.<init>(FileInputStream.java:78)
01-28 13:49:56.190: D/StrictMode(12035): 	at okio.Okio.source(Okio.java:160)
01-28 13:49:56.190: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.readJournal(DiskLruCache.java:249)
01-28 13:49:56.190: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.initialize(DiskLruCache.java:207)
01-28 13:49:56.190: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.open(DiskLruCache.java:244)
01-28 13:49:56.190: D/StrictMode(12035): 	at com.squareup.okhttp.Cache.<init>(Cache.java:143)
01-28 13:49:56.190: D/StrictMode(12035): 	at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:74)
01-28 13:49:56.190: D/StrictMode(12035): 	at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:61)
01-28 13:49:56.190: D/StrictMode(12035): 	at me.siegenthaler.utone.sp.main.application.SimpleApplication.initImageService(SimpleApplication.java:153)
01-28 13:49:56.190: D/StrictMode(12035): 	at me.siegenthaler.utone.sp.main.application.SimpleApplication.onCreate(SimpleApplication.java:59)
01-28 13:49:56.190: D/StrictMode(12035): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
01-28 13:49:56.190: D/StrictMode(12035): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4467)
01-28 13:49:56.190: D/StrictMode(12035): 	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
01-28 13:49:56.190: D/StrictMode(12035): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
01-28 13:49:56.190: D/StrictMode(12035): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-28 13:49:56.190: D/StrictMode(12035): 	at android.os.Looper.loop(Looper.java:136)
01-28 13:49:56.190: D/StrictMode(12035): 	at android.app.ActivityThread.main(ActivityThread.java:5140)
01-28 13:49:56.190: D/StrictMode(12035): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-28 13:49:56.190: D/StrictMode(12035): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-28 13:49:56.190: D/StrictMode(12035): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
01-28 13:49:56.190: D/StrictMode(12035): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
01-28 13:49:56.190: D/StrictMode(12035): 	at dalvik.system.NativeStart.main(Native Method)
01-28 13:49:56.190: D/StrictMode(12035): StrictMode policy violation; ~duration=43 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
01-28 13:49:56.190: D/StrictMode(12035): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1135)
01-28 13:49:56.190: D/StrictMode(12035): 	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:148)
01-28 13:49:56.190: D/StrictMode(12035): 	at libcore.io.IoBridge.read(IoBridge.java:425)
01-28 13:49:56.190: D/StrictMode(12035): 	at java.io.FileInputStream.read(FileInputStream.java:179)
01-28 13:49:56.190: D/StrictMode(12035): 	at okio.Okio$2.read(Okio.java:136)
01-28 13:49:56.190: D/StrictMode(12035): 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:255)
01-28 13:49:56.190: D/StrictMode(12035): 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:249)
01-28 13:49:56.190: D/StrictMode(12035): 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
01-28 13:49:56.190: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.readJournal(DiskLruCache.java:251)
01-28 13:49:56.190: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.initialize(DiskLruCache.java:207)
01-28 13:49:56.190: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.open(DiskLruCache.java:244)
01-28 13:49:56.190: D/StrictMode(12035): 	at com.squareup.okhttp.Cache.<init>(Cache.java:143)
01-28 13:49:56.190: D/StrictMode(12035): 	at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:74)
01-28 13:49:56.190: D/StrictMode(12035): 	at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:61)
01-28 13:49:56.190: D/StrictMode(12035): 	at me.siegenthaler.utone.sp.main.application.SimpleApplication.initImageService(SimpleApplication.java:153)
01-28 13:49:56.190: D/StrictMode(12035): 	at me.siegenthaler.utone.sp.main.application.SimpleApplication.onCreate(SimpleApplication.java:59)
01-28 13:49:56.190: D/StrictMode(12035): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
01-28 13:49:56.190: D/StrictMode(12035): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4467)
01-28 13:49:56.190: D/StrictMode(12035): 	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
01-28 13:49:56.190: D/StrictMode(12035): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
01-28 13:49:56.190: D/StrictMode(12035): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-28 13:49:56.190: D/StrictMode(12035): 	at android.os.Looper.loop(Looper.java:136)
01-28 13:49:56.190: D/StrictMode(12035): 	at android.app.ActivityThread.main(ActivityThread.java:5140)
01-28 13:49:56.190: D/StrictMode(12035): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-28 13:49:56.190: D/StrictMode(12035): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-28 13:49:56.190: D/StrictMode(12035): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
01-28 13:49:56.190: D/StrictMode(12035): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
01-28 13:49:56.190: D/StrictMode(12035): 	at dalvik.system.NativeStart.main(Native Method)
01-28 13:49:56.200: D/StrictMode(12035): StrictMode policy violation; ~duration=33 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
01-28 13:49:56.200: D/StrictMode(12035): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1135)
01-28 13:49:56.200: D/StrictMode(12035): 	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:148)
01-28 13:49:56.200: D/StrictMode(12035): 	at libcore.io.IoBridge.read(IoBridge.java:425)
01-28 13:49:56.200: D/StrictMode(12035): 	at java.io.FileInputStream.read(FileInputStream.java:179)
01-28 13:49:56.200: D/StrictMode(12035): 	at okio.Okio$2.read(Okio.java:136)
01-28 13:49:56.200: D/StrictMode(12035): 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:260)
01-28 13:49:56.200: D/StrictMode(12035): 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:249)
01-28 13:49:56.200: D/StrictMode(12035): 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.readJournal(DiskLruCache.java:268)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.initialize(DiskLruCache.java:207)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.open(DiskLruCache.java:244)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.okhttp.Cache.<init>(Cache.java:143)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:74)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:61)
01-28 13:49:56.200: D/StrictMode(12035): 	at me.siegenthaler.utone.sp.main.application.SimpleApplication.initImageService(SimpleApplication.java:153)
01-28 13:49:56.200: D/StrictMode(12035): 	at me.siegenthaler.utone.sp.main.application.SimpleApplication.onCreate(SimpleApplication.java:59)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4467)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.os.Looper.loop(Looper.java:136)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.ActivityThread.main(ActivityThread.java:5140)
01-28 13:49:56.200: D/StrictMode(12035): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-28 13:49:56.200: D/StrictMode(12035): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
01-28 13:49:56.200: D/StrictMode(12035): 	at dalvik.system.NativeStart.main(Native Method)
01-28 13:49:56.200: D/StrictMode(12035): StrictMode policy violation; ~duration=28 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
01-28 13:49:56.200: D/StrictMode(12035): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1135)
01-28 13:49:56.200: D/StrictMode(12035): 	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:148)
01-28 13:49:56.200: D/StrictMode(12035): 	at libcore.io.IoBridge.read(IoBridge.java:425)
01-28 13:49:56.200: D/StrictMode(12035): 	at java.io.FileInputStream.read(FileInputStream.java:179)
01-28 13:49:56.200: D/StrictMode(12035): 	at okio.Okio$2.read(Okio.java:136)
01-28 13:49:56.200: D/StrictMode(12035): 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:255)
01-28 13:49:56.200: D/StrictMode(12035): 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:249)
01-28 13:49:56.200: D/StrictMode(12035): 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.readJournal(DiskLruCache.java:268)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.initialize(DiskLruCache.java:207)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.open(DiskLruCache.java:244)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.okhttp.Cache.<init>(Cache.java:143)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:74)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:61)
01-28 13:49:56.200: D/StrictMode(12035): 	at me.siegenthaler.utone.sp.main.application.SimpleApplication.initImageService(SimpleApplication.java:153)
01-28 13:49:56.200: D/StrictMode(12035): 	at me.siegenthaler.utone.sp.main.application.SimpleApplication.onCreate(SimpleApplication.java:59)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4467)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.os.Looper.loop(Looper.java:136)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.ActivityThread.main(ActivityThread.java:5140)
01-28 13:49:56.200: D/StrictMode(12035): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-28 13:49:56.200: D/StrictMode(12035): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
01-28 13:49:56.200: D/StrictMode(12035): 	at dalvik.system.NativeStart.main(Native Method)
01-28 13:49:56.200: D/StrictMode(12035): StrictMode policy violation; ~duration=23 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
01-28 13:49:56.200: D/StrictMode(12035): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1135)
01-28 13:49:56.200: D/StrictMode(12035): 	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:148)
01-28 13:49:56.200: D/StrictMode(12035): 	at libcore.io.IoBridge.read(IoBridge.java:425)
01-28 13:49:56.200: D/StrictMode(12035): 	at java.io.FileInputStream.read(FileInputStream.java:179)
01-28 13:49:56.200: D/StrictMode(12035): 	at okio.Okio$2.read(Okio.java:136)
01-28 13:49:56.200: D/StrictMode(12035): 	at okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.readJournal(DiskLruCache.java:277)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.initialize(DiskLruCache.java:207)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.open(DiskLruCache.java:244)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.okhttp.Cache.<init>(Cache.java:143)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:74)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:61)
01-28 13:49:56.200: D/StrictMode(12035): 	at me.siegenthaler.utone.sp.main.application.SimpleApplication.initImageService(SimpleApplication.java:153)
01-28 13:49:56.200: D/StrictMode(12035): 	at me.siegenthaler.utone.sp.main.application.SimpleApplication.onCreate(SimpleApplication.java:59)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4467)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.os.Looper.loop(Looper.java:136)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.ActivityThread.main(ActivityThread.java:5140)
01-28 13:49:56.200: D/StrictMode(12035): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-28 13:49:56.200: D/StrictMode(12035): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
01-28 13:49:56.200: D/StrictMode(12035): 	at dalvik.system.NativeStart.main(Native Method)
01-28 13:49:56.200: D/StrictMode(12035): StrictMode policy violation; ~duration=21 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
01-28 13:49:56.200: D/StrictMode(12035): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1135)
01-28 13:49:56.200: D/StrictMode(12035): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:106)
01-28 13:49:56.200: D/StrictMode(12035): 	at libcore.io.IoBridge.open(IoBridge.java:393)
01-28 13:49:56.200: D/StrictMode(12035): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
01-28 13:49:56.200: D/StrictMode(12035): 	at okio.Okio.appendingSink(Okio.java:179)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.readJournal(DiskLruCache.java:280)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.initialize(DiskLruCache.java:207)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.okhttp.internal.DiskLruCache.open(DiskLruCache.java:244)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.okhttp.Cache.<init>(Cache.java:143)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:74)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:61)
01-28 13:49:56.200: D/StrictMode(12035): 	at me.siegenthaler.utone.sp.main.application.SimpleApplication.initImageService(SimpleApplication.java:153)
01-28 13:49:56.200: D/StrictMode(12035): 	at me.siegenthaler.utone.sp.main.application.SimpleApplication.onCreate(SimpleApplication.java:59)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4467)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.os.Looper.loop(Looper.java:136)
01-28 13:49:56.200: D/StrictMode(12035): 	at android.app.ActivityThread.main(ActivityThread.java:5140)
01-28 13:49:56.200: D/StrictMode(12035): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-28 13:49:56.200: D/StrictMode(12035): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
01-28 13:49:56.200: D/StrictMode(12035): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
01-28 13:49:56.200: D/StrictMode(12035): 	at dalvik.system.NativeStart.main(Native Method)
```

```
        final Picasso p = new Picasso.Builder(getApplicationContext())
                .downloader(new OkHttpDownloader(getApplicationContext(), DEFAULT_IMAGE_CACHE_SIZE))
                .build();
        Picasso.setSingletonInstance(p);
```

**Comment by dnkoutso** [comment]
This has been reported already. 

Sample app to reproduce?

**Comment by Wolftein** [comment]
The code is what it is causing it, just those 3 lines.

**Comment by dnkoutso** [comment]
Will investigate.

**Comment by JakeWharton** [comment]
Already fixed just not released: https://github.com/square/okhttp/pull/1310

**Comment by JakeWharton** [comment]
Also, in practice, this wasn't a very big deal.
