### ISSUE TITLE
I cant find the supporting libraries

### ISSUE THREAD

**Issue by jjhesk** [square/picasso#867]
```
 Process: com.hb.hkm.hypebeaststore, PID: 4761
    java.lang.RuntimeException: Picasso detected an unsupported OkHttp on the classpath.
    To use OkHttp with this version of Picasso, you'll need:
    1. com.squareup.okhttp:okhttp:1.6.0 (or newer)
    2. com.squareup.okhttp:okhttp-urlconnection:1.6.0 (or newer)
    Note that OkHttp 2.0.0+ is supported!
            at com.squareup.picasso.Utils.createDefaultDownloader(Utils.java:251)
            at com.squareup.picasso.Picasso$Builder.build(Picasso.java:754)
            at com.squareup.picasso.Picasso.with(Picasso.java:597)
            at com.hb.hkm.hypebeaststore.fragments.GridComponents.ListAdapter.feedData(ListAdapter.java:36)
            at com.hb.hkm.hypebeaststore.fragments.GridComponents.ListAdapter.getView(ListAdapter.java:54)
            at android.widget.AbsListView.obtainView(AbsListView.java:2344)


```
I only have include the okhttp:2.2.0.

**Comment by JakeWharton** [comment]
You have the OkHttp dependency but you need to add the one on `okhttp-urlconnection`. The exception message gives you the coordinates to add as dependencies in your build file. Make sure both dependencies are using version 2.2 of OkHttp.

**Comment by jjhesk** [comment]
where is the okhttp-urlconnection?

**Comment by DHuckaby** [comment]
@jjhesk `compile 'com.squareup.okhttp:okhttp-urlconnection:2.2.0'`

**Comment by jjhesk** [comment]
This is possible to specify in the README.MD as a part of setup instruction?

@DHuckaby @JakeWharton

**Comment by JakeWharton** [comment]
No. This is no longer a requirement on master and the exception was already
telling you exactly what was needed.
