### ISSUE TITLE
Handling exceptions that are (re)thrown by Picasso

### ISSUE THREAD

**Issue by radzio** [square/picasso#869]
Hi,

Is it possible to catch exceptions like these? Can I use Thread.UncaughtExceptionHandler? 

```
java.lang.IllegalArgumentException: RemoteViews for widget update exceeds maximum bitmap memory usage (used: 1000000, max: 921600) The total memory cannot exceed that required to fill the device's screen once.
       at android.os.Parcel.readException(Parcel.java:1429)
       at android.os.Parcel.readException(Parcel.java:1379)
       at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.updateAppWidgetIds(IAppWidgetService.java:523)
       at android.appwidget.AppWidgetManager.updateAppWidget(AppWidgetManager.java:333)
       at com.squareup.picasso.RemoteViewsAction$AppWidgetAction.update(RemoteViewsAction.java:99)
       at com.squareup.picasso.RemoteViewsAction.complete(RemoteViewsAction.java:43)
       at com.squareup.picasso.Picasso.deliverAction(Picasso.java:511)
       at com.squareup.picasso.Picasso.complete(Picasso.java:470)
       at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:115)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4963)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

I see that Picasso is throwing exceptions using Handler:
```
Picasso.HANDLER.post(new Runnable() { ...
```

Is it possible to catch this exceptions from my code?

**Comment by dnkoutso** [comment]
I think something else is fundamentally wrong by adding such big bitmap. The platform is warning you about this.

Part of Picassos' vision is to not promote such cases. Fail fast. If you are loading too much then thats whats wrong. Catching and swallowing exceptions degrade the overall platform performance in the sake of "making it work".

**Comment by radzio** [comment]
@dnkoutso  I agree that bitmap was too big but the question is still open - why there is no any possibility to catch exception which are thrown by picasso?
