### ISSUE TITLE
RequestCreator.get throws NPE when contact at Uri doesn't have a photo

### ISSUE THREAD

**Issue by pushbit** [square/picasso#877]
I started noticing this in 2.5.0.  Previously it would return `null`.  Is this change intended?

**Comment by JakeWharton** [comment]
Stacktrace?

**Comment by pushbit** [comment]
```java
java.lang.NullPointerException: stream == null
        at com.squareup.picasso.Utils.checkNotNull(Utils.java:120)
        at com.squareup.picasso.RequestHandler$Result.<init>(RequestHandler.java:62)
        at com.squareup.picasso.ContactsPhotoRequestHandler.load(ContactsPhotoRequestHandler.java:71)
        at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
        at com.squareup.picasso.RequestCreator.get(RequestCreator.java:385)
```
