### ISSUE TITLE
java.io.EOFException

### ISSUE THREAD

**Issue by iceAnson** [square/picasso#929]
can't load image,first request return this log,after that,all return timeout,what's the reason?

```
03-17 10:07:05.247  12962-13079/com.lingan.seeyou W/System.err﹕ java.io.EOFException: \n not found: size=162111 content=34ef1ac5f19f5ebcd766be9ad1b4b6bcd71f5231851379a01663b33ba3e9d71e...
03-17 10:07:05.248  12962-13079/com.lingan.seeyou W/System.err﹕ at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
03-17 10:07:05.248  12962-13079/com.lingan.seeyou W/System.err﹕ at com.squareup.okhttp.internal.http.HttpConnection.readHeaders(HttpConnection.java:209)
03-17 10:07:05.248  12962-13079/com.lingan.seeyou W/System.err﹕ at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:195)
03-17 10:07:05.248  12962-13079/com.lingan.seeyou W/System.err﹕ at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
03-17 10:07:05.249  12962-13079/com.lingan.seeyou W/System.err﹕ at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:791)
03-17 10:07:05.249  12962-13079/com.lingan.seeyou W/System.err﹕ at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:90)
03-17 10:07:05.249  12962-13079/com.lingan.seeyou W/System.err﹕ at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:784)
03-17 10:07:05.249  12962-13079/com.lingan.seeyou W/System.err﹕ at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:645)
03-17 10:07:05.249  12962-13079/com.lingan.seeyou W/System.err﹕ at com.squareup.okhttp.Call.getResponse(Call.java:263)
03-17 10:07:05.249  12962-13079/com.lingan.seeyou W/System.err﹕ at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
03-17 10:07:05.250  12962-13079/com.lingan.seeyou W/System.err﹕ at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
03-17 10:07:05.250  12962-13079/com.lingan.seeyou W/System.err﹕ at com.squareup.okhttp.Call.execute(Call.java:79)
03-17 10:07:05.250  12962-13079/com.lingan.seeyou W/System.err﹕ at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:116)
03-17 10:07:05.250  12962-13079/com.lingan.seeyou W/System.err﹕ at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
03-17 10:07:05.250  12962-13079/com.lingan.seeyou W/System.err﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:215)
03-17 10:07:05.251  12962-13079/com.lingan.seeyou W/System.err﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:162)
03-17 10:07:05.251  12962-13079/com.lingan.seeyou W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
03-17 10:07:05.251  12962-13079/com.lingan.seeyou W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:234)
03-17 10:07:05.251  12962-13079/com.lingan.seeyou W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
03-17 10:07:05.251  12962-13079/com.lingan.seeyou W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
03-17 10:07:05.251  12962-13079/com.lingan.seeyou W/System.err﹕ at java.lang.Thread.run(Thread.java:838)
03-17 10:07:05.252  12962-13079/com.lingan.seeyou W/System.err﹕ at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:391)
03-17 10:07:05.253  12962-13079/com.lingan.seeyou D/Picasso﹕ Hunter      executing    [R12]+13s
```

**Comment by iceAnson** [comment]
it only happens at some device, such as vivo phone

**Comment by iceAnson** [comment]
i use the liberary :
okhttp-2.2.0
okio-1.3.0

**Comment by dnkoutso** [comment]
Too little information. Try another library and see if it works, or is it a bad file or a bad device. This also appears to be in http stack. Not picasso related.
