### ISSUE TITLE
Picasso with RoundedImageView problem after lastest update

### ISSUE THREAD

**Issue by MoshDev** [square/picasso#943]
Am using Picasso with RoundedImageView library, the day before it was working fine, and today seems there is an update on Picasso and now each image loading throws a NullPointerException.

```
    java.lang.NullPointerException
            at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:641)
            at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:578)
            at com.makeramen.roundedimageview.RoundedImageView.applyColorMod(RoundedImageView.java:285)
            at com.makeramen.roundedimageview.RoundedImageView.updateAttrs(RoundedImageView.java:307)
            at com.makeramen.roundedimageview.RoundedImageView.updateAttrs(RoundedImageView.java:312)
            at com.makeramen.roundedimageview.RoundedImageView.updateDrawableAttrs(RoundedImageView.java:258)
            at com.makeramen.roundedimageview.RoundedImageView.setImageDrawable(RoundedImageView.java:207)
            at com.squareup.picasso.PicassoDrawable.setBitmap(PicassoDrawable.java:52)
            at com.squareup.picasso.ImageViewAction.complete(ImageViewAction.java:48)
            at com.squareup.picasso.Picasso.deliverAction(Picasso.java:558)
            at com.squareup.picasso.Picasso.complete(Picasso.java:510)
            at com.squareup.picasso.PicassohandleMessage(Picasso.java:117)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by dnkoutso** [comment]
Most likely related to https://github.com/square/picasso/pull/855

**Comment by ChrisMCMine** [comment]
Same problem with Picasso 2.5.1 and the [Shape ImageView library](https://github.com/siyamed/android-shape-imageview)

**Comment by dnkoutso** [comment]
Please fallback to 2.5.0 for now we are investigating on the issues.

**Comment by dlew** [comment]
I'm looking into this one now...

**Comment by dlew** [comment]
This bug only occurs if you set a `ColorFilter` on the `ImageView` in some way shape or form. In that case, `RoundedImageView` mutates the underlying `Drawable` so it doesn't screw up the shared drawable state.

However, this is actually a bug in RoundedImageView. Its `RoundedDrawable` does not implement `Drawable.getConstantState()`, which is necessary for `LayerDrawable.mutate()` to work properly.

Even without the `mutate()` RoundedImageView doesn't work properly - it doesn't show the image because it doesn't seem to be executing the `TransitionDrawable` properly. I haven't dug in on exactly why but I suspect it is because `RoundedDrawable` doesn't implement `Drawable.Callback`.

AFAIK, none of these are problems with `PicassoDrawable` itself; it's issues with the other library's not-quite-robust-enough implementations of `Drawable`. That said, it's probably not great that `PicassoDrawable` is breaking everyone else's stuff, too.

@dnkoutso I don't know the best route out of here - Maybe reverting `PicassoDrawable`, then trying to get other popular `Drawable`-based libraries to support something as complex as `TransitionDrawable` before trying to reintroduce?

**Comment by dnkoutso** [comment]
@dlew I am starting to feel we should revert for 2.5.2 until we properly test and handle all cases.

I do agree that RoundedImageView should be fixed but we cant depend on that.

**Comment by vinc3m1** [comment]
Technically people should be using the provided [RoundedTransformationBuilder](https://github.com/vinc3m1/RoundedImageView#usage) instead, but I can't speak for other libs.

I know `TransitionDrawable` support is generally tricky, and I didn't think my lib worked without `noFade()` tbh. An ideal solution for me (and probably for other libs) would be to to use a regular drawable in the case of noFade() and TransitionDrawable otherwise. This way using 3rd party `ImageView`s would just require setting noFade() and losing out on that fade anim.

**Comment by JakeWharton** [comment]
Yep. The `noFade()` thing is obvious and a good change regardless as it's an easy one less object allocation per request.
