### ISSUE TITLE
StackOverFlow error from fadein 

### ISSUE THREAD

**Issue by raylee4204** [square/picasso#946]
I'm setting a background image in viewpageradapter. When i scroll through fast and at some point, it throws the following error, and I assume it's coming from fadein effect.

java.lang.StackOverflowError
            at java.lang.ref.FinalizerReference.<init>(FinalizerReference.java:42)
            at java.lang.ref.FinalizerReference.add(FinalizerReference.java:54)
            at android.graphics.Paint.<init>(Paint.java:459)
            at android.graphics.Paint.<init>(Paint.java:450)
            at android.graphics.drawable.ColorDrawable.<init>(ColorDrawable.java:40)
            at android.graphics.drawable.ColorDrawable.<init>(ColorDrawable.java:37)
            at android.graphics.drawable.ColorDrawable$ColorState.newDrawable(ColorDrawable.java:194)
            at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:671)
            at android.graphics.drawable.TransitionDrawable$TransitionState.<init>(TransitionDrawable.java:249)
            at android.graphics.drawable.TransitionDrawable.createConstantState(TransitionDrawable.java:101)
            at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:99)
            at android.graphics.drawable.TransitionDrawable.<init>(TransitionDrawable.java:92)
            at android.graphics.drawable.TransitionDrawable.<init>(TransitionDrawable.java:41)
            at android.graphics.drawable.TransitionDrawable$TransitionState.newDrawable(TransitionDrawable.java:254)
            at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:671)
            at android.graphics.drawable.TransitionDrawable$TransitionState.<init>(TransitionDrawable.java:249)
            at android.graphics.drawable.TransitionDrawable.createConstantState(TransitionDrawable.java:101)
            at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:99)
            at android.graphics.drawable.TransitionDrawable.<init>(TransitionDrawable.java:92)
            at android.graphics.drawable.TransitionDrawable.<init>(TransitionDrawable.java:41)
            at android.graphics.drawable.TransitionDrawable$TransitionState.newDrawable(TransitionDrawable.java:254)
            at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:671)
            at android.graphics.drawable.TransitionDrawable$TransitionState.<init>(TransitionDrawable.java:249)
            at android.graphics.drawable.TransitionDrawable.createConstantState(TransitionDrawable.java:101)
            at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:99)
            at android.graphics.drawable.TransitionDrawable.<init>(TransitionDrawable.java:92)
            at android.graphics.drawable.TransitionDrawable.<init>(TransitionDrawable.java:41)
            at android.graphics.drawable.TransitionDrawable$TransitionState.newDrawable(TransitionDrawable.java:254)
            at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:671)
            at android.graphics.drawable.TransitionDrawable$TransitionState.<init>(TransitionDrawable.java:249)
            at android.graphics.drawable.TransitionDrawable.createConstantState(TransitionDrawable.java:101)
            at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:99)
            at android.graphics.drawable.TransitionDrawable.<init>(TransitionDrawable.java:92)
            at android.graphics.drawable.TransitionDrawable.<init>(TransitionDrawable.java:41)
            at android.graphics.drawable.TransitionDrawable$TransitionState.newDrawable(TransitionDrawable.java:254)
            at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:671)
            at android.graphics.drawable.TransitionDrawable$TransitionState.<init>(TransitionDrawable.java:249)
            at android.graphics.drawable.TransitionDrawable.createConstantState(TransitionDrawable.java:101)
            at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:99)
            at android.graphics.drawable.TransitionDrawable.<init>(TransitionDrawable.java:92)
            at android.graphics.drawable.TransitionDrawable.<init>(TransitionDrawable.java:41)
            at android.graphics.drawable.TransitionDrawable$TransitionState.newDrawable(TransitionDrawable.java:254)
            at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:671)
            at android.graphics.drawable.TransitionDrawable$TransitionState.<init>(TransitionDrawable.java:249)
            at android.graphics.drawable.TransitionDrawable.createConstantState(TransitionDrawable.java:101)
            at android.graphics.drawable.Layer

**Comment by JakeWharton** [comment]
Use versoin 2.5.2 which was released today.

**Comment by raylee4204** [comment]
I'm using the latest version unless 2.5.2 is still not up

**Comment by JakeWharton** [comment]
It's in Maven central: http://repo1.maven.org/maven2/com/squareup/picasso/picasso/2.5.2/
