### ISSUE TITLE
Some files (with metadata) can't be loaded

### ISSUE THREAD

**Issue by pierrexn** [square/picasso#966]
The attached file can't be loaded, if i remove all metadata, there is no more problems...
![img_20150406_101740](https://cloud.githubusercontent.com/assets/1200371/7021669/81863436-dd24-11e4-822b-7b437956c91d.jpg)

**Comment by dnkoutso** [comment]
#907 

```
10513-10513/com.example.picasso W/System.err﹕ java.io.IOException: Cannot reset
05-09 14:48:08.924  10513-10513/com.example.picasso W/System.err﹕ at com.squareup.picasso.MarkableInputStream.reset(MarkableInputStream.java:99)
05-09 14:48:08.924  10513-10513/com.example.picasso W/System.err﹕ at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:140)
05-09 14:48:08.924  10513-10513/com.example.picasso W/System.err﹕ at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
05-09 14:48:08.924  10513-10513/com.example.picasso W/System.err﹕ at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
05-09 14:48:08.924  10513-10513/com.example.picasso W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
05-09 14:48:08.924  10513-10513/com.example.picasso W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-09 14:48:08.924  10513-10513/com.example.picasso W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-09 14:48:08.925  10513-10513/com.example.picasso W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-09 14:48:08.925  10513-10513/com.example.picasso W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
05-09 14:48:08.925  10513-10513/com.example.picasso W/System.err﹕ at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
```

One day we will fix it for 2.5.3
