### ISSUE TITLE
Picasso.resize is not working when width or height is 0

### ISSUE THREAD

**Issue by chaitanya0bhagvan** [square/picasso#989]
The following code does not load the image.

    Picasso.with(context)
		.load(inputImage)
		.resize(width, 0)
		.centerInside()
		.into(imageView);

When I add a listener I get the following exception

    04-22 12:25:45.152  24878-24878/com.example D/ImageCropActivity﹕ Image load failed: file:///storage/emulated/0/Pictures/JPEG_20150422_122538_-436522152.jpg exception: java.lang.IllegalArgumentException: width and height must be > 0
    java.lang.IllegalArgumentException: width and height must be > 0
            at android.graphics.Bitmap.createBitmap(Bitmap.java:815)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:794)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:725)
            at com.squareup.picasso.BitmapHunter.transformResult(BitmapHunter.java:558)
            at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:232)
            at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
            at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

I noticed that if I replaced .resize with .resizeDimen and specify the width or height as 0dp or 0px it works. 

I am using picasso 2.5.2. 

I am not sure whether I am doing something wrong or this is a bug

**Comment by JakeWharton** [comment]
What is the value of `width`?

**Comment by JakeWharton** [comment]
Er, nevermind. That's not the problem. What size is the image file?

**Comment by chaitanya0bhagvan** [comment]
Image size is 640 x 480

**Comment by chaitanya0bhagvan** [comment]
But as I mentioned if I use resizeDimen it works just fine.

**Comment by dnkoutso** [comment]
Probably a cannot reset excepion

**Comment by chaitanya0bhagvan** [comment]
@dnkoutso I am sorry I dint get that

**Comment by JakeWharton** [comment]
@dnkoutso how?

**Comment by dnkoutso** [comment]
Oh nevermind, I just saw the stacktrace posted.

**Comment by chaitanya0bhagvan** [comment]
Is there a way to fix this or a work around?

**Comment by dnkoutso** [comment]
You could apply the transformation yourself, however, I am interested on the real cause of the problem.

**Comment by dnkoutso** [comment]
Closing. Please provide an update if you have found the issue here.

**Comment by JohnWowUs** [comment]
The centerInside and centerCrop transformations ensure that the aspect ratio is preserved but they make an implicit assumption that neither of the resize dimensions will be set to 0.
